
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Machines` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Machines
 * @@TypeGraphQL.type(name: "Machine")
 */
export type MachinesModel = runtime.Types.Result.DefaultSelection<Prisma.$MachinesPayload>

export type AggregateMachines = {
  _count: MachinesCountAggregateOutputType | null
  _avg: MachinesAvgAggregateOutputType | null
  _sum: MachinesSumAggregateOutputType | null
  _min: MachinesMinAggregateOutputType | null
  _max: MachinesMaxAggregateOutputType | null
}

export type MachinesAvgAggregateOutputType = {
  machine_number: number | null
  version_group_id: number | null
  item_id: number | null
  move_id: number | null
}

export type MachinesSumAggregateOutputType = {
  machine_number: number | null
  version_group_id: number | null
  item_id: number | null
  move_id: number | null
}

export type MachinesMinAggregateOutputType = {
  machine_number: number | null
  version_group_id: number | null
  item_id: number | null
  move_id: number | null
}

export type MachinesMaxAggregateOutputType = {
  machine_number: number | null
  version_group_id: number | null
  item_id: number | null
  move_id: number | null
}

export type MachinesCountAggregateOutputType = {
  machine_number: number
  version_group_id: number
  item_id: number
  move_id: number
  _all: number
}


export type MachinesAvgAggregateInputType = {
  machine_number?: true
  version_group_id?: true
  item_id?: true
  move_id?: true
}

export type MachinesSumAggregateInputType = {
  machine_number?: true
  version_group_id?: true
  item_id?: true
  move_id?: true
}

export type MachinesMinAggregateInputType = {
  machine_number?: true
  version_group_id?: true
  item_id?: true
  move_id?: true
}

export type MachinesMaxAggregateInputType = {
  machine_number?: true
  version_group_id?: true
  item_id?: true
  move_id?: true
}

export type MachinesCountAggregateInputType = {
  machine_number?: true
  version_group_id?: true
  item_id?: true
  move_id?: true
  _all?: true
}

export type MachinesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Machines to aggregate.
   */
  where?: Prisma.MachinesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Machines to fetch.
   */
  orderBy?: Prisma.MachinesOrderByWithRelationInput | Prisma.MachinesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MachinesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Machines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Machines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Machines
  **/
  _count?: true | MachinesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MachinesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MachinesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MachinesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MachinesMaxAggregateInputType
}

export type GetMachinesAggregateType<T extends MachinesAggregateArgs> = {
      [P in keyof T & keyof AggregateMachines]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMachines[P]>
    : Prisma.GetScalarType<T[P], AggregateMachines[P]>
}




export type MachinesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MachinesWhereInput
  orderBy?: Prisma.MachinesOrderByWithAggregationInput | Prisma.MachinesOrderByWithAggregationInput[]
  by: Prisma.MachinesScalarFieldEnum[] | Prisma.MachinesScalarFieldEnum
  having?: Prisma.MachinesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MachinesCountAggregateInputType | true
  _avg?: MachinesAvgAggregateInputType
  _sum?: MachinesSumAggregateInputType
  _min?: MachinesMinAggregateInputType
  _max?: MachinesMaxAggregateInputType
}

export type MachinesGroupByOutputType = {
  machine_number: number
  version_group_id: number
  item_id: number
  move_id: number
  _count: MachinesCountAggregateOutputType | null
  _avg: MachinesAvgAggregateOutputType | null
  _sum: MachinesSumAggregateOutputType | null
  _min: MachinesMinAggregateOutputType | null
  _max: MachinesMaxAggregateOutputType | null
}

export type GetMachinesGroupByPayload<T extends MachinesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MachinesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MachinesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MachinesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MachinesGroupByOutputType[P]>
      }
    >
  >



export type MachinesWhereInput = {
  AND?: Prisma.MachinesWhereInput | Prisma.MachinesWhereInput[]
  OR?: Prisma.MachinesWhereInput[]
  NOT?: Prisma.MachinesWhereInput | Prisma.MachinesWhereInput[]
  machine_number?: Prisma.IntFilter<"Machines"> | number
  version_group_id?: Prisma.IntFilter<"Machines"> | number
  item_id?: Prisma.IntFilter<"Machines"> | number
  move_id?: Prisma.IntFilter<"Machines"> | number
  versionGroup?: Prisma.XOR<Prisma.VersionGroupsScalarRelationFilter, Prisma.VersionGroupsWhereInput>
  item?: Prisma.XOR<Prisma.ItemsScalarRelationFilter, Prisma.ItemsWhereInput>
  move?: Prisma.XOR<Prisma.MovesScalarRelationFilter, Prisma.MovesWhereInput>
}

export type MachinesOrderByWithRelationInput = {
  machine_number?: Prisma.SortOrder
  version_group_id?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  move_id?: Prisma.SortOrder
  versionGroup?: Prisma.VersionGroupsOrderByWithRelationInput
  item?: Prisma.ItemsOrderByWithRelationInput
  move?: Prisma.MovesOrderByWithRelationInput
}

export type MachinesWhereUniqueInput = Prisma.AtLeast<{
  machine_number_version_group_id?: Prisma.MachinesMachine_numberVersion_group_idCompoundUniqueInput
  AND?: Prisma.MachinesWhereInput | Prisma.MachinesWhereInput[]
  OR?: Prisma.MachinesWhereInput[]
  NOT?: Prisma.MachinesWhereInput | Prisma.MachinesWhereInput[]
  machine_number?: Prisma.IntFilter<"Machines"> | number
  version_group_id?: Prisma.IntFilter<"Machines"> | number
  item_id?: Prisma.IntFilter<"Machines"> | number
  move_id?: Prisma.IntFilter<"Machines"> | number
  versionGroup?: Prisma.XOR<Prisma.VersionGroupsScalarRelationFilter, Prisma.VersionGroupsWhereInput>
  item?: Prisma.XOR<Prisma.ItemsScalarRelationFilter, Prisma.ItemsWhereInput>
  move?: Prisma.XOR<Prisma.MovesScalarRelationFilter, Prisma.MovesWhereInput>
}, "machine_number_version_group_id">

export type MachinesOrderByWithAggregationInput = {
  machine_number?: Prisma.SortOrder
  version_group_id?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  move_id?: Prisma.SortOrder
  _count?: Prisma.MachinesCountOrderByAggregateInput
  _avg?: Prisma.MachinesAvgOrderByAggregateInput
  _max?: Prisma.MachinesMaxOrderByAggregateInput
  _min?: Prisma.MachinesMinOrderByAggregateInput
  _sum?: Prisma.MachinesSumOrderByAggregateInput
}

export type MachinesScalarWhereWithAggregatesInput = {
  AND?: Prisma.MachinesScalarWhereWithAggregatesInput | Prisma.MachinesScalarWhereWithAggregatesInput[]
  OR?: Prisma.MachinesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MachinesScalarWhereWithAggregatesInput | Prisma.MachinesScalarWhereWithAggregatesInput[]
  machine_number?: Prisma.IntWithAggregatesFilter<"Machines"> | number
  version_group_id?: Prisma.IntWithAggregatesFilter<"Machines"> | number
  item_id?: Prisma.IntWithAggregatesFilter<"Machines"> | number
  move_id?: Prisma.IntWithAggregatesFilter<"Machines"> | number
}

export type MachinesCreateInput = {
  machine_number: number
  versionGroup: Prisma.VersionGroupsCreateNestedOneWithoutMachinesInput
  item: Prisma.ItemsCreateNestedOneWithoutMachinesInput
  move: Prisma.MovesCreateNestedOneWithoutMachinesInput
}

export type MachinesUncheckedCreateInput = {
  machine_number: number
  version_group_id: number
  item_id: number
  move_id: number
}

export type MachinesUpdateInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  versionGroup?: Prisma.VersionGroupsUpdateOneRequiredWithoutMachinesNestedInput
  item?: Prisma.ItemsUpdateOneRequiredWithoutMachinesNestedInput
  move?: Prisma.MovesUpdateOneRequiredWithoutMachinesNestedInput
}

export type MachinesUncheckedUpdateInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  version_group_id?: Prisma.IntFieldUpdateOperationsInput | number
  item_id?: Prisma.IntFieldUpdateOperationsInput | number
  move_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MachinesCreateManyInput = {
  machine_number: number
  version_group_id: number
  item_id: number
  move_id: number
}

export type MachinesUpdateManyMutationInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MachinesUncheckedUpdateManyInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  version_group_id?: Prisma.IntFieldUpdateOperationsInput | number
  item_id?: Prisma.IntFieldUpdateOperationsInput | number
  move_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MachinesListRelationFilter = {
  every?: Prisma.MachinesWhereInput
  some?: Prisma.MachinesWhereInput
  none?: Prisma.MachinesWhereInput
}

export type MachinesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MachinesMachine_numberVersion_group_idCompoundUniqueInput = {
  machine_number: number
  version_group_id: number
}

export type MachinesCountOrderByAggregateInput = {
  machine_number?: Prisma.SortOrder
  version_group_id?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  move_id?: Prisma.SortOrder
}

export type MachinesAvgOrderByAggregateInput = {
  machine_number?: Prisma.SortOrder
  version_group_id?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  move_id?: Prisma.SortOrder
}

export type MachinesMaxOrderByAggregateInput = {
  machine_number?: Prisma.SortOrder
  version_group_id?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  move_id?: Prisma.SortOrder
}

export type MachinesMinOrderByAggregateInput = {
  machine_number?: Prisma.SortOrder
  version_group_id?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  move_id?: Prisma.SortOrder
}

export type MachinesSumOrderByAggregateInput = {
  machine_number?: Prisma.SortOrder
  version_group_id?: Prisma.SortOrder
  item_id?: Prisma.SortOrder
  move_id?: Prisma.SortOrder
}

export type MachinesCreateNestedManyWithoutMoveInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutMoveInput, Prisma.MachinesUncheckedCreateWithoutMoveInput> | Prisma.MachinesCreateWithoutMoveInput[] | Prisma.MachinesUncheckedCreateWithoutMoveInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutMoveInput | Prisma.MachinesCreateOrConnectWithoutMoveInput[]
  createMany?: Prisma.MachinesCreateManyMoveInputEnvelope
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
}

export type MachinesUncheckedCreateNestedManyWithoutMoveInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutMoveInput, Prisma.MachinesUncheckedCreateWithoutMoveInput> | Prisma.MachinesCreateWithoutMoveInput[] | Prisma.MachinesUncheckedCreateWithoutMoveInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutMoveInput | Prisma.MachinesCreateOrConnectWithoutMoveInput[]
  createMany?: Prisma.MachinesCreateManyMoveInputEnvelope
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
}

export type MachinesUpdateManyWithoutMoveNestedInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutMoveInput, Prisma.MachinesUncheckedCreateWithoutMoveInput> | Prisma.MachinesCreateWithoutMoveInput[] | Prisma.MachinesUncheckedCreateWithoutMoveInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutMoveInput | Prisma.MachinesCreateOrConnectWithoutMoveInput[]
  upsert?: Prisma.MachinesUpsertWithWhereUniqueWithoutMoveInput | Prisma.MachinesUpsertWithWhereUniqueWithoutMoveInput[]
  createMany?: Prisma.MachinesCreateManyMoveInputEnvelope
  set?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  disconnect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  delete?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  update?: Prisma.MachinesUpdateWithWhereUniqueWithoutMoveInput | Prisma.MachinesUpdateWithWhereUniqueWithoutMoveInput[]
  updateMany?: Prisma.MachinesUpdateManyWithWhereWithoutMoveInput | Prisma.MachinesUpdateManyWithWhereWithoutMoveInput[]
  deleteMany?: Prisma.MachinesScalarWhereInput | Prisma.MachinesScalarWhereInput[]
}

export type MachinesUncheckedUpdateManyWithoutMoveNestedInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutMoveInput, Prisma.MachinesUncheckedCreateWithoutMoveInput> | Prisma.MachinesCreateWithoutMoveInput[] | Prisma.MachinesUncheckedCreateWithoutMoveInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutMoveInput | Prisma.MachinesCreateOrConnectWithoutMoveInput[]
  upsert?: Prisma.MachinesUpsertWithWhereUniqueWithoutMoveInput | Prisma.MachinesUpsertWithWhereUniqueWithoutMoveInput[]
  createMany?: Prisma.MachinesCreateManyMoveInputEnvelope
  set?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  disconnect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  delete?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  update?: Prisma.MachinesUpdateWithWhereUniqueWithoutMoveInput | Prisma.MachinesUpdateWithWhereUniqueWithoutMoveInput[]
  updateMany?: Prisma.MachinesUpdateManyWithWhereWithoutMoveInput | Prisma.MachinesUpdateManyWithWhereWithoutMoveInput[]
  deleteMany?: Prisma.MachinesScalarWhereInput | Prisma.MachinesScalarWhereInput[]
}

export type MachinesCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutItemInput, Prisma.MachinesUncheckedCreateWithoutItemInput> | Prisma.MachinesCreateWithoutItemInput[] | Prisma.MachinesUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutItemInput | Prisma.MachinesCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.MachinesCreateManyItemInputEnvelope
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
}

export type MachinesUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutItemInput, Prisma.MachinesUncheckedCreateWithoutItemInput> | Prisma.MachinesCreateWithoutItemInput[] | Prisma.MachinesUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutItemInput | Prisma.MachinesCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.MachinesCreateManyItemInputEnvelope
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
}

export type MachinesUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutItemInput, Prisma.MachinesUncheckedCreateWithoutItemInput> | Prisma.MachinesCreateWithoutItemInput[] | Prisma.MachinesUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutItemInput | Prisma.MachinesCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.MachinesUpsertWithWhereUniqueWithoutItemInput | Prisma.MachinesUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.MachinesCreateManyItemInputEnvelope
  set?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  disconnect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  delete?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  update?: Prisma.MachinesUpdateWithWhereUniqueWithoutItemInput | Prisma.MachinesUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.MachinesUpdateManyWithWhereWithoutItemInput | Prisma.MachinesUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.MachinesScalarWhereInput | Prisma.MachinesScalarWhereInput[]
}

export type MachinesUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutItemInput, Prisma.MachinesUncheckedCreateWithoutItemInput> | Prisma.MachinesCreateWithoutItemInput[] | Prisma.MachinesUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutItemInput | Prisma.MachinesCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.MachinesUpsertWithWhereUniqueWithoutItemInput | Prisma.MachinesUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.MachinesCreateManyItemInputEnvelope
  set?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  disconnect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  delete?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  update?: Prisma.MachinesUpdateWithWhereUniqueWithoutItemInput | Prisma.MachinesUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.MachinesUpdateManyWithWhereWithoutItemInput | Prisma.MachinesUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.MachinesScalarWhereInput | Prisma.MachinesScalarWhereInput[]
}

export type MachinesCreateNestedManyWithoutVersionGroupInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutVersionGroupInput, Prisma.MachinesUncheckedCreateWithoutVersionGroupInput> | Prisma.MachinesCreateWithoutVersionGroupInput[] | Prisma.MachinesUncheckedCreateWithoutVersionGroupInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutVersionGroupInput | Prisma.MachinesCreateOrConnectWithoutVersionGroupInput[]
  createMany?: Prisma.MachinesCreateManyVersionGroupInputEnvelope
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
}

export type MachinesUncheckedCreateNestedManyWithoutVersionGroupInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutVersionGroupInput, Prisma.MachinesUncheckedCreateWithoutVersionGroupInput> | Prisma.MachinesCreateWithoutVersionGroupInput[] | Prisma.MachinesUncheckedCreateWithoutVersionGroupInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutVersionGroupInput | Prisma.MachinesCreateOrConnectWithoutVersionGroupInput[]
  createMany?: Prisma.MachinesCreateManyVersionGroupInputEnvelope
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
}

export type MachinesUpdateManyWithoutVersionGroupNestedInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutVersionGroupInput, Prisma.MachinesUncheckedCreateWithoutVersionGroupInput> | Prisma.MachinesCreateWithoutVersionGroupInput[] | Prisma.MachinesUncheckedCreateWithoutVersionGroupInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutVersionGroupInput | Prisma.MachinesCreateOrConnectWithoutVersionGroupInput[]
  upsert?: Prisma.MachinesUpsertWithWhereUniqueWithoutVersionGroupInput | Prisma.MachinesUpsertWithWhereUniqueWithoutVersionGroupInput[]
  createMany?: Prisma.MachinesCreateManyVersionGroupInputEnvelope
  set?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  disconnect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  delete?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  update?: Prisma.MachinesUpdateWithWhereUniqueWithoutVersionGroupInput | Prisma.MachinesUpdateWithWhereUniqueWithoutVersionGroupInput[]
  updateMany?: Prisma.MachinesUpdateManyWithWhereWithoutVersionGroupInput | Prisma.MachinesUpdateManyWithWhereWithoutVersionGroupInput[]
  deleteMany?: Prisma.MachinesScalarWhereInput | Prisma.MachinesScalarWhereInput[]
}

export type MachinesUncheckedUpdateManyWithoutVersionGroupNestedInput = {
  create?: Prisma.XOR<Prisma.MachinesCreateWithoutVersionGroupInput, Prisma.MachinesUncheckedCreateWithoutVersionGroupInput> | Prisma.MachinesCreateWithoutVersionGroupInput[] | Prisma.MachinesUncheckedCreateWithoutVersionGroupInput[]
  connectOrCreate?: Prisma.MachinesCreateOrConnectWithoutVersionGroupInput | Prisma.MachinesCreateOrConnectWithoutVersionGroupInput[]
  upsert?: Prisma.MachinesUpsertWithWhereUniqueWithoutVersionGroupInput | Prisma.MachinesUpsertWithWhereUniqueWithoutVersionGroupInput[]
  createMany?: Prisma.MachinesCreateManyVersionGroupInputEnvelope
  set?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  disconnect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  delete?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  connect?: Prisma.MachinesWhereUniqueInput | Prisma.MachinesWhereUniqueInput[]
  update?: Prisma.MachinesUpdateWithWhereUniqueWithoutVersionGroupInput | Prisma.MachinesUpdateWithWhereUniqueWithoutVersionGroupInput[]
  updateMany?: Prisma.MachinesUpdateManyWithWhereWithoutVersionGroupInput | Prisma.MachinesUpdateManyWithWhereWithoutVersionGroupInput[]
  deleteMany?: Prisma.MachinesScalarWhereInput | Prisma.MachinesScalarWhereInput[]
}

export type MachinesCreateWithoutMoveInput = {
  machine_number: number
  versionGroup: Prisma.VersionGroupsCreateNestedOneWithoutMachinesInput
  item: Prisma.ItemsCreateNestedOneWithoutMachinesInput
}

export type MachinesUncheckedCreateWithoutMoveInput = {
  machine_number: number
  version_group_id: number
  item_id: number
}

export type MachinesCreateOrConnectWithoutMoveInput = {
  where: Prisma.MachinesWhereUniqueInput
  create: Prisma.XOR<Prisma.MachinesCreateWithoutMoveInput, Prisma.MachinesUncheckedCreateWithoutMoveInput>
}

export type MachinesCreateManyMoveInputEnvelope = {
  data: Prisma.MachinesCreateManyMoveInput | Prisma.MachinesCreateManyMoveInput[]
  skipDuplicates?: boolean
}

export type MachinesUpsertWithWhereUniqueWithoutMoveInput = {
  where: Prisma.MachinesWhereUniqueInput
  update: Prisma.XOR<Prisma.MachinesUpdateWithoutMoveInput, Prisma.MachinesUncheckedUpdateWithoutMoveInput>
  create: Prisma.XOR<Prisma.MachinesCreateWithoutMoveInput, Prisma.MachinesUncheckedCreateWithoutMoveInput>
}

export type MachinesUpdateWithWhereUniqueWithoutMoveInput = {
  where: Prisma.MachinesWhereUniqueInput
  data: Prisma.XOR<Prisma.MachinesUpdateWithoutMoveInput, Prisma.MachinesUncheckedUpdateWithoutMoveInput>
}

export type MachinesUpdateManyWithWhereWithoutMoveInput = {
  where: Prisma.MachinesScalarWhereInput
  data: Prisma.XOR<Prisma.MachinesUpdateManyMutationInput, Prisma.MachinesUncheckedUpdateManyWithoutMoveInput>
}

export type MachinesScalarWhereInput = {
  AND?: Prisma.MachinesScalarWhereInput | Prisma.MachinesScalarWhereInput[]
  OR?: Prisma.MachinesScalarWhereInput[]
  NOT?: Prisma.MachinesScalarWhereInput | Prisma.MachinesScalarWhereInput[]
  machine_number?: Prisma.IntFilter<"Machines"> | number
  version_group_id?: Prisma.IntFilter<"Machines"> | number
  item_id?: Prisma.IntFilter<"Machines"> | number
  move_id?: Prisma.IntFilter<"Machines"> | number
}

export type MachinesCreateWithoutItemInput = {
  machine_number: number
  versionGroup: Prisma.VersionGroupsCreateNestedOneWithoutMachinesInput
  move: Prisma.MovesCreateNestedOneWithoutMachinesInput
}

export type MachinesUncheckedCreateWithoutItemInput = {
  machine_number: number
  version_group_id: number
  move_id: number
}

export type MachinesCreateOrConnectWithoutItemInput = {
  where: Prisma.MachinesWhereUniqueInput
  create: Prisma.XOR<Prisma.MachinesCreateWithoutItemInput, Prisma.MachinesUncheckedCreateWithoutItemInput>
}

export type MachinesCreateManyItemInputEnvelope = {
  data: Prisma.MachinesCreateManyItemInput | Prisma.MachinesCreateManyItemInput[]
  skipDuplicates?: boolean
}

export type MachinesUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.MachinesWhereUniqueInput
  update: Prisma.XOR<Prisma.MachinesUpdateWithoutItemInput, Prisma.MachinesUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.MachinesCreateWithoutItemInput, Prisma.MachinesUncheckedCreateWithoutItemInput>
}

export type MachinesUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.MachinesWhereUniqueInput
  data: Prisma.XOR<Prisma.MachinesUpdateWithoutItemInput, Prisma.MachinesUncheckedUpdateWithoutItemInput>
}

export type MachinesUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.MachinesScalarWhereInput
  data: Prisma.XOR<Prisma.MachinesUpdateManyMutationInput, Prisma.MachinesUncheckedUpdateManyWithoutItemInput>
}

export type MachinesCreateWithoutVersionGroupInput = {
  machine_number: number
  item: Prisma.ItemsCreateNestedOneWithoutMachinesInput
  move: Prisma.MovesCreateNestedOneWithoutMachinesInput
}

export type MachinesUncheckedCreateWithoutVersionGroupInput = {
  machine_number: number
  item_id: number
  move_id: number
}

export type MachinesCreateOrConnectWithoutVersionGroupInput = {
  where: Prisma.MachinesWhereUniqueInput
  create: Prisma.XOR<Prisma.MachinesCreateWithoutVersionGroupInput, Prisma.MachinesUncheckedCreateWithoutVersionGroupInput>
}

export type MachinesCreateManyVersionGroupInputEnvelope = {
  data: Prisma.MachinesCreateManyVersionGroupInput | Prisma.MachinesCreateManyVersionGroupInput[]
  skipDuplicates?: boolean
}

export type MachinesUpsertWithWhereUniqueWithoutVersionGroupInput = {
  where: Prisma.MachinesWhereUniqueInput
  update: Prisma.XOR<Prisma.MachinesUpdateWithoutVersionGroupInput, Prisma.MachinesUncheckedUpdateWithoutVersionGroupInput>
  create: Prisma.XOR<Prisma.MachinesCreateWithoutVersionGroupInput, Prisma.MachinesUncheckedCreateWithoutVersionGroupInput>
}

export type MachinesUpdateWithWhereUniqueWithoutVersionGroupInput = {
  where: Prisma.MachinesWhereUniqueInput
  data: Prisma.XOR<Prisma.MachinesUpdateWithoutVersionGroupInput, Prisma.MachinesUncheckedUpdateWithoutVersionGroupInput>
}

export type MachinesUpdateManyWithWhereWithoutVersionGroupInput = {
  where: Prisma.MachinesScalarWhereInput
  data: Prisma.XOR<Prisma.MachinesUpdateManyMutationInput, Prisma.MachinesUncheckedUpdateManyWithoutVersionGroupInput>
}

export type MachinesCreateManyMoveInput = {
  machine_number: number
  version_group_id: number
  item_id: number
}

export type MachinesUpdateWithoutMoveInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  versionGroup?: Prisma.VersionGroupsUpdateOneRequiredWithoutMachinesNestedInput
  item?: Prisma.ItemsUpdateOneRequiredWithoutMachinesNestedInput
}

export type MachinesUncheckedUpdateWithoutMoveInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  version_group_id?: Prisma.IntFieldUpdateOperationsInput | number
  item_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MachinesUncheckedUpdateManyWithoutMoveInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  version_group_id?: Prisma.IntFieldUpdateOperationsInput | number
  item_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MachinesCreateManyItemInput = {
  machine_number: number
  version_group_id: number
  move_id: number
}

export type MachinesUpdateWithoutItemInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  versionGroup?: Prisma.VersionGroupsUpdateOneRequiredWithoutMachinesNestedInput
  move?: Prisma.MovesUpdateOneRequiredWithoutMachinesNestedInput
}

export type MachinesUncheckedUpdateWithoutItemInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  version_group_id?: Prisma.IntFieldUpdateOperationsInput | number
  move_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MachinesUncheckedUpdateManyWithoutItemInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  version_group_id?: Prisma.IntFieldUpdateOperationsInput | number
  move_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MachinesCreateManyVersionGroupInput = {
  machine_number: number
  item_id: number
  move_id: number
}

export type MachinesUpdateWithoutVersionGroupInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  item?: Prisma.ItemsUpdateOneRequiredWithoutMachinesNestedInput
  move?: Prisma.MovesUpdateOneRequiredWithoutMachinesNestedInput
}

export type MachinesUncheckedUpdateWithoutVersionGroupInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  item_id?: Prisma.IntFieldUpdateOperationsInput | number
  move_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type MachinesUncheckedUpdateManyWithoutVersionGroupInput = {
  machine_number?: Prisma.IntFieldUpdateOperationsInput | number
  item_id?: Prisma.IntFieldUpdateOperationsInput | number
  move_id?: Prisma.IntFieldUpdateOperationsInput | number
}



export type MachinesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  machine_number?: boolean
  version_group_id?: boolean
  item_id?: boolean
  move_id?: boolean
  versionGroup?: boolean | Prisma.VersionGroupsDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemsDefaultArgs<ExtArgs>
  move?: boolean | Prisma.MovesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["machines"]>

export type MachinesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  machine_number?: boolean
  version_group_id?: boolean
  item_id?: boolean
  move_id?: boolean
  versionGroup?: boolean | Prisma.VersionGroupsDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemsDefaultArgs<ExtArgs>
  move?: boolean | Prisma.MovesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["machines"]>

export type MachinesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  machine_number?: boolean
  version_group_id?: boolean
  item_id?: boolean
  move_id?: boolean
  versionGroup?: boolean | Prisma.VersionGroupsDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemsDefaultArgs<ExtArgs>
  move?: boolean | Prisma.MovesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["machines"]>

export type MachinesSelectScalar = {
  machine_number?: boolean
  version_group_id?: boolean
  item_id?: boolean
  move_id?: boolean
}

export type MachinesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"machine_number" | "version_group_id" | "item_id" | "move_id", ExtArgs["result"]["machines"]>
export type MachinesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  versionGroup?: boolean | Prisma.VersionGroupsDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemsDefaultArgs<ExtArgs>
  move?: boolean | Prisma.MovesDefaultArgs<ExtArgs>
}
export type MachinesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  versionGroup?: boolean | Prisma.VersionGroupsDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemsDefaultArgs<ExtArgs>
  move?: boolean | Prisma.MovesDefaultArgs<ExtArgs>
}
export type MachinesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  versionGroup?: boolean | Prisma.VersionGroupsDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemsDefaultArgs<ExtArgs>
  move?: boolean | Prisma.MovesDefaultArgs<ExtArgs>
}

export type $MachinesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Machines"
  objects: {
    versionGroup: Prisma.$VersionGroupsPayload<ExtArgs>
    item: Prisma.$ItemsPayload<ExtArgs>
    move: Prisma.$MovesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    machine_number: number
    version_group_id: number
    item_id: number
    move_id: number
  }, ExtArgs["result"]["machines"]>
  composites: {}
}

export type MachinesGetPayload<S extends boolean | null | undefined | MachinesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MachinesPayload, S>

export type MachinesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MachinesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MachinesCountAggregateInputType | true
  }

export interface MachinesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Machines'], meta: { name: 'Machines' } }
  /**
   * Find zero or one Machines that matches the filter.
   * @param {MachinesFindUniqueArgs} args - Arguments to find a Machines
   * @example
   * // Get one Machines
   * const machines = await prisma.machines.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MachinesFindUniqueArgs>(args: Prisma.SelectSubset<T, MachinesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MachinesClient<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Machines that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MachinesFindUniqueOrThrowArgs} args - Arguments to find a Machines
   * @example
   * // Get one Machines
   * const machines = await prisma.machines.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MachinesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MachinesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MachinesClient<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Machines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MachinesFindFirstArgs} args - Arguments to find a Machines
   * @example
   * // Get one Machines
   * const machines = await prisma.machines.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MachinesFindFirstArgs>(args?: Prisma.SelectSubset<T, MachinesFindFirstArgs<ExtArgs>>): Prisma.Prisma__MachinesClient<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Machines that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MachinesFindFirstOrThrowArgs} args - Arguments to find a Machines
   * @example
   * // Get one Machines
   * const machines = await prisma.machines.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MachinesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MachinesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MachinesClient<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Machines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MachinesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Machines
   * const machines = await prisma.machines.findMany()
   * 
   * // Get first 10 Machines
   * const machines = await prisma.machines.findMany({ take: 10 })
   * 
   * // Only select the `machine_number`
   * const machinesWithMachine_numberOnly = await prisma.machines.findMany({ select: { machine_number: true } })
   * 
   */
  findMany<T extends MachinesFindManyArgs>(args?: Prisma.SelectSubset<T, MachinesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Machines.
   * @param {MachinesCreateArgs} args - Arguments to create a Machines.
   * @example
   * // Create one Machines
   * const Machines = await prisma.machines.create({
   *   data: {
   *     // ... data to create a Machines
   *   }
   * })
   * 
   */
  create<T extends MachinesCreateArgs>(args: Prisma.SelectSubset<T, MachinesCreateArgs<ExtArgs>>): Prisma.Prisma__MachinesClient<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Machines.
   * @param {MachinesCreateManyArgs} args - Arguments to create many Machines.
   * @example
   * // Create many Machines
   * const machines = await prisma.machines.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MachinesCreateManyArgs>(args?: Prisma.SelectSubset<T, MachinesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Machines and returns the data saved in the database.
   * @param {MachinesCreateManyAndReturnArgs} args - Arguments to create many Machines.
   * @example
   * // Create many Machines
   * const machines = await prisma.machines.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Machines and only return the `machine_number`
   * const machinesWithMachine_numberOnly = await prisma.machines.createManyAndReturn({
   *   select: { machine_number: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MachinesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MachinesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Machines.
   * @param {MachinesDeleteArgs} args - Arguments to delete one Machines.
   * @example
   * // Delete one Machines
   * const Machines = await prisma.machines.delete({
   *   where: {
   *     // ... filter to delete one Machines
   *   }
   * })
   * 
   */
  delete<T extends MachinesDeleteArgs>(args: Prisma.SelectSubset<T, MachinesDeleteArgs<ExtArgs>>): Prisma.Prisma__MachinesClient<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Machines.
   * @param {MachinesUpdateArgs} args - Arguments to update one Machines.
   * @example
   * // Update one Machines
   * const machines = await prisma.machines.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MachinesUpdateArgs>(args: Prisma.SelectSubset<T, MachinesUpdateArgs<ExtArgs>>): Prisma.Prisma__MachinesClient<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Machines.
   * @param {MachinesDeleteManyArgs} args - Arguments to filter Machines to delete.
   * @example
   * // Delete a few Machines
   * const { count } = await prisma.machines.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MachinesDeleteManyArgs>(args?: Prisma.SelectSubset<T, MachinesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Machines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MachinesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Machines
   * const machines = await prisma.machines.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MachinesUpdateManyArgs>(args: Prisma.SelectSubset<T, MachinesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Machines and returns the data updated in the database.
   * @param {MachinesUpdateManyAndReturnArgs} args - Arguments to update many Machines.
   * @example
   * // Update many Machines
   * const machines = await prisma.machines.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Machines and only return the `machine_number`
   * const machinesWithMachine_numberOnly = await prisma.machines.updateManyAndReturn({
   *   select: { machine_number: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MachinesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MachinesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Machines.
   * @param {MachinesUpsertArgs} args - Arguments to update or create a Machines.
   * @example
   * // Update or create a Machines
   * const machines = await prisma.machines.upsert({
   *   create: {
   *     // ... data to create a Machines
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Machines we want to update
   *   }
   * })
   */
  upsert<T extends MachinesUpsertArgs>(args: Prisma.SelectSubset<T, MachinesUpsertArgs<ExtArgs>>): Prisma.Prisma__MachinesClient<runtime.Types.Result.GetResult<Prisma.$MachinesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Machines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MachinesCountArgs} args - Arguments to filter Machines to count.
   * @example
   * // Count the number of Machines
   * const count = await prisma.machines.count({
   *   where: {
   *     // ... the filter for the Machines we want to count
   *   }
   * })
  **/
  count<T extends MachinesCountArgs>(
    args?: Prisma.Subset<T, MachinesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MachinesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Machines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MachinesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MachinesAggregateArgs>(args: Prisma.Subset<T, MachinesAggregateArgs>): Prisma.PrismaPromise<GetMachinesAggregateType<T>>

  /**
   * Group by Machines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MachinesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MachinesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MachinesGroupByArgs['orderBy'] }
      : { orderBy?: MachinesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MachinesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMachinesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Machines model
 */
readonly fields: MachinesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Machines.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MachinesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  versionGroup<T extends Prisma.VersionGroupsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VersionGroupsDefaultArgs<ExtArgs>>): Prisma.Prisma__VersionGroupsClient<runtime.Types.Result.GetResult<Prisma.$VersionGroupsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  item<T extends Prisma.ItemsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ItemsDefaultArgs<ExtArgs>>): Prisma.Prisma__ItemsClient<runtime.Types.Result.GetResult<Prisma.$ItemsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  move<T extends Prisma.MovesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MovesDefaultArgs<ExtArgs>>): Prisma.Prisma__MovesClient<runtime.Types.Result.GetResult<Prisma.$MovesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Machines model
 */
export interface MachinesFieldRefs {
  readonly machine_number: Prisma.FieldRef<"Machines", 'Int'>
  readonly version_group_id: Prisma.FieldRef<"Machines", 'Int'>
  readonly item_id: Prisma.FieldRef<"Machines", 'Int'>
  readonly move_id: Prisma.FieldRef<"Machines", 'Int'>
}
    

// Custom InputTypes
/**
 * Machines findUnique
 */
export type MachinesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
  /**
   * Filter, which Machines to fetch.
   */
  where: Prisma.MachinesWhereUniqueInput
}

/**
 * Machines findUniqueOrThrow
 */
export type MachinesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
  /**
   * Filter, which Machines to fetch.
   */
  where: Prisma.MachinesWhereUniqueInput
}

/**
 * Machines findFirst
 */
export type MachinesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
  /**
   * Filter, which Machines to fetch.
   */
  where?: Prisma.MachinesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Machines to fetch.
   */
  orderBy?: Prisma.MachinesOrderByWithRelationInput | Prisma.MachinesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Machines.
   */
  cursor?: Prisma.MachinesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Machines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Machines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Machines.
   */
  distinct?: Prisma.MachinesScalarFieldEnum | Prisma.MachinesScalarFieldEnum[]
}

/**
 * Machines findFirstOrThrow
 */
export type MachinesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
  /**
   * Filter, which Machines to fetch.
   */
  where?: Prisma.MachinesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Machines to fetch.
   */
  orderBy?: Prisma.MachinesOrderByWithRelationInput | Prisma.MachinesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Machines.
   */
  cursor?: Prisma.MachinesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Machines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Machines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Machines.
   */
  distinct?: Prisma.MachinesScalarFieldEnum | Prisma.MachinesScalarFieldEnum[]
}

/**
 * Machines findMany
 */
export type MachinesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
  /**
   * Filter, which Machines to fetch.
   */
  where?: Prisma.MachinesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Machines to fetch.
   */
  orderBy?: Prisma.MachinesOrderByWithRelationInput | Prisma.MachinesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Machines.
   */
  cursor?: Prisma.MachinesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Machines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Machines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Machines.
   */
  distinct?: Prisma.MachinesScalarFieldEnum | Prisma.MachinesScalarFieldEnum[]
}

/**
 * Machines create
 */
export type MachinesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
  /**
   * The data needed to create a Machines.
   */
  data: Prisma.XOR<Prisma.MachinesCreateInput, Prisma.MachinesUncheckedCreateInput>
}

/**
 * Machines createMany
 */
export type MachinesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Machines.
   */
  data: Prisma.MachinesCreateManyInput | Prisma.MachinesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Machines createManyAndReturn
 */
export type MachinesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * The data used to create many Machines.
   */
  data: Prisma.MachinesCreateManyInput | Prisma.MachinesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Machines update
 */
export type MachinesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
  /**
   * The data needed to update a Machines.
   */
  data: Prisma.XOR<Prisma.MachinesUpdateInput, Prisma.MachinesUncheckedUpdateInput>
  /**
   * Choose, which Machines to update.
   */
  where: Prisma.MachinesWhereUniqueInput
}

/**
 * Machines updateMany
 */
export type MachinesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Machines.
   */
  data: Prisma.XOR<Prisma.MachinesUpdateManyMutationInput, Prisma.MachinesUncheckedUpdateManyInput>
  /**
   * Filter which Machines to update
   */
  where?: Prisma.MachinesWhereInput
  /**
   * Limit how many Machines to update.
   */
  limit?: number
}

/**
 * Machines updateManyAndReturn
 */
export type MachinesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * The data used to update Machines.
   */
  data: Prisma.XOR<Prisma.MachinesUpdateManyMutationInput, Prisma.MachinesUncheckedUpdateManyInput>
  /**
   * Filter which Machines to update
   */
  where?: Prisma.MachinesWhereInput
  /**
   * Limit how many Machines to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Machines upsert
 */
export type MachinesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
  /**
   * The filter to search for the Machines to update in case it exists.
   */
  where: Prisma.MachinesWhereUniqueInput
  /**
   * In case the Machines found by the `where` argument doesn't exist, create a new Machines with this data.
   */
  create: Prisma.XOR<Prisma.MachinesCreateInput, Prisma.MachinesUncheckedCreateInput>
  /**
   * In case the Machines was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MachinesUpdateInput, Prisma.MachinesUncheckedUpdateInput>
}

/**
 * Machines delete
 */
export type MachinesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
  /**
   * Filter which Machines to delete.
   */
  where: Prisma.MachinesWhereUniqueInput
}

/**
 * Machines deleteMany
 */
export type MachinesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Machines to delete
   */
  where?: Prisma.MachinesWhereInput
  /**
   * Limit how many Machines to delete.
   */
  limit?: number
}

/**
 * Machines without action
 */
export type MachinesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machines
   */
  select?: Prisma.MachinesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machines
   */
  omit?: Prisma.MachinesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachinesInclude<ExtArgs> | null
}
