
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Natures` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Natures
 * @@TypeGraphQL.type(name: "Nature")
 */
export type NaturesModel = runtime.Types.Result.DefaultSelection<Prisma.$NaturesPayload>

export type AggregateNatures = {
  _count: NaturesCountAggregateOutputType | null
  _avg: NaturesAvgAggregateOutputType | null
  _sum: NaturesSumAggregateOutputType | null
  _min: NaturesMinAggregateOutputType | null
  _max: NaturesMaxAggregateOutputType | null
}

export type NaturesAvgAggregateOutputType = {
  id: number | null
  decreased_stat_id: number | null
  increased_stat_id: number | null
  hates_flavor_id: number | null
  likes_flavor_id: number | null
  game_index: number | null
}

export type NaturesSumAggregateOutputType = {
  id: number | null
  decreased_stat_id: number | null
  increased_stat_id: number | null
  hates_flavor_id: number | null
  likes_flavor_id: number | null
  game_index: number | null
}

export type NaturesMinAggregateOutputType = {
  id: number | null
  identifier: string | null
  decreased_stat_id: number | null
  increased_stat_id: number | null
  hates_flavor_id: number | null
  likes_flavor_id: number | null
  game_index: number | null
}

export type NaturesMaxAggregateOutputType = {
  id: number | null
  identifier: string | null
  decreased_stat_id: number | null
  increased_stat_id: number | null
  hates_flavor_id: number | null
  likes_flavor_id: number | null
  game_index: number | null
}

export type NaturesCountAggregateOutputType = {
  id: number
  identifier: number
  decreased_stat_id: number
  increased_stat_id: number
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
  _all: number
}


export type NaturesAvgAggregateInputType = {
  id?: true
  decreased_stat_id?: true
  increased_stat_id?: true
  hates_flavor_id?: true
  likes_flavor_id?: true
  game_index?: true
}

export type NaturesSumAggregateInputType = {
  id?: true
  decreased_stat_id?: true
  increased_stat_id?: true
  hates_flavor_id?: true
  likes_flavor_id?: true
  game_index?: true
}

export type NaturesMinAggregateInputType = {
  id?: true
  identifier?: true
  decreased_stat_id?: true
  increased_stat_id?: true
  hates_flavor_id?: true
  likes_flavor_id?: true
  game_index?: true
}

export type NaturesMaxAggregateInputType = {
  id?: true
  identifier?: true
  decreased_stat_id?: true
  increased_stat_id?: true
  hates_flavor_id?: true
  likes_flavor_id?: true
  game_index?: true
}

export type NaturesCountAggregateInputType = {
  id?: true
  identifier?: true
  decreased_stat_id?: true
  increased_stat_id?: true
  hates_flavor_id?: true
  likes_flavor_id?: true
  game_index?: true
  _all?: true
}

export type NaturesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Natures to aggregate.
   */
  where?: Prisma.NaturesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Natures to fetch.
   */
  orderBy?: Prisma.NaturesOrderByWithRelationInput | Prisma.NaturesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NaturesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Natures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Natures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Natures
  **/
  _count?: true | NaturesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NaturesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NaturesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NaturesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NaturesMaxAggregateInputType
}

export type GetNaturesAggregateType<T extends NaturesAggregateArgs> = {
      [P in keyof T & keyof AggregateNatures]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNatures[P]>
    : Prisma.GetScalarType<T[P], AggregateNatures[P]>
}




export type NaturesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NaturesWhereInput
  orderBy?: Prisma.NaturesOrderByWithAggregationInput | Prisma.NaturesOrderByWithAggregationInput[]
  by: Prisma.NaturesScalarFieldEnum[] | Prisma.NaturesScalarFieldEnum
  having?: Prisma.NaturesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NaturesCountAggregateInputType | true
  _avg?: NaturesAvgAggregateInputType
  _sum?: NaturesSumAggregateInputType
  _min?: NaturesMinAggregateInputType
  _max?: NaturesMaxAggregateInputType
}

export type NaturesGroupByOutputType = {
  id: number
  identifier: string
  decreased_stat_id: number
  increased_stat_id: number
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
  _count: NaturesCountAggregateOutputType | null
  _avg: NaturesAvgAggregateOutputType | null
  _sum: NaturesSumAggregateOutputType | null
  _min: NaturesMinAggregateOutputType | null
  _max: NaturesMaxAggregateOutputType | null
}

export type GetNaturesGroupByPayload<T extends NaturesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NaturesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NaturesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NaturesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NaturesGroupByOutputType[P]>
      }
    >
  >



export type NaturesWhereInput = {
  AND?: Prisma.NaturesWhereInput | Prisma.NaturesWhereInput[]
  OR?: Prisma.NaturesWhereInput[]
  NOT?: Prisma.NaturesWhereInput | Prisma.NaturesWhereInput[]
  id?: Prisma.IntFilter<"Natures"> | number
  identifier?: Prisma.StringFilter<"Natures"> | string
  decreased_stat_id?: Prisma.IntFilter<"Natures"> | number
  increased_stat_id?: Prisma.IntFilter<"Natures"> | number
  hates_flavor_id?: Prisma.IntFilter<"Natures"> | number
  likes_flavor_id?: Prisma.IntFilter<"Natures"> | number
  game_index?: Prisma.IntFilter<"Natures"> | number
  decreasedStat?: Prisma.XOR<Prisma.StatsScalarRelationFilter, Prisma.StatsWhereInput>
  increasedStat?: Prisma.XOR<Prisma.StatsScalarRelationFilter, Prisma.StatsWhereInput>
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesListRelationFilter
}

export type NaturesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  decreased_stat_id?: Prisma.SortOrder
  increased_stat_id?: Prisma.SortOrder
  hates_flavor_id?: Prisma.SortOrder
  likes_flavor_id?: Prisma.SortOrder
  game_index?: Prisma.SortOrder
  decreasedStat?: Prisma.StatsOrderByWithRelationInput
  increasedStat?: Prisma.StatsOrderByWithRelationInput
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesOrderByRelationAggregateInput
}

export type NaturesWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.NaturesWhereInput | Prisma.NaturesWhereInput[]
  OR?: Prisma.NaturesWhereInput[]
  NOT?: Prisma.NaturesWhereInput | Prisma.NaturesWhereInput[]
  identifier?: Prisma.StringFilter<"Natures"> | string
  decreased_stat_id?: Prisma.IntFilter<"Natures"> | number
  increased_stat_id?: Prisma.IntFilter<"Natures"> | number
  hates_flavor_id?: Prisma.IntFilter<"Natures"> | number
  likes_flavor_id?: Prisma.IntFilter<"Natures"> | number
  game_index?: Prisma.IntFilter<"Natures"> | number
  decreasedStat?: Prisma.XOR<Prisma.StatsScalarRelationFilter, Prisma.StatsWhereInput>
  increasedStat?: Prisma.XOR<Prisma.StatsScalarRelationFilter, Prisma.StatsWhereInput>
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesListRelationFilter
}, "id">

export type NaturesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  decreased_stat_id?: Prisma.SortOrder
  increased_stat_id?: Prisma.SortOrder
  hates_flavor_id?: Prisma.SortOrder
  likes_flavor_id?: Prisma.SortOrder
  game_index?: Prisma.SortOrder
  _count?: Prisma.NaturesCountOrderByAggregateInput
  _avg?: Prisma.NaturesAvgOrderByAggregateInput
  _max?: Prisma.NaturesMaxOrderByAggregateInput
  _min?: Prisma.NaturesMinOrderByAggregateInput
  _sum?: Prisma.NaturesSumOrderByAggregateInput
}

export type NaturesScalarWhereWithAggregatesInput = {
  AND?: Prisma.NaturesScalarWhereWithAggregatesInput | Prisma.NaturesScalarWhereWithAggregatesInput[]
  OR?: Prisma.NaturesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NaturesScalarWhereWithAggregatesInput | Prisma.NaturesScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Natures"> | number
  identifier?: Prisma.StringWithAggregatesFilter<"Natures"> | string
  decreased_stat_id?: Prisma.IntWithAggregatesFilter<"Natures"> | number
  increased_stat_id?: Prisma.IntWithAggregatesFilter<"Natures"> | number
  hates_flavor_id?: Prisma.IntWithAggregatesFilter<"Natures"> | number
  likes_flavor_id?: Prisma.IntWithAggregatesFilter<"Natures"> | number
  game_index?: Prisma.IntWithAggregatesFilter<"Natures"> | number
}

export type NaturesCreateInput = {
  id: number
  identifier: string
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
  decreasedStat: Prisma.StatsCreateNestedOneWithoutNaturesDecreasedInput
  increasedStat: Prisma.StatsCreateNestedOneWithoutNaturesIncreasedInput
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesCreateNestedManyWithoutNatureInput
}

export type NaturesUncheckedCreateInput = {
  id: number
  identifier: string
  decreased_stat_id: number
  increased_stat_id: number
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesUncheckedCreateNestedManyWithoutNatureInput
}

export type NaturesUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
  decreasedStat?: Prisma.StatsUpdateOneRequiredWithoutNaturesDecreasedNestedInput
  increasedStat?: Prisma.StatsUpdateOneRequiredWithoutNaturesIncreasedNestedInput
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesUpdateManyWithoutNatureNestedInput
}

export type NaturesUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  decreased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  increased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesUncheckedUpdateManyWithoutNatureNestedInput
}

export type NaturesCreateManyInput = {
  id: number
  identifier: string
  decreased_stat_id: number
  increased_stat_id: number
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
}

export type NaturesUpdateManyMutationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NaturesUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  decreased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  increased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NaturesListRelationFilter = {
  every?: Prisma.NaturesWhereInput
  some?: Prisma.NaturesWhereInput
  none?: Prisma.NaturesWhereInput
}

export type NaturesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NaturesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  decreased_stat_id?: Prisma.SortOrder
  increased_stat_id?: Prisma.SortOrder
  hates_flavor_id?: Prisma.SortOrder
  likes_flavor_id?: Prisma.SortOrder
  game_index?: Prisma.SortOrder
}

export type NaturesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  decreased_stat_id?: Prisma.SortOrder
  increased_stat_id?: Prisma.SortOrder
  hates_flavor_id?: Prisma.SortOrder
  likes_flavor_id?: Prisma.SortOrder
  game_index?: Prisma.SortOrder
}

export type NaturesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  decreased_stat_id?: Prisma.SortOrder
  increased_stat_id?: Prisma.SortOrder
  hates_flavor_id?: Prisma.SortOrder
  likes_flavor_id?: Prisma.SortOrder
  game_index?: Prisma.SortOrder
}

export type NaturesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  decreased_stat_id?: Prisma.SortOrder
  increased_stat_id?: Prisma.SortOrder
  hates_flavor_id?: Prisma.SortOrder
  likes_flavor_id?: Prisma.SortOrder
  game_index?: Prisma.SortOrder
}

export type NaturesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  decreased_stat_id?: Prisma.SortOrder
  increased_stat_id?: Prisma.SortOrder
  hates_flavor_id?: Prisma.SortOrder
  likes_flavor_id?: Prisma.SortOrder
  game_index?: Prisma.SortOrder
}

export type NaturesScalarRelationFilter = {
  is?: Prisma.NaturesWhereInput
  isNot?: Prisma.NaturesWhereInput
}

export type NaturesCreateNestedManyWithoutDecreasedStatInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutDecreasedStatInput, Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput> | Prisma.NaturesCreateWithoutDecreasedStatInput[] | Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput[]
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutDecreasedStatInput | Prisma.NaturesCreateOrConnectWithoutDecreasedStatInput[]
  createMany?: Prisma.NaturesCreateManyDecreasedStatInputEnvelope
  connect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
}

export type NaturesCreateNestedManyWithoutIncreasedStatInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutIncreasedStatInput, Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput> | Prisma.NaturesCreateWithoutIncreasedStatInput[] | Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput[]
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutIncreasedStatInput | Prisma.NaturesCreateOrConnectWithoutIncreasedStatInput[]
  createMany?: Prisma.NaturesCreateManyIncreasedStatInputEnvelope
  connect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
}

export type NaturesUncheckedCreateNestedManyWithoutDecreasedStatInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutDecreasedStatInput, Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput> | Prisma.NaturesCreateWithoutDecreasedStatInput[] | Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput[]
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutDecreasedStatInput | Prisma.NaturesCreateOrConnectWithoutDecreasedStatInput[]
  createMany?: Prisma.NaturesCreateManyDecreasedStatInputEnvelope
  connect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
}

export type NaturesUncheckedCreateNestedManyWithoutIncreasedStatInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutIncreasedStatInput, Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput> | Prisma.NaturesCreateWithoutIncreasedStatInput[] | Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput[]
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutIncreasedStatInput | Prisma.NaturesCreateOrConnectWithoutIncreasedStatInput[]
  createMany?: Prisma.NaturesCreateManyIncreasedStatInputEnvelope
  connect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
}

export type NaturesUpdateManyWithoutDecreasedStatNestedInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutDecreasedStatInput, Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput> | Prisma.NaturesCreateWithoutDecreasedStatInput[] | Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput[]
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutDecreasedStatInput | Prisma.NaturesCreateOrConnectWithoutDecreasedStatInput[]
  upsert?: Prisma.NaturesUpsertWithWhereUniqueWithoutDecreasedStatInput | Prisma.NaturesUpsertWithWhereUniqueWithoutDecreasedStatInput[]
  createMany?: Prisma.NaturesCreateManyDecreasedStatInputEnvelope
  set?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  disconnect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  delete?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  connect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  update?: Prisma.NaturesUpdateWithWhereUniqueWithoutDecreasedStatInput | Prisma.NaturesUpdateWithWhereUniqueWithoutDecreasedStatInput[]
  updateMany?: Prisma.NaturesUpdateManyWithWhereWithoutDecreasedStatInput | Prisma.NaturesUpdateManyWithWhereWithoutDecreasedStatInput[]
  deleteMany?: Prisma.NaturesScalarWhereInput | Prisma.NaturesScalarWhereInput[]
}

export type NaturesUpdateManyWithoutIncreasedStatNestedInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutIncreasedStatInput, Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput> | Prisma.NaturesCreateWithoutIncreasedStatInput[] | Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput[]
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutIncreasedStatInput | Prisma.NaturesCreateOrConnectWithoutIncreasedStatInput[]
  upsert?: Prisma.NaturesUpsertWithWhereUniqueWithoutIncreasedStatInput | Prisma.NaturesUpsertWithWhereUniqueWithoutIncreasedStatInput[]
  createMany?: Prisma.NaturesCreateManyIncreasedStatInputEnvelope
  set?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  disconnect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  delete?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  connect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  update?: Prisma.NaturesUpdateWithWhereUniqueWithoutIncreasedStatInput | Prisma.NaturesUpdateWithWhereUniqueWithoutIncreasedStatInput[]
  updateMany?: Prisma.NaturesUpdateManyWithWhereWithoutIncreasedStatInput | Prisma.NaturesUpdateManyWithWhereWithoutIncreasedStatInput[]
  deleteMany?: Prisma.NaturesScalarWhereInput | Prisma.NaturesScalarWhereInput[]
}

export type NaturesUncheckedUpdateManyWithoutDecreasedStatNestedInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutDecreasedStatInput, Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput> | Prisma.NaturesCreateWithoutDecreasedStatInput[] | Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput[]
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutDecreasedStatInput | Prisma.NaturesCreateOrConnectWithoutDecreasedStatInput[]
  upsert?: Prisma.NaturesUpsertWithWhereUniqueWithoutDecreasedStatInput | Prisma.NaturesUpsertWithWhereUniqueWithoutDecreasedStatInput[]
  createMany?: Prisma.NaturesCreateManyDecreasedStatInputEnvelope
  set?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  disconnect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  delete?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  connect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  update?: Prisma.NaturesUpdateWithWhereUniqueWithoutDecreasedStatInput | Prisma.NaturesUpdateWithWhereUniqueWithoutDecreasedStatInput[]
  updateMany?: Prisma.NaturesUpdateManyWithWhereWithoutDecreasedStatInput | Prisma.NaturesUpdateManyWithWhereWithoutDecreasedStatInput[]
  deleteMany?: Prisma.NaturesScalarWhereInput | Prisma.NaturesScalarWhereInput[]
}

export type NaturesUncheckedUpdateManyWithoutIncreasedStatNestedInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutIncreasedStatInput, Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput> | Prisma.NaturesCreateWithoutIncreasedStatInput[] | Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput[]
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutIncreasedStatInput | Prisma.NaturesCreateOrConnectWithoutIncreasedStatInput[]
  upsert?: Prisma.NaturesUpsertWithWhereUniqueWithoutIncreasedStatInput | Prisma.NaturesUpsertWithWhereUniqueWithoutIncreasedStatInput[]
  createMany?: Prisma.NaturesCreateManyIncreasedStatInputEnvelope
  set?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  disconnect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  delete?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  connect?: Prisma.NaturesWhereUniqueInput | Prisma.NaturesWhereUniqueInput[]
  update?: Prisma.NaturesUpdateWithWhereUniqueWithoutIncreasedStatInput | Prisma.NaturesUpdateWithWhereUniqueWithoutIncreasedStatInput[]
  updateMany?: Prisma.NaturesUpdateManyWithWhereWithoutIncreasedStatInput | Prisma.NaturesUpdateManyWithWhereWithoutIncreasedStatInput[]
  deleteMany?: Prisma.NaturesScalarWhereInput | Prisma.NaturesScalarWhereInput[]
}

export type NaturesCreateNestedOneWithoutBattleStylePreferencesInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutBattleStylePreferencesInput, Prisma.NaturesUncheckedCreateWithoutBattleStylePreferencesInput>
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutBattleStylePreferencesInput
  connect?: Prisma.NaturesWhereUniqueInput
}

export type NaturesUpdateOneRequiredWithoutBattleStylePreferencesNestedInput = {
  create?: Prisma.XOR<Prisma.NaturesCreateWithoutBattleStylePreferencesInput, Prisma.NaturesUncheckedCreateWithoutBattleStylePreferencesInput>
  connectOrCreate?: Prisma.NaturesCreateOrConnectWithoutBattleStylePreferencesInput
  upsert?: Prisma.NaturesUpsertWithoutBattleStylePreferencesInput
  connect?: Prisma.NaturesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NaturesUpdateToOneWithWhereWithoutBattleStylePreferencesInput, Prisma.NaturesUpdateWithoutBattleStylePreferencesInput>, Prisma.NaturesUncheckedUpdateWithoutBattleStylePreferencesInput>
}

export type NaturesCreateWithoutDecreasedStatInput = {
  id: number
  identifier: string
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
  increasedStat: Prisma.StatsCreateNestedOneWithoutNaturesIncreasedInput
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesCreateNestedManyWithoutNatureInput
}

export type NaturesUncheckedCreateWithoutDecreasedStatInput = {
  id: number
  identifier: string
  increased_stat_id: number
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesUncheckedCreateNestedManyWithoutNatureInput
}

export type NaturesCreateOrConnectWithoutDecreasedStatInput = {
  where: Prisma.NaturesWhereUniqueInput
  create: Prisma.XOR<Prisma.NaturesCreateWithoutDecreasedStatInput, Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput>
}

export type NaturesCreateManyDecreasedStatInputEnvelope = {
  data: Prisma.NaturesCreateManyDecreasedStatInput | Prisma.NaturesCreateManyDecreasedStatInput[]
  skipDuplicates?: boolean
}

export type NaturesCreateWithoutIncreasedStatInput = {
  id: number
  identifier: string
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
  decreasedStat: Prisma.StatsCreateNestedOneWithoutNaturesDecreasedInput
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesCreateNestedManyWithoutNatureInput
}

export type NaturesUncheckedCreateWithoutIncreasedStatInput = {
  id: number
  identifier: string
  decreased_stat_id: number
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesUncheckedCreateNestedManyWithoutNatureInput
}

export type NaturesCreateOrConnectWithoutIncreasedStatInput = {
  where: Prisma.NaturesWhereUniqueInput
  create: Prisma.XOR<Prisma.NaturesCreateWithoutIncreasedStatInput, Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput>
}

export type NaturesCreateManyIncreasedStatInputEnvelope = {
  data: Prisma.NaturesCreateManyIncreasedStatInput | Prisma.NaturesCreateManyIncreasedStatInput[]
  skipDuplicates?: boolean
}

export type NaturesUpsertWithWhereUniqueWithoutDecreasedStatInput = {
  where: Prisma.NaturesWhereUniqueInput
  update: Prisma.XOR<Prisma.NaturesUpdateWithoutDecreasedStatInput, Prisma.NaturesUncheckedUpdateWithoutDecreasedStatInput>
  create: Prisma.XOR<Prisma.NaturesCreateWithoutDecreasedStatInput, Prisma.NaturesUncheckedCreateWithoutDecreasedStatInput>
}

export type NaturesUpdateWithWhereUniqueWithoutDecreasedStatInput = {
  where: Prisma.NaturesWhereUniqueInput
  data: Prisma.XOR<Prisma.NaturesUpdateWithoutDecreasedStatInput, Prisma.NaturesUncheckedUpdateWithoutDecreasedStatInput>
}

export type NaturesUpdateManyWithWhereWithoutDecreasedStatInput = {
  where: Prisma.NaturesScalarWhereInput
  data: Prisma.XOR<Prisma.NaturesUpdateManyMutationInput, Prisma.NaturesUncheckedUpdateManyWithoutDecreasedStatInput>
}

export type NaturesScalarWhereInput = {
  AND?: Prisma.NaturesScalarWhereInput | Prisma.NaturesScalarWhereInput[]
  OR?: Prisma.NaturesScalarWhereInput[]
  NOT?: Prisma.NaturesScalarWhereInput | Prisma.NaturesScalarWhereInput[]
  id?: Prisma.IntFilter<"Natures"> | number
  identifier?: Prisma.StringFilter<"Natures"> | string
  decreased_stat_id?: Prisma.IntFilter<"Natures"> | number
  increased_stat_id?: Prisma.IntFilter<"Natures"> | number
  hates_flavor_id?: Prisma.IntFilter<"Natures"> | number
  likes_flavor_id?: Prisma.IntFilter<"Natures"> | number
  game_index?: Prisma.IntFilter<"Natures"> | number
}

export type NaturesUpsertWithWhereUniqueWithoutIncreasedStatInput = {
  where: Prisma.NaturesWhereUniqueInput
  update: Prisma.XOR<Prisma.NaturesUpdateWithoutIncreasedStatInput, Prisma.NaturesUncheckedUpdateWithoutIncreasedStatInput>
  create: Prisma.XOR<Prisma.NaturesCreateWithoutIncreasedStatInput, Prisma.NaturesUncheckedCreateWithoutIncreasedStatInput>
}

export type NaturesUpdateWithWhereUniqueWithoutIncreasedStatInput = {
  where: Prisma.NaturesWhereUniqueInput
  data: Prisma.XOR<Prisma.NaturesUpdateWithoutIncreasedStatInput, Prisma.NaturesUncheckedUpdateWithoutIncreasedStatInput>
}

export type NaturesUpdateManyWithWhereWithoutIncreasedStatInput = {
  where: Prisma.NaturesScalarWhereInput
  data: Prisma.XOR<Prisma.NaturesUpdateManyMutationInput, Prisma.NaturesUncheckedUpdateManyWithoutIncreasedStatInput>
}

export type NaturesCreateWithoutBattleStylePreferencesInput = {
  id: number
  identifier: string
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
  decreasedStat: Prisma.StatsCreateNestedOneWithoutNaturesDecreasedInput
  increasedStat: Prisma.StatsCreateNestedOneWithoutNaturesIncreasedInput
}

export type NaturesUncheckedCreateWithoutBattleStylePreferencesInput = {
  id: number
  identifier: string
  decreased_stat_id: number
  increased_stat_id: number
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
}

export type NaturesCreateOrConnectWithoutBattleStylePreferencesInput = {
  where: Prisma.NaturesWhereUniqueInput
  create: Prisma.XOR<Prisma.NaturesCreateWithoutBattleStylePreferencesInput, Prisma.NaturesUncheckedCreateWithoutBattleStylePreferencesInput>
}

export type NaturesUpsertWithoutBattleStylePreferencesInput = {
  update: Prisma.XOR<Prisma.NaturesUpdateWithoutBattleStylePreferencesInput, Prisma.NaturesUncheckedUpdateWithoutBattleStylePreferencesInput>
  create: Prisma.XOR<Prisma.NaturesCreateWithoutBattleStylePreferencesInput, Prisma.NaturesUncheckedCreateWithoutBattleStylePreferencesInput>
  where?: Prisma.NaturesWhereInput
}

export type NaturesUpdateToOneWithWhereWithoutBattleStylePreferencesInput = {
  where?: Prisma.NaturesWhereInput
  data: Prisma.XOR<Prisma.NaturesUpdateWithoutBattleStylePreferencesInput, Prisma.NaturesUncheckedUpdateWithoutBattleStylePreferencesInput>
}

export type NaturesUpdateWithoutBattleStylePreferencesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
  decreasedStat?: Prisma.StatsUpdateOneRequiredWithoutNaturesDecreasedNestedInput
  increasedStat?: Prisma.StatsUpdateOneRequiredWithoutNaturesIncreasedNestedInput
}

export type NaturesUncheckedUpdateWithoutBattleStylePreferencesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  decreased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  increased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NaturesCreateManyDecreasedStatInput = {
  id: number
  identifier: string
  increased_stat_id: number
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
}

export type NaturesCreateManyIncreasedStatInput = {
  id: number
  identifier: string
  decreased_stat_id: number
  hates_flavor_id: number
  likes_flavor_id: number
  game_index: number
}

export type NaturesUpdateWithoutDecreasedStatInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
  increasedStat?: Prisma.StatsUpdateOneRequiredWithoutNaturesIncreasedNestedInput
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesUpdateManyWithoutNatureNestedInput
}

export type NaturesUncheckedUpdateWithoutDecreasedStatInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  increased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesUncheckedUpdateManyWithoutNatureNestedInput
}

export type NaturesUncheckedUpdateManyWithoutDecreasedStatInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  increased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type NaturesUpdateWithoutIncreasedStatInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
  decreasedStat?: Prisma.StatsUpdateOneRequiredWithoutNaturesDecreasedNestedInput
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesUpdateManyWithoutNatureNestedInput
}

export type NaturesUncheckedUpdateWithoutIncreasedStatInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  decreased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
  battleStylePreferences?: Prisma.NatureBattleStylePreferencesUncheckedUpdateManyWithoutNatureNestedInput
}

export type NaturesUncheckedUpdateManyWithoutIncreasedStatInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  decreased_stat_id?: Prisma.IntFieldUpdateOperationsInput | number
  hates_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  likes_flavor_id?: Prisma.IntFieldUpdateOperationsInput | number
  game_index?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type NaturesCountOutputType
 */

export type NaturesCountOutputType = {
  battleStylePreferences: number
}

export type NaturesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  battleStylePreferences?: boolean | NaturesCountOutputTypeCountBattleStylePreferencesArgs
}

/**
 * NaturesCountOutputType without action
 */
export type NaturesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NaturesCountOutputType
   */
  select?: Prisma.NaturesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * NaturesCountOutputType without action
 */
export type NaturesCountOutputTypeCountBattleStylePreferencesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NatureBattleStylePreferencesWhereInput
}


export type NaturesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  decreased_stat_id?: boolean
  increased_stat_id?: boolean
  hates_flavor_id?: boolean
  likes_flavor_id?: boolean
  game_index?: boolean
  decreasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
  increasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
  battleStylePreferences?: boolean | Prisma.Natures$battleStylePreferencesArgs<ExtArgs>
  _count?: boolean | Prisma.NaturesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["natures"]>

export type NaturesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  decreased_stat_id?: boolean
  increased_stat_id?: boolean
  hates_flavor_id?: boolean
  likes_flavor_id?: boolean
  game_index?: boolean
  decreasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
  increasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["natures"]>

export type NaturesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  decreased_stat_id?: boolean
  increased_stat_id?: boolean
  hates_flavor_id?: boolean
  likes_flavor_id?: boolean
  game_index?: boolean
  decreasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
  increasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["natures"]>

export type NaturesSelectScalar = {
  id?: boolean
  identifier?: boolean
  decreased_stat_id?: boolean
  increased_stat_id?: boolean
  hates_flavor_id?: boolean
  likes_flavor_id?: boolean
  game_index?: boolean
}

export type NaturesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "identifier" | "decreased_stat_id" | "increased_stat_id" | "hates_flavor_id" | "likes_flavor_id" | "game_index", ExtArgs["result"]["natures"]>
export type NaturesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  decreasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
  increasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
  battleStylePreferences?: boolean | Prisma.Natures$battleStylePreferencesArgs<ExtArgs>
  _count?: boolean | Prisma.NaturesCountOutputTypeDefaultArgs<ExtArgs>
}
export type NaturesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  decreasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
  increasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
}
export type NaturesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  decreasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
  increasedStat?: boolean | Prisma.StatsDefaultArgs<ExtArgs>
}

export type $NaturesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Natures"
  objects: {
    decreasedStat: Prisma.$StatsPayload<ExtArgs>
    increasedStat: Prisma.$StatsPayload<ExtArgs>
    battleStylePreferences: Prisma.$NatureBattleStylePreferencesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    identifier: string
    decreased_stat_id: number
    increased_stat_id: number
    hates_flavor_id: number
    likes_flavor_id: number
    game_index: number
  }, ExtArgs["result"]["natures"]>
  composites: {}
}

export type NaturesGetPayload<S extends boolean | null | undefined | NaturesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NaturesPayload, S>

export type NaturesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NaturesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NaturesCountAggregateInputType | true
  }

export interface NaturesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Natures'], meta: { name: 'Natures' } }
  /**
   * Find zero or one Natures that matches the filter.
   * @param {NaturesFindUniqueArgs} args - Arguments to find a Natures
   * @example
   * // Get one Natures
   * const natures = await prisma.natures.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NaturesFindUniqueArgs>(args: Prisma.SelectSubset<T, NaturesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NaturesClient<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Natures that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NaturesFindUniqueOrThrowArgs} args - Arguments to find a Natures
   * @example
   * // Get one Natures
   * const natures = await prisma.natures.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NaturesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NaturesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NaturesClient<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Natures that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NaturesFindFirstArgs} args - Arguments to find a Natures
   * @example
   * // Get one Natures
   * const natures = await prisma.natures.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NaturesFindFirstArgs>(args?: Prisma.SelectSubset<T, NaturesFindFirstArgs<ExtArgs>>): Prisma.Prisma__NaturesClient<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Natures that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NaturesFindFirstOrThrowArgs} args - Arguments to find a Natures
   * @example
   * // Get one Natures
   * const natures = await prisma.natures.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NaturesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NaturesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NaturesClient<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Natures that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NaturesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Natures
   * const natures = await prisma.natures.findMany()
   * 
   * // Get first 10 Natures
   * const natures = await prisma.natures.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const naturesWithIdOnly = await prisma.natures.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NaturesFindManyArgs>(args?: Prisma.SelectSubset<T, NaturesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Natures.
   * @param {NaturesCreateArgs} args - Arguments to create a Natures.
   * @example
   * // Create one Natures
   * const Natures = await prisma.natures.create({
   *   data: {
   *     // ... data to create a Natures
   *   }
   * })
   * 
   */
  create<T extends NaturesCreateArgs>(args: Prisma.SelectSubset<T, NaturesCreateArgs<ExtArgs>>): Prisma.Prisma__NaturesClient<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Natures.
   * @param {NaturesCreateManyArgs} args - Arguments to create many Natures.
   * @example
   * // Create many Natures
   * const natures = await prisma.natures.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NaturesCreateManyArgs>(args?: Prisma.SelectSubset<T, NaturesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Natures and returns the data saved in the database.
   * @param {NaturesCreateManyAndReturnArgs} args - Arguments to create many Natures.
   * @example
   * // Create many Natures
   * const natures = await prisma.natures.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Natures and only return the `id`
   * const naturesWithIdOnly = await prisma.natures.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NaturesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NaturesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Natures.
   * @param {NaturesDeleteArgs} args - Arguments to delete one Natures.
   * @example
   * // Delete one Natures
   * const Natures = await prisma.natures.delete({
   *   where: {
   *     // ... filter to delete one Natures
   *   }
   * })
   * 
   */
  delete<T extends NaturesDeleteArgs>(args: Prisma.SelectSubset<T, NaturesDeleteArgs<ExtArgs>>): Prisma.Prisma__NaturesClient<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Natures.
   * @param {NaturesUpdateArgs} args - Arguments to update one Natures.
   * @example
   * // Update one Natures
   * const natures = await prisma.natures.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NaturesUpdateArgs>(args: Prisma.SelectSubset<T, NaturesUpdateArgs<ExtArgs>>): Prisma.Prisma__NaturesClient<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Natures.
   * @param {NaturesDeleteManyArgs} args - Arguments to filter Natures to delete.
   * @example
   * // Delete a few Natures
   * const { count } = await prisma.natures.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NaturesDeleteManyArgs>(args?: Prisma.SelectSubset<T, NaturesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Natures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NaturesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Natures
   * const natures = await prisma.natures.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NaturesUpdateManyArgs>(args: Prisma.SelectSubset<T, NaturesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Natures and returns the data updated in the database.
   * @param {NaturesUpdateManyAndReturnArgs} args - Arguments to update many Natures.
   * @example
   * // Update many Natures
   * const natures = await prisma.natures.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Natures and only return the `id`
   * const naturesWithIdOnly = await prisma.natures.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NaturesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NaturesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Natures.
   * @param {NaturesUpsertArgs} args - Arguments to update or create a Natures.
   * @example
   * // Update or create a Natures
   * const natures = await prisma.natures.upsert({
   *   create: {
   *     // ... data to create a Natures
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Natures we want to update
   *   }
   * })
   */
  upsert<T extends NaturesUpsertArgs>(args: Prisma.SelectSubset<T, NaturesUpsertArgs<ExtArgs>>): Prisma.Prisma__NaturesClient<runtime.Types.Result.GetResult<Prisma.$NaturesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Natures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NaturesCountArgs} args - Arguments to filter Natures to count.
   * @example
   * // Count the number of Natures
   * const count = await prisma.natures.count({
   *   where: {
   *     // ... the filter for the Natures we want to count
   *   }
   * })
  **/
  count<T extends NaturesCountArgs>(
    args?: Prisma.Subset<T, NaturesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NaturesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Natures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NaturesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NaturesAggregateArgs>(args: Prisma.Subset<T, NaturesAggregateArgs>): Prisma.PrismaPromise<GetNaturesAggregateType<T>>

  /**
   * Group by Natures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NaturesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NaturesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NaturesGroupByArgs['orderBy'] }
      : { orderBy?: NaturesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NaturesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNaturesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Natures model
 */
readonly fields: NaturesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Natures.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NaturesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  decreasedStat<T extends Prisma.StatsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StatsDefaultArgs<ExtArgs>>): Prisma.Prisma__StatsClient<runtime.Types.Result.GetResult<Prisma.$StatsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  increasedStat<T extends Prisma.StatsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StatsDefaultArgs<ExtArgs>>): Prisma.Prisma__StatsClient<runtime.Types.Result.GetResult<Prisma.$StatsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  battleStylePreferences<T extends Prisma.Natures$battleStylePreferencesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Natures$battleStylePreferencesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NatureBattleStylePreferencesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Natures model
 */
export interface NaturesFieldRefs {
  readonly id: Prisma.FieldRef<"Natures", 'Int'>
  readonly identifier: Prisma.FieldRef<"Natures", 'String'>
  readonly decreased_stat_id: Prisma.FieldRef<"Natures", 'Int'>
  readonly increased_stat_id: Prisma.FieldRef<"Natures", 'Int'>
  readonly hates_flavor_id: Prisma.FieldRef<"Natures", 'Int'>
  readonly likes_flavor_id: Prisma.FieldRef<"Natures", 'Int'>
  readonly game_index: Prisma.FieldRef<"Natures", 'Int'>
}
    

// Custom InputTypes
/**
 * Natures findUnique
 */
export type NaturesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
  /**
   * Filter, which Natures to fetch.
   */
  where: Prisma.NaturesWhereUniqueInput
}

/**
 * Natures findUniqueOrThrow
 */
export type NaturesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
  /**
   * Filter, which Natures to fetch.
   */
  where: Prisma.NaturesWhereUniqueInput
}

/**
 * Natures findFirst
 */
export type NaturesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
  /**
   * Filter, which Natures to fetch.
   */
  where?: Prisma.NaturesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Natures to fetch.
   */
  orderBy?: Prisma.NaturesOrderByWithRelationInput | Prisma.NaturesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Natures.
   */
  cursor?: Prisma.NaturesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Natures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Natures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Natures.
   */
  distinct?: Prisma.NaturesScalarFieldEnum | Prisma.NaturesScalarFieldEnum[]
}

/**
 * Natures findFirstOrThrow
 */
export type NaturesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
  /**
   * Filter, which Natures to fetch.
   */
  where?: Prisma.NaturesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Natures to fetch.
   */
  orderBy?: Prisma.NaturesOrderByWithRelationInput | Prisma.NaturesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Natures.
   */
  cursor?: Prisma.NaturesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Natures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Natures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Natures.
   */
  distinct?: Prisma.NaturesScalarFieldEnum | Prisma.NaturesScalarFieldEnum[]
}

/**
 * Natures findMany
 */
export type NaturesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
  /**
   * Filter, which Natures to fetch.
   */
  where?: Prisma.NaturesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Natures to fetch.
   */
  orderBy?: Prisma.NaturesOrderByWithRelationInput | Prisma.NaturesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Natures.
   */
  cursor?: Prisma.NaturesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Natures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Natures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Natures.
   */
  distinct?: Prisma.NaturesScalarFieldEnum | Prisma.NaturesScalarFieldEnum[]
}

/**
 * Natures create
 */
export type NaturesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
  /**
   * The data needed to create a Natures.
   */
  data: Prisma.XOR<Prisma.NaturesCreateInput, Prisma.NaturesUncheckedCreateInput>
}

/**
 * Natures createMany
 */
export type NaturesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Natures.
   */
  data: Prisma.NaturesCreateManyInput | Prisma.NaturesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Natures createManyAndReturn
 */
export type NaturesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * The data used to create many Natures.
   */
  data: Prisma.NaturesCreateManyInput | Prisma.NaturesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Natures update
 */
export type NaturesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
  /**
   * The data needed to update a Natures.
   */
  data: Prisma.XOR<Prisma.NaturesUpdateInput, Prisma.NaturesUncheckedUpdateInput>
  /**
   * Choose, which Natures to update.
   */
  where: Prisma.NaturesWhereUniqueInput
}

/**
 * Natures updateMany
 */
export type NaturesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Natures.
   */
  data: Prisma.XOR<Prisma.NaturesUpdateManyMutationInput, Prisma.NaturesUncheckedUpdateManyInput>
  /**
   * Filter which Natures to update
   */
  where?: Prisma.NaturesWhereInput
  /**
   * Limit how many Natures to update.
   */
  limit?: number
}

/**
 * Natures updateManyAndReturn
 */
export type NaturesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * The data used to update Natures.
   */
  data: Prisma.XOR<Prisma.NaturesUpdateManyMutationInput, Prisma.NaturesUncheckedUpdateManyInput>
  /**
   * Filter which Natures to update
   */
  where?: Prisma.NaturesWhereInput
  /**
   * Limit how many Natures to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Natures upsert
 */
export type NaturesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
  /**
   * The filter to search for the Natures to update in case it exists.
   */
  where: Prisma.NaturesWhereUniqueInput
  /**
   * In case the Natures found by the `where` argument doesn't exist, create a new Natures with this data.
   */
  create: Prisma.XOR<Prisma.NaturesCreateInput, Prisma.NaturesUncheckedCreateInput>
  /**
   * In case the Natures was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NaturesUpdateInput, Prisma.NaturesUncheckedUpdateInput>
}

/**
 * Natures delete
 */
export type NaturesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
  /**
   * Filter which Natures to delete.
   */
  where: Prisma.NaturesWhereUniqueInput
}

/**
 * Natures deleteMany
 */
export type NaturesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Natures to delete
   */
  where?: Prisma.NaturesWhereInput
  /**
   * Limit how many Natures to delete.
   */
  limit?: number
}

/**
 * Natures.battleStylePreferences
 */
export type Natures$battleStylePreferencesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NatureBattleStylePreferences
   */
  select?: Prisma.NatureBattleStylePreferencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NatureBattleStylePreferences
   */
  omit?: Prisma.NatureBattleStylePreferencesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NatureBattleStylePreferencesInclude<ExtArgs> | null
  where?: Prisma.NatureBattleStylePreferencesWhereInput
  orderBy?: Prisma.NatureBattleStylePreferencesOrderByWithRelationInput | Prisma.NatureBattleStylePreferencesOrderByWithRelationInput[]
  cursor?: Prisma.NatureBattleStylePreferencesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NatureBattleStylePreferencesScalarFieldEnum | Prisma.NatureBattleStylePreferencesScalarFieldEnum[]
}

/**
 * Natures without action
 */
export type NaturesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Natures
   */
  select?: Prisma.NaturesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Natures
   */
  omit?: Prisma.NaturesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NaturesInclude<ExtArgs> | null
}
