
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PokemonDexNumbers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PokemonDexNumbers
 * @@TypeGraphQL.type(name: "PokemonDexNumber")
 */
export type PokemonDexNumbersModel = runtime.Types.Result.DefaultSelection<Prisma.$PokemonDexNumbersPayload>

export type AggregatePokemonDexNumbers = {
  _count: PokemonDexNumbersCountAggregateOutputType | null
  _avg: PokemonDexNumbersAvgAggregateOutputType | null
  _sum: PokemonDexNumbersSumAggregateOutputType | null
  _min: PokemonDexNumbersMinAggregateOutputType | null
  _max: PokemonDexNumbersMaxAggregateOutputType | null
}

export type PokemonDexNumbersAvgAggregateOutputType = {
  species_id: number | null
  pokedex_id: number | null
  pokedex_number: number | null
}

export type PokemonDexNumbersSumAggregateOutputType = {
  species_id: number | null
  pokedex_id: number | null
  pokedex_number: number | null
}

export type PokemonDexNumbersMinAggregateOutputType = {
  species_id: number | null
  pokedex_id: number | null
  pokedex_number: number | null
}

export type PokemonDexNumbersMaxAggregateOutputType = {
  species_id: number | null
  pokedex_id: number | null
  pokedex_number: number | null
}

export type PokemonDexNumbersCountAggregateOutputType = {
  species_id: number
  pokedex_id: number
  pokedex_number: number
  _all: number
}


export type PokemonDexNumbersAvgAggregateInputType = {
  species_id?: true
  pokedex_id?: true
  pokedex_number?: true
}

export type PokemonDexNumbersSumAggregateInputType = {
  species_id?: true
  pokedex_id?: true
  pokedex_number?: true
}

export type PokemonDexNumbersMinAggregateInputType = {
  species_id?: true
  pokedex_id?: true
  pokedex_number?: true
}

export type PokemonDexNumbersMaxAggregateInputType = {
  species_id?: true
  pokedex_id?: true
  pokedex_number?: true
}

export type PokemonDexNumbersCountAggregateInputType = {
  species_id?: true
  pokedex_id?: true
  pokedex_number?: true
  _all?: true
}

export type PokemonDexNumbersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PokemonDexNumbers to aggregate.
   */
  where?: Prisma.PokemonDexNumbersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonDexNumbers to fetch.
   */
  orderBy?: Prisma.PokemonDexNumbersOrderByWithRelationInput | Prisma.PokemonDexNumbersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PokemonDexNumbersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonDexNumbers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonDexNumbers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PokemonDexNumbers
  **/
  _count?: true | PokemonDexNumbersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PokemonDexNumbersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PokemonDexNumbersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PokemonDexNumbersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PokemonDexNumbersMaxAggregateInputType
}

export type GetPokemonDexNumbersAggregateType<T extends PokemonDexNumbersAggregateArgs> = {
      [P in keyof T & keyof AggregatePokemonDexNumbers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePokemonDexNumbers[P]>
    : Prisma.GetScalarType<T[P], AggregatePokemonDexNumbers[P]>
}




export type PokemonDexNumbersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PokemonDexNumbersWhereInput
  orderBy?: Prisma.PokemonDexNumbersOrderByWithAggregationInput | Prisma.PokemonDexNumbersOrderByWithAggregationInput[]
  by: Prisma.PokemonDexNumbersScalarFieldEnum[] | Prisma.PokemonDexNumbersScalarFieldEnum
  having?: Prisma.PokemonDexNumbersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PokemonDexNumbersCountAggregateInputType | true
  _avg?: PokemonDexNumbersAvgAggregateInputType
  _sum?: PokemonDexNumbersSumAggregateInputType
  _min?: PokemonDexNumbersMinAggregateInputType
  _max?: PokemonDexNumbersMaxAggregateInputType
}

export type PokemonDexNumbersGroupByOutputType = {
  species_id: number
  pokedex_id: number
  pokedex_number: number
  _count: PokemonDexNumbersCountAggregateOutputType | null
  _avg: PokemonDexNumbersAvgAggregateOutputType | null
  _sum: PokemonDexNumbersSumAggregateOutputType | null
  _min: PokemonDexNumbersMinAggregateOutputType | null
  _max: PokemonDexNumbersMaxAggregateOutputType | null
}

export type GetPokemonDexNumbersGroupByPayload<T extends PokemonDexNumbersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PokemonDexNumbersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PokemonDexNumbersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PokemonDexNumbersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PokemonDexNumbersGroupByOutputType[P]>
      }
    >
  >



export type PokemonDexNumbersWhereInput = {
  AND?: Prisma.PokemonDexNumbersWhereInput | Prisma.PokemonDexNumbersWhereInput[]
  OR?: Prisma.PokemonDexNumbersWhereInput[]
  NOT?: Prisma.PokemonDexNumbersWhereInput | Prisma.PokemonDexNumbersWhereInput[]
  species_id?: Prisma.IntFilter<"PokemonDexNumbers"> | number
  pokedex_id?: Prisma.IntFilter<"PokemonDexNumbers"> | number
  pokedex_number?: Prisma.IntFilter<"PokemonDexNumbers"> | number
  species?: Prisma.XOR<Prisma.PokemonSpeciesScalarRelationFilter, Prisma.PokemonSpeciesWhereInput>
  pokedex?: Prisma.XOR<Prisma.PokedexesScalarRelationFilter, Prisma.PokedexesWhereInput>
}

export type PokemonDexNumbersOrderByWithRelationInput = {
  species_id?: Prisma.SortOrder
  pokedex_id?: Prisma.SortOrder
  pokedex_number?: Prisma.SortOrder
  species?: Prisma.PokemonSpeciesOrderByWithRelationInput
  pokedex?: Prisma.PokedexesOrderByWithRelationInput
}

export type PokemonDexNumbersWhereUniqueInput = Prisma.AtLeast<{
  species_id_pokedex_id?: Prisma.PokemonDexNumbersSpecies_idPokedex_idCompoundUniqueInput
  AND?: Prisma.PokemonDexNumbersWhereInput | Prisma.PokemonDexNumbersWhereInput[]
  OR?: Prisma.PokemonDexNumbersWhereInput[]
  NOT?: Prisma.PokemonDexNumbersWhereInput | Prisma.PokemonDexNumbersWhereInput[]
  species_id?: Prisma.IntFilter<"PokemonDexNumbers"> | number
  pokedex_id?: Prisma.IntFilter<"PokemonDexNumbers"> | number
  pokedex_number?: Prisma.IntFilter<"PokemonDexNumbers"> | number
  species?: Prisma.XOR<Prisma.PokemonSpeciesScalarRelationFilter, Prisma.PokemonSpeciesWhereInput>
  pokedex?: Prisma.XOR<Prisma.PokedexesScalarRelationFilter, Prisma.PokedexesWhereInput>
}, "species_id_pokedex_id">

export type PokemonDexNumbersOrderByWithAggregationInput = {
  species_id?: Prisma.SortOrder
  pokedex_id?: Prisma.SortOrder
  pokedex_number?: Prisma.SortOrder
  _count?: Prisma.PokemonDexNumbersCountOrderByAggregateInput
  _avg?: Prisma.PokemonDexNumbersAvgOrderByAggregateInput
  _max?: Prisma.PokemonDexNumbersMaxOrderByAggregateInput
  _min?: Prisma.PokemonDexNumbersMinOrderByAggregateInput
  _sum?: Prisma.PokemonDexNumbersSumOrderByAggregateInput
}

export type PokemonDexNumbersScalarWhereWithAggregatesInput = {
  AND?: Prisma.PokemonDexNumbersScalarWhereWithAggregatesInput | Prisma.PokemonDexNumbersScalarWhereWithAggregatesInput[]
  OR?: Prisma.PokemonDexNumbersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PokemonDexNumbersScalarWhereWithAggregatesInput | Prisma.PokemonDexNumbersScalarWhereWithAggregatesInput[]
  species_id?: Prisma.IntWithAggregatesFilter<"PokemonDexNumbers"> | number
  pokedex_id?: Prisma.IntWithAggregatesFilter<"PokemonDexNumbers"> | number
  pokedex_number?: Prisma.IntWithAggregatesFilter<"PokemonDexNumbers"> | number
}

export type PokemonDexNumbersCreateInput = {
  pokedex_number: number
  species: Prisma.PokemonSpeciesCreateNestedOneWithoutDexNumbersInput
  pokedex: Prisma.PokedexesCreateNestedOneWithoutDexNumbersInput
}

export type PokemonDexNumbersUncheckedCreateInput = {
  species_id: number
  pokedex_id: number
  pokedex_number: number
}

export type PokemonDexNumbersUpdateInput = {
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
  species?: Prisma.PokemonSpeciesUpdateOneRequiredWithoutDexNumbersNestedInput
  pokedex?: Prisma.PokedexesUpdateOneRequiredWithoutDexNumbersNestedInput
}

export type PokemonDexNumbersUncheckedUpdateInput = {
  species_id?: Prisma.IntFieldUpdateOperationsInput | number
  pokedex_id?: Prisma.IntFieldUpdateOperationsInput | number
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonDexNumbersCreateManyInput = {
  species_id: number
  pokedex_id: number
  pokedex_number: number
}

export type PokemonDexNumbersUpdateManyMutationInput = {
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonDexNumbersUncheckedUpdateManyInput = {
  species_id?: Prisma.IntFieldUpdateOperationsInput | number
  pokedex_id?: Prisma.IntFieldUpdateOperationsInput | number
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonDexNumbersListRelationFilter = {
  every?: Prisma.PokemonDexNumbersWhereInput
  some?: Prisma.PokemonDexNumbersWhereInput
  none?: Prisma.PokemonDexNumbersWhereInput
}

export type PokemonDexNumbersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PokemonDexNumbersSpecies_idPokedex_idCompoundUniqueInput = {
  species_id: number
  pokedex_id: number
}

export type PokemonDexNumbersCountOrderByAggregateInput = {
  species_id?: Prisma.SortOrder
  pokedex_id?: Prisma.SortOrder
  pokedex_number?: Prisma.SortOrder
}

export type PokemonDexNumbersAvgOrderByAggregateInput = {
  species_id?: Prisma.SortOrder
  pokedex_id?: Prisma.SortOrder
  pokedex_number?: Prisma.SortOrder
}

export type PokemonDexNumbersMaxOrderByAggregateInput = {
  species_id?: Prisma.SortOrder
  pokedex_id?: Prisma.SortOrder
  pokedex_number?: Prisma.SortOrder
}

export type PokemonDexNumbersMinOrderByAggregateInput = {
  species_id?: Prisma.SortOrder
  pokedex_id?: Prisma.SortOrder
  pokedex_number?: Prisma.SortOrder
}

export type PokemonDexNumbersSumOrderByAggregateInput = {
  species_id?: Prisma.SortOrder
  pokedex_id?: Prisma.SortOrder
  pokedex_number?: Prisma.SortOrder
}

export type PokemonDexNumbersCreateNestedManyWithoutSpeciesInput = {
  create?: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutSpeciesInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput> | Prisma.PokemonDexNumbersCreateWithoutSpeciesInput[] | Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput[]
  connectOrCreate?: Prisma.PokemonDexNumbersCreateOrConnectWithoutSpeciesInput | Prisma.PokemonDexNumbersCreateOrConnectWithoutSpeciesInput[]
  createMany?: Prisma.PokemonDexNumbersCreateManySpeciesInputEnvelope
  connect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
}

export type PokemonDexNumbersUncheckedCreateNestedManyWithoutSpeciesInput = {
  create?: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutSpeciesInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput> | Prisma.PokemonDexNumbersCreateWithoutSpeciesInput[] | Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput[]
  connectOrCreate?: Prisma.PokemonDexNumbersCreateOrConnectWithoutSpeciesInput | Prisma.PokemonDexNumbersCreateOrConnectWithoutSpeciesInput[]
  createMany?: Prisma.PokemonDexNumbersCreateManySpeciesInputEnvelope
  connect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
}

export type PokemonDexNumbersUpdateManyWithoutSpeciesNestedInput = {
  create?: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutSpeciesInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput> | Prisma.PokemonDexNumbersCreateWithoutSpeciesInput[] | Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput[]
  connectOrCreate?: Prisma.PokemonDexNumbersCreateOrConnectWithoutSpeciesInput | Prisma.PokemonDexNumbersCreateOrConnectWithoutSpeciesInput[]
  upsert?: Prisma.PokemonDexNumbersUpsertWithWhereUniqueWithoutSpeciesInput | Prisma.PokemonDexNumbersUpsertWithWhereUniqueWithoutSpeciesInput[]
  createMany?: Prisma.PokemonDexNumbersCreateManySpeciesInputEnvelope
  set?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  disconnect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  delete?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  connect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  update?: Prisma.PokemonDexNumbersUpdateWithWhereUniqueWithoutSpeciesInput | Prisma.PokemonDexNumbersUpdateWithWhereUniqueWithoutSpeciesInput[]
  updateMany?: Prisma.PokemonDexNumbersUpdateManyWithWhereWithoutSpeciesInput | Prisma.PokemonDexNumbersUpdateManyWithWhereWithoutSpeciesInput[]
  deleteMany?: Prisma.PokemonDexNumbersScalarWhereInput | Prisma.PokemonDexNumbersScalarWhereInput[]
}

export type PokemonDexNumbersUncheckedUpdateManyWithoutSpeciesNestedInput = {
  create?: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutSpeciesInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput> | Prisma.PokemonDexNumbersCreateWithoutSpeciesInput[] | Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput[]
  connectOrCreate?: Prisma.PokemonDexNumbersCreateOrConnectWithoutSpeciesInput | Prisma.PokemonDexNumbersCreateOrConnectWithoutSpeciesInput[]
  upsert?: Prisma.PokemonDexNumbersUpsertWithWhereUniqueWithoutSpeciesInput | Prisma.PokemonDexNumbersUpsertWithWhereUniqueWithoutSpeciesInput[]
  createMany?: Prisma.PokemonDexNumbersCreateManySpeciesInputEnvelope
  set?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  disconnect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  delete?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  connect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  update?: Prisma.PokemonDexNumbersUpdateWithWhereUniqueWithoutSpeciesInput | Prisma.PokemonDexNumbersUpdateWithWhereUniqueWithoutSpeciesInput[]
  updateMany?: Prisma.PokemonDexNumbersUpdateManyWithWhereWithoutSpeciesInput | Prisma.PokemonDexNumbersUpdateManyWithWhereWithoutSpeciesInput[]
  deleteMany?: Prisma.PokemonDexNumbersScalarWhereInput | Prisma.PokemonDexNumbersScalarWhereInput[]
}

export type PokemonDexNumbersCreateNestedManyWithoutPokedexInput = {
  create?: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutPokedexInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput> | Prisma.PokemonDexNumbersCreateWithoutPokedexInput[] | Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput[]
  connectOrCreate?: Prisma.PokemonDexNumbersCreateOrConnectWithoutPokedexInput | Prisma.PokemonDexNumbersCreateOrConnectWithoutPokedexInput[]
  createMany?: Prisma.PokemonDexNumbersCreateManyPokedexInputEnvelope
  connect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
}

export type PokemonDexNumbersUncheckedCreateNestedManyWithoutPokedexInput = {
  create?: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutPokedexInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput> | Prisma.PokemonDexNumbersCreateWithoutPokedexInput[] | Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput[]
  connectOrCreate?: Prisma.PokemonDexNumbersCreateOrConnectWithoutPokedexInput | Prisma.PokemonDexNumbersCreateOrConnectWithoutPokedexInput[]
  createMany?: Prisma.PokemonDexNumbersCreateManyPokedexInputEnvelope
  connect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
}

export type PokemonDexNumbersUpdateManyWithoutPokedexNestedInput = {
  create?: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutPokedexInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput> | Prisma.PokemonDexNumbersCreateWithoutPokedexInput[] | Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput[]
  connectOrCreate?: Prisma.PokemonDexNumbersCreateOrConnectWithoutPokedexInput | Prisma.PokemonDexNumbersCreateOrConnectWithoutPokedexInput[]
  upsert?: Prisma.PokemonDexNumbersUpsertWithWhereUniqueWithoutPokedexInput | Prisma.PokemonDexNumbersUpsertWithWhereUniqueWithoutPokedexInput[]
  createMany?: Prisma.PokemonDexNumbersCreateManyPokedexInputEnvelope
  set?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  disconnect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  delete?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  connect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  update?: Prisma.PokemonDexNumbersUpdateWithWhereUniqueWithoutPokedexInput | Prisma.PokemonDexNumbersUpdateWithWhereUniqueWithoutPokedexInput[]
  updateMany?: Prisma.PokemonDexNumbersUpdateManyWithWhereWithoutPokedexInput | Prisma.PokemonDexNumbersUpdateManyWithWhereWithoutPokedexInput[]
  deleteMany?: Prisma.PokemonDexNumbersScalarWhereInput | Prisma.PokemonDexNumbersScalarWhereInput[]
}

export type PokemonDexNumbersUncheckedUpdateManyWithoutPokedexNestedInput = {
  create?: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutPokedexInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput> | Prisma.PokemonDexNumbersCreateWithoutPokedexInput[] | Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput[]
  connectOrCreate?: Prisma.PokemonDexNumbersCreateOrConnectWithoutPokedexInput | Prisma.PokemonDexNumbersCreateOrConnectWithoutPokedexInput[]
  upsert?: Prisma.PokemonDexNumbersUpsertWithWhereUniqueWithoutPokedexInput | Prisma.PokemonDexNumbersUpsertWithWhereUniqueWithoutPokedexInput[]
  createMany?: Prisma.PokemonDexNumbersCreateManyPokedexInputEnvelope
  set?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  disconnect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  delete?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  connect?: Prisma.PokemonDexNumbersWhereUniqueInput | Prisma.PokemonDexNumbersWhereUniqueInput[]
  update?: Prisma.PokemonDexNumbersUpdateWithWhereUniqueWithoutPokedexInput | Prisma.PokemonDexNumbersUpdateWithWhereUniqueWithoutPokedexInput[]
  updateMany?: Prisma.PokemonDexNumbersUpdateManyWithWhereWithoutPokedexInput | Prisma.PokemonDexNumbersUpdateManyWithWhereWithoutPokedexInput[]
  deleteMany?: Prisma.PokemonDexNumbersScalarWhereInput | Prisma.PokemonDexNumbersScalarWhereInput[]
}

export type PokemonDexNumbersCreateWithoutSpeciesInput = {
  pokedex_number: number
  pokedex: Prisma.PokedexesCreateNestedOneWithoutDexNumbersInput
}

export type PokemonDexNumbersUncheckedCreateWithoutSpeciesInput = {
  pokedex_id: number
  pokedex_number: number
}

export type PokemonDexNumbersCreateOrConnectWithoutSpeciesInput = {
  where: Prisma.PokemonDexNumbersWhereUniqueInput
  create: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutSpeciesInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput>
}

export type PokemonDexNumbersCreateManySpeciesInputEnvelope = {
  data: Prisma.PokemonDexNumbersCreateManySpeciesInput | Prisma.PokemonDexNumbersCreateManySpeciesInput[]
  skipDuplicates?: boolean
}

export type PokemonDexNumbersUpsertWithWhereUniqueWithoutSpeciesInput = {
  where: Prisma.PokemonDexNumbersWhereUniqueInput
  update: Prisma.XOR<Prisma.PokemonDexNumbersUpdateWithoutSpeciesInput, Prisma.PokemonDexNumbersUncheckedUpdateWithoutSpeciesInput>
  create: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutSpeciesInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutSpeciesInput>
}

export type PokemonDexNumbersUpdateWithWhereUniqueWithoutSpeciesInput = {
  where: Prisma.PokemonDexNumbersWhereUniqueInput
  data: Prisma.XOR<Prisma.PokemonDexNumbersUpdateWithoutSpeciesInput, Prisma.PokemonDexNumbersUncheckedUpdateWithoutSpeciesInput>
}

export type PokemonDexNumbersUpdateManyWithWhereWithoutSpeciesInput = {
  where: Prisma.PokemonDexNumbersScalarWhereInput
  data: Prisma.XOR<Prisma.PokemonDexNumbersUpdateManyMutationInput, Prisma.PokemonDexNumbersUncheckedUpdateManyWithoutSpeciesInput>
}

export type PokemonDexNumbersScalarWhereInput = {
  AND?: Prisma.PokemonDexNumbersScalarWhereInput | Prisma.PokemonDexNumbersScalarWhereInput[]
  OR?: Prisma.PokemonDexNumbersScalarWhereInput[]
  NOT?: Prisma.PokemonDexNumbersScalarWhereInput | Prisma.PokemonDexNumbersScalarWhereInput[]
  species_id?: Prisma.IntFilter<"PokemonDexNumbers"> | number
  pokedex_id?: Prisma.IntFilter<"PokemonDexNumbers"> | number
  pokedex_number?: Prisma.IntFilter<"PokemonDexNumbers"> | number
}

export type PokemonDexNumbersCreateWithoutPokedexInput = {
  pokedex_number: number
  species: Prisma.PokemonSpeciesCreateNestedOneWithoutDexNumbersInput
}

export type PokemonDexNumbersUncheckedCreateWithoutPokedexInput = {
  species_id: number
  pokedex_number: number
}

export type PokemonDexNumbersCreateOrConnectWithoutPokedexInput = {
  where: Prisma.PokemonDexNumbersWhereUniqueInput
  create: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutPokedexInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput>
}

export type PokemonDexNumbersCreateManyPokedexInputEnvelope = {
  data: Prisma.PokemonDexNumbersCreateManyPokedexInput | Prisma.PokemonDexNumbersCreateManyPokedexInput[]
  skipDuplicates?: boolean
}

export type PokemonDexNumbersUpsertWithWhereUniqueWithoutPokedexInput = {
  where: Prisma.PokemonDexNumbersWhereUniqueInput
  update: Prisma.XOR<Prisma.PokemonDexNumbersUpdateWithoutPokedexInput, Prisma.PokemonDexNumbersUncheckedUpdateWithoutPokedexInput>
  create: Prisma.XOR<Prisma.PokemonDexNumbersCreateWithoutPokedexInput, Prisma.PokemonDexNumbersUncheckedCreateWithoutPokedexInput>
}

export type PokemonDexNumbersUpdateWithWhereUniqueWithoutPokedexInput = {
  where: Prisma.PokemonDexNumbersWhereUniqueInput
  data: Prisma.XOR<Prisma.PokemonDexNumbersUpdateWithoutPokedexInput, Prisma.PokemonDexNumbersUncheckedUpdateWithoutPokedexInput>
}

export type PokemonDexNumbersUpdateManyWithWhereWithoutPokedexInput = {
  where: Prisma.PokemonDexNumbersScalarWhereInput
  data: Prisma.XOR<Prisma.PokemonDexNumbersUpdateManyMutationInput, Prisma.PokemonDexNumbersUncheckedUpdateManyWithoutPokedexInput>
}

export type PokemonDexNumbersCreateManySpeciesInput = {
  pokedex_id: number
  pokedex_number: number
}

export type PokemonDexNumbersUpdateWithoutSpeciesInput = {
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
  pokedex?: Prisma.PokedexesUpdateOneRequiredWithoutDexNumbersNestedInput
}

export type PokemonDexNumbersUncheckedUpdateWithoutSpeciesInput = {
  pokedex_id?: Prisma.IntFieldUpdateOperationsInput | number
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonDexNumbersUncheckedUpdateManyWithoutSpeciesInput = {
  pokedex_id?: Prisma.IntFieldUpdateOperationsInput | number
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonDexNumbersCreateManyPokedexInput = {
  species_id: number
  pokedex_number: number
}

export type PokemonDexNumbersUpdateWithoutPokedexInput = {
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
  species?: Prisma.PokemonSpeciesUpdateOneRequiredWithoutDexNumbersNestedInput
}

export type PokemonDexNumbersUncheckedUpdateWithoutPokedexInput = {
  species_id?: Prisma.IntFieldUpdateOperationsInput | number
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonDexNumbersUncheckedUpdateManyWithoutPokedexInput = {
  species_id?: Prisma.IntFieldUpdateOperationsInput | number
  pokedex_number?: Prisma.IntFieldUpdateOperationsInput | number
}



export type PokemonDexNumbersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  species_id?: boolean
  pokedex_id?: boolean
  pokedex_number?: boolean
  species?: boolean | Prisma.PokemonSpeciesDefaultArgs<ExtArgs>
  pokedex?: boolean | Prisma.PokedexesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pokemonDexNumbers"]>

export type PokemonDexNumbersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  species_id?: boolean
  pokedex_id?: boolean
  pokedex_number?: boolean
  species?: boolean | Prisma.PokemonSpeciesDefaultArgs<ExtArgs>
  pokedex?: boolean | Prisma.PokedexesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pokemonDexNumbers"]>

export type PokemonDexNumbersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  species_id?: boolean
  pokedex_id?: boolean
  pokedex_number?: boolean
  species?: boolean | Prisma.PokemonSpeciesDefaultArgs<ExtArgs>
  pokedex?: boolean | Prisma.PokedexesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pokemonDexNumbers"]>

export type PokemonDexNumbersSelectScalar = {
  species_id?: boolean
  pokedex_id?: boolean
  pokedex_number?: boolean
}

export type PokemonDexNumbersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"species_id" | "pokedex_id" | "pokedex_number", ExtArgs["result"]["pokemonDexNumbers"]>
export type PokemonDexNumbersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  species?: boolean | Prisma.PokemonSpeciesDefaultArgs<ExtArgs>
  pokedex?: boolean | Prisma.PokedexesDefaultArgs<ExtArgs>
}
export type PokemonDexNumbersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  species?: boolean | Prisma.PokemonSpeciesDefaultArgs<ExtArgs>
  pokedex?: boolean | Prisma.PokedexesDefaultArgs<ExtArgs>
}
export type PokemonDexNumbersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  species?: boolean | Prisma.PokemonSpeciesDefaultArgs<ExtArgs>
  pokedex?: boolean | Prisma.PokedexesDefaultArgs<ExtArgs>
}

export type $PokemonDexNumbersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PokemonDexNumbers"
  objects: {
    species: Prisma.$PokemonSpeciesPayload<ExtArgs>
    pokedex: Prisma.$PokedexesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    species_id: number
    pokedex_id: number
    pokedex_number: number
  }, ExtArgs["result"]["pokemonDexNumbers"]>
  composites: {}
}

export type PokemonDexNumbersGetPayload<S extends boolean | null | undefined | PokemonDexNumbersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload, S>

export type PokemonDexNumbersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PokemonDexNumbersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PokemonDexNumbersCountAggregateInputType | true
  }

export interface PokemonDexNumbersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PokemonDexNumbers'], meta: { name: 'PokemonDexNumbers' } }
  /**
   * Find zero or one PokemonDexNumbers that matches the filter.
   * @param {PokemonDexNumbersFindUniqueArgs} args - Arguments to find a PokemonDexNumbers
   * @example
   * // Get one PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PokemonDexNumbersFindUniqueArgs>(args: Prisma.SelectSubset<T, PokemonDexNumbersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PokemonDexNumbersClient<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PokemonDexNumbers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PokemonDexNumbersFindUniqueOrThrowArgs} args - Arguments to find a PokemonDexNumbers
   * @example
   * // Get one PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PokemonDexNumbersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PokemonDexNumbersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PokemonDexNumbersClient<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PokemonDexNumbers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonDexNumbersFindFirstArgs} args - Arguments to find a PokemonDexNumbers
   * @example
   * // Get one PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PokemonDexNumbersFindFirstArgs>(args?: Prisma.SelectSubset<T, PokemonDexNumbersFindFirstArgs<ExtArgs>>): Prisma.Prisma__PokemonDexNumbersClient<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PokemonDexNumbers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonDexNumbersFindFirstOrThrowArgs} args - Arguments to find a PokemonDexNumbers
   * @example
   * // Get one PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PokemonDexNumbersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PokemonDexNumbersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PokemonDexNumbersClient<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PokemonDexNumbers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonDexNumbersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.findMany()
   * 
   * // Get first 10 PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.findMany({ take: 10 })
   * 
   * // Only select the `species_id`
   * const pokemonDexNumbersWithSpecies_idOnly = await prisma.pokemonDexNumbers.findMany({ select: { species_id: true } })
   * 
   */
  findMany<T extends PokemonDexNumbersFindManyArgs>(args?: Prisma.SelectSubset<T, PokemonDexNumbersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PokemonDexNumbers.
   * @param {PokemonDexNumbersCreateArgs} args - Arguments to create a PokemonDexNumbers.
   * @example
   * // Create one PokemonDexNumbers
   * const PokemonDexNumbers = await prisma.pokemonDexNumbers.create({
   *   data: {
   *     // ... data to create a PokemonDexNumbers
   *   }
   * })
   * 
   */
  create<T extends PokemonDexNumbersCreateArgs>(args: Prisma.SelectSubset<T, PokemonDexNumbersCreateArgs<ExtArgs>>): Prisma.Prisma__PokemonDexNumbersClient<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PokemonDexNumbers.
   * @param {PokemonDexNumbersCreateManyArgs} args - Arguments to create many PokemonDexNumbers.
   * @example
   * // Create many PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PokemonDexNumbersCreateManyArgs>(args?: Prisma.SelectSubset<T, PokemonDexNumbersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PokemonDexNumbers and returns the data saved in the database.
   * @param {PokemonDexNumbersCreateManyAndReturnArgs} args - Arguments to create many PokemonDexNumbers.
   * @example
   * // Create many PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PokemonDexNumbers and only return the `species_id`
   * const pokemonDexNumbersWithSpecies_idOnly = await prisma.pokemonDexNumbers.createManyAndReturn({
   *   select: { species_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PokemonDexNumbersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PokemonDexNumbersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PokemonDexNumbers.
   * @param {PokemonDexNumbersDeleteArgs} args - Arguments to delete one PokemonDexNumbers.
   * @example
   * // Delete one PokemonDexNumbers
   * const PokemonDexNumbers = await prisma.pokemonDexNumbers.delete({
   *   where: {
   *     // ... filter to delete one PokemonDexNumbers
   *   }
   * })
   * 
   */
  delete<T extends PokemonDexNumbersDeleteArgs>(args: Prisma.SelectSubset<T, PokemonDexNumbersDeleteArgs<ExtArgs>>): Prisma.Prisma__PokemonDexNumbersClient<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PokemonDexNumbers.
   * @param {PokemonDexNumbersUpdateArgs} args - Arguments to update one PokemonDexNumbers.
   * @example
   * // Update one PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PokemonDexNumbersUpdateArgs>(args: Prisma.SelectSubset<T, PokemonDexNumbersUpdateArgs<ExtArgs>>): Prisma.Prisma__PokemonDexNumbersClient<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PokemonDexNumbers.
   * @param {PokemonDexNumbersDeleteManyArgs} args - Arguments to filter PokemonDexNumbers to delete.
   * @example
   * // Delete a few PokemonDexNumbers
   * const { count } = await prisma.pokemonDexNumbers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PokemonDexNumbersDeleteManyArgs>(args?: Prisma.SelectSubset<T, PokemonDexNumbersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PokemonDexNumbers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonDexNumbersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PokemonDexNumbersUpdateManyArgs>(args: Prisma.SelectSubset<T, PokemonDexNumbersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PokemonDexNumbers and returns the data updated in the database.
   * @param {PokemonDexNumbersUpdateManyAndReturnArgs} args - Arguments to update many PokemonDexNumbers.
   * @example
   * // Update many PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PokemonDexNumbers and only return the `species_id`
   * const pokemonDexNumbersWithSpecies_idOnly = await prisma.pokemonDexNumbers.updateManyAndReturn({
   *   select: { species_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PokemonDexNumbersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PokemonDexNumbersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PokemonDexNumbers.
   * @param {PokemonDexNumbersUpsertArgs} args - Arguments to update or create a PokemonDexNumbers.
   * @example
   * // Update or create a PokemonDexNumbers
   * const pokemonDexNumbers = await prisma.pokemonDexNumbers.upsert({
   *   create: {
   *     // ... data to create a PokemonDexNumbers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PokemonDexNumbers we want to update
   *   }
   * })
   */
  upsert<T extends PokemonDexNumbersUpsertArgs>(args: Prisma.SelectSubset<T, PokemonDexNumbersUpsertArgs<ExtArgs>>): Prisma.Prisma__PokemonDexNumbersClient<runtime.Types.Result.GetResult<Prisma.$PokemonDexNumbersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PokemonDexNumbers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonDexNumbersCountArgs} args - Arguments to filter PokemonDexNumbers to count.
   * @example
   * // Count the number of PokemonDexNumbers
   * const count = await prisma.pokemonDexNumbers.count({
   *   where: {
   *     // ... the filter for the PokemonDexNumbers we want to count
   *   }
   * })
  **/
  count<T extends PokemonDexNumbersCountArgs>(
    args?: Prisma.Subset<T, PokemonDexNumbersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PokemonDexNumbersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PokemonDexNumbers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonDexNumbersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PokemonDexNumbersAggregateArgs>(args: Prisma.Subset<T, PokemonDexNumbersAggregateArgs>): Prisma.PrismaPromise<GetPokemonDexNumbersAggregateType<T>>

  /**
   * Group by PokemonDexNumbers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonDexNumbersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PokemonDexNumbersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PokemonDexNumbersGroupByArgs['orderBy'] }
      : { orderBy?: PokemonDexNumbersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PokemonDexNumbersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPokemonDexNumbersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PokemonDexNumbers model
 */
readonly fields: PokemonDexNumbersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PokemonDexNumbers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PokemonDexNumbersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  species<T extends Prisma.PokemonSpeciesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PokemonSpeciesDefaultArgs<ExtArgs>>): Prisma.Prisma__PokemonSpeciesClient<runtime.Types.Result.GetResult<Prisma.$PokemonSpeciesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  pokedex<T extends Prisma.PokedexesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PokedexesDefaultArgs<ExtArgs>>): Prisma.Prisma__PokedexesClient<runtime.Types.Result.GetResult<Prisma.$PokedexesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PokemonDexNumbers model
 */
export interface PokemonDexNumbersFieldRefs {
  readonly species_id: Prisma.FieldRef<"PokemonDexNumbers", 'Int'>
  readonly pokedex_id: Prisma.FieldRef<"PokemonDexNumbers", 'Int'>
  readonly pokedex_number: Prisma.FieldRef<"PokemonDexNumbers", 'Int'>
}
    

// Custom InputTypes
/**
 * PokemonDexNumbers findUnique
 */
export type PokemonDexNumbersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
  /**
   * Filter, which PokemonDexNumbers to fetch.
   */
  where: Prisma.PokemonDexNumbersWhereUniqueInput
}

/**
 * PokemonDexNumbers findUniqueOrThrow
 */
export type PokemonDexNumbersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
  /**
   * Filter, which PokemonDexNumbers to fetch.
   */
  where: Prisma.PokemonDexNumbersWhereUniqueInput
}

/**
 * PokemonDexNumbers findFirst
 */
export type PokemonDexNumbersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
  /**
   * Filter, which PokemonDexNumbers to fetch.
   */
  where?: Prisma.PokemonDexNumbersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonDexNumbers to fetch.
   */
  orderBy?: Prisma.PokemonDexNumbersOrderByWithRelationInput | Prisma.PokemonDexNumbersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PokemonDexNumbers.
   */
  cursor?: Prisma.PokemonDexNumbersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonDexNumbers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonDexNumbers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PokemonDexNumbers.
   */
  distinct?: Prisma.PokemonDexNumbersScalarFieldEnum | Prisma.PokemonDexNumbersScalarFieldEnum[]
}

/**
 * PokemonDexNumbers findFirstOrThrow
 */
export type PokemonDexNumbersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
  /**
   * Filter, which PokemonDexNumbers to fetch.
   */
  where?: Prisma.PokemonDexNumbersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonDexNumbers to fetch.
   */
  orderBy?: Prisma.PokemonDexNumbersOrderByWithRelationInput | Prisma.PokemonDexNumbersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PokemonDexNumbers.
   */
  cursor?: Prisma.PokemonDexNumbersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonDexNumbers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonDexNumbers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PokemonDexNumbers.
   */
  distinct?: Prisma.PokemonDexNumbersScalarFieldEnum | Prisma.PokemonDexNumbersScalarFieldEnum[]
}

/**
 * PokemonDexNumbers findMany
 */
export type PokemonDexNumbersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
  /**
   * Filter, which PokemonDexNumbers to fetch.
   */
  where?: Prisma.PokemonDexNumbersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonDexNumbers to fetch.
   */
  orderBy?: Prisma.PokemonDexNumbersOrderByWithRelationInput | Prisma.PokemonDexNumbersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PokemonDexNumbers.
   */
  cursor?: Prisma.PokemonDexNumbersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonDexNumbers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonDexNumbers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PokemonDexNumbers.
   */
  distinct?: Prisma.PokemonDexNumbersScalarFieldEnum | Prisma.PokemonDexNumbersScalarFieldEnum[]
}

/**
 * PokemonDexNumbers create
 */
export type PokemonDexNumbersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
  /**
   * The data needed to create a PokemonDexNumbers.
   */
  data: Prisma.XOR<Prisma.PokemonDexNumbersCreateInput, Prisma.PokemonDexNumbersUncheckedCreateInput>
}

/**
 * PokemonDexNumbers createMany
 */
export type PokemonDexNumbersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PokemonDexNumbers.
   */
  data: Prisma.PokemonDexNumbersCreateManyInput | Prisma.PokemonDexNumbersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PokemonDexNumbers createManyAndReturn
 */
export type PokemonDexNumbersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * The data used to create many PokemonDexNumbers.
   */
  data: Prisma.PokemonDexNumbersCreateManyInput | Prisma.PokemonDexNumbersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PokemonDexNumbers update
 */
export type PokemonDexNumbersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
  /**
   * The data needed to update a PokemonDexNumbers.
   */
  data: Prisma.XOR<Prisma.PokemonDexNumbersUpdateInput, Prisma.PokemonDexNumbersUncheckedUpdateInput>
  /**
   * Choose, which PokemonDexNumbers to update.
   */
  where: Prisma.PokemonDexNumbersWhereUniqueInput
}

/**
 * PokemonDexNumbers updateMany
 */
export type PokemonDexNumbersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PokemonDexNumbers.
   */
  data: Prisma.XOR<Prisma.PokemonDexNumbersUpdateManyMutationInput, Prisma.PokemonDexNumbersUncheckedUpdateManyInput>
  /**
   * Filter which PokemonDexNumbers to update
   */
  where?: Prisma.PokemonDexNumbersWhereInput
  /**
   * Limit how many PokemonDexNumbers to update.
   */
  limit?: number
}

/**
 * PokemonDexNumbers updateManyAndReturn
 */
export type PokemonDexNumbersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * The data used to update PokemonDexNumbers.
   */
  data: Prisma.XOR<Prisma.PokemonDexNumbersUpdateManyMutationInput, Prisma.PokemonDexNumbersUncheckedUpdateManyInput>
  /**
   * Filter which PokemonDexNumbers to update
   */
  where?: Prisma.PokemonDexNumbersWhereInput
  /**
   * Limit how many PokemonDexNumbers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PokemonDexNumbers upsert
 */
export type PokemonDexNumbersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
  /**
   * The filter to search for the PokemonDexNumbers to update in case it exists.
   */
  where: Prisma.PokemonDexNumbersWhereUniqueInput
  /**
   * In case the PokemonDexNumbers found by the `where` argument doesn't exist, create a new PokemonDexNumbers with this data.
   */
  create: Prisma.XOR<Prisma.PokemonDexNumbersCreateInput, Prisma.PokemonDexNumbersUncheckedCreateInput>
  /**
   * In case the PokemonDexNumbers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PokemonDexNumbersUpdateInput, Prisma.PokemonDexNumbersUncheckedUpdateInput>
}

/**
 * PokemonDexNumbers delete
 */
export type PokemonDexNumbersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
  /**
   * Filter which PokemonDexNumbers to delete.
   */
  where: Prisma.PokemonDexNumbersWhereUniqueInput
}

/**
 * PokemonDexNumbers deleteMany
 */
export type PokemonDexNumbersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PokemonDexNumbers to delete
   */
  where?: Prisma.PokemonDexNumbersWhereInput
  /**
   * Limit how many PokemonDexNumbers to delete.
   */
  limit?: number
}

/**
 * PokemonDexNumbers without action
 */
export type PokemonDexNumbersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonDexNumbers
   */
  select?: Prisma.PokemonDexNumbersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonDexNumbers
   */
  omit?: Prisma.PokemonDexNumbersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonDexNumbersInclude<ExtArgs> | null
}
