
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PokemonTypes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PokemonTypes
 * @@TypeGraphQL.type(name: "PokemonType")
 */
export type PokemonTypesModel = runtime.Types.Result.DefaultSelection<Prisma.$PokemonTypesPayload>

export type AggregatePokemonTypes = {
  _count: PokemonTypesCountAggregateOutputType | null
  _avg: PokemonTypesAvgAggregateOutputType | null
  _sum: PokemonTypesSumAggregateOutputType | null
  _min: PokemonTypesMinAggregateOutputType | null
  _max: PokemonTypesMaxAggregateOutputType | null
}

export type PokemonTypesAvgAggregateOutputType = {
  pokemon_id: number | null
  type_id: number | null
  slot: number | null
}

export type PokemonTypesSumAggregateOutputType = {
  pokemon_id: number | null
  type_id: number | null
  slot: number | null
}

export type PokemonTypesMinAggregateOutputType = {
  pokemon_id: number | null
  type_id: number | null
  slot: number | null
}

export type PokemonTypesMaxAggregateOutputType = {
  pokemon_id: number | null
  type_id: number | null
  slot: number | null
}

export type PokemonTypesCountAggregateOutputType = {
  pokemon_id: number
  type_id: number
  slot: number
  _all: number
}


export type PokemonTypesAvgAggregateInputType = {
  pokemon_id?: true
  type_id?: true
  slot?: true
}

export type PokemonTypesSumAggregateInputType = {
  pokemon_id?: true
  type_id?: true
  slot?: true
}

export type PokemonTypesMinAggregateInputType = {
  pokemon_id?: true
  type_id?: true
  slot?: true
}

export type PokemonTypesMaxAggregateInputType = {
  pokemon_id?: true
  type_id?: true
  slot?: true
}

export type PokemonTypesCountAggregateInputType = {
  pokemon_id?: true
  type_id?: true
  slot?: true
  _all?: true
}

export type PokemonTypesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PokemonTypes to aggregate.
   */
  where?: Prisma.PokemonTypesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonTypes to fetch.
   */
  orderBy?: Prisma.PokemonTypesOrderByWithRelationInput | Prisma.PokemonTypesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PokemonTypesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PokemonTypes
  **/
  _count?: true | PokemonTypesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PokemonTypesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PokemonTypesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PokemonTypesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PokemonTypesMaxAggregateInputType
}

export type GetPokemonTypesAggregateType<T extends PokemonTypesAggregateArgs> = {
      [P in keyof T & keyof AggregatePokemonTypes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePokemonTypes[P]>
    : Prisma.GetScalarType<T[P], AggregatePokemonTypes[P]>
}




export type PokemonTypesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PokemonTypesWhereInput
  orderBy?: Prisma.PokemonTypesOrderByWithAggregationInput | Prisma.PokemonTypesOrderByWithAggregationInput[]
  by: Prisma.PokemonTypesScalarFieldEnum[] | Prisma.PokemonTypesScalarFieldEnum
  having?: Prisma.PokemonTypesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PokemonTypesCountAggregateInputType | true
  _avg?: PokemonTypesAvgAggregateInputType
  _sum?: PokemonTypesSumAggregateInputType
  _min?: PokemonTypesMinAggregateInputType
  _max?: PokemonTypesMaxAggregateInputType
}

export type PokemonTypesGroupByOutputType = {
  pokemon_id: number
  type_id: number
  slot: number
  _count: PokemonTypesCountAggregateOutputType | null
  _avg: PokemonTypesAvgAggregateOutputType | null
  _sum: PokemonTypesSumAggregateOutputType | null
  _min: PokemonTypesMinAggregateOutputType | null
  _max: PokemonTypesMaxAggregateOutputType | null
}

export type GetPokemonTypesGroupByPayload<T extends PokemonTypesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PokemonTypesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PokemonTypesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PokemonTypesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PokemonTypesGroupByOutputType[P]>
      }
    >
  >



export type PokemonTypesWhereInput = {
  AND?: Prisma.PokemonTypesWhereInput | Prisma.PokemonTypesWhereInput[]
  OR?: Prisma.PokemonTypesWhereInput[]
  NOT?: Prisma.PokemonTypesWhereInput | Prisma.PokemonTypesWhereInput[]
  pokemon_id?: Prisma.IntFilter<"PokemonTypes"> | number
  type_id?: Prisma.IntFilter<"PokemonTypes"> | number
  slot?: Prisma.IntFilter<"PokemonTypes"> | number
  pokemon?: Prisma.XOR<Prisma.PokemonScalarRelationFilter, Prisma.PokemonWhereInput>
  type?: Prisma.XOR<Prisma.TypesScalarRelationFilter, Prisma.TypesWhereInput>
}

export type PokemonTypesOrderByWithRelationInput = {
  pokemon_id?: Prisma.SortOrder
  type_id?: Prisma.SortOrder
  slot?: Prisma.SortOrder
  pokemon?: Prisma.PokemonOrderByWithRelationInput
  type?: Prisma.TypesOrderByWithRelationInput
}

export type PokemonTypesWhereUniqueInput = Prisma.AtLeast<{
  pokemon_id_type_id?: Prisma.PokemonTypesPokemon_idType_idCompoundUniqueInput
  AND?: Prisma.PokemonTypesWhereInput | Prisma.PokemonTypesWhereInput[]
  OR?: Prisma.PokemonTypesWhereInput[]
  NOT?: Prisma.PokemonTypesWhereInput | Prisma.PokemonTypesWhereInput[]
  pokemon_id?: Prisma.IntFilter<"PokemonTypes"> | number
  type_id?: Prisma.IntFilter<"PokemonTypes"> | number
  slot?: Prisma.IntFilter<"PokemonTypes"> | number
  pokemon?: Prisma.XOR<Prisma.PokemonScalarRelationFilter, Prisma.PokemonWhereInput>
  type?: Prisma.XOR<Prisma.TypesScalarRelationFilter, Prisma.TypesWhereInput>
}, "pokemon_id_type_id">

export type PokemonTypesOrderByWithAggregationInput = {
  pokemon_id?: Prisma.SortOrder
  type_id?: Prisma.SortOrder
  slot?: Prisma.SortOrder
  _count?: Prisma.PokemonTypesCountOrderByAggregateInput
  _avg?: Prisma.PokemonTypesAvgOrderByAggregateInput
  _max?: Prisma.PokemonTypesMaxOrderByAggregateInput
  _min?: Prisma.PokemonTypesMinOrderByAggregateInput
  _sum?: Prisma.PokemonTypesSumOrderByAggregateInput
}

export type PokemonTypesScalarWhereWithAggregatesInput = {
  AND?: Prisma.PokemonTypesScalarWhereWithAggregatesInput | Prisma.PokemonTypesScalarWhereWithAggregatesInput[]
  OR?: Prisma.PokemonTypesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PokemonTypesScalarWhereWithAggregatesInput | Prisma.PokemonTypesScalarWhereWithAggregatesInput[]
  pokemon_id?: Prisma.IntWithAggregatesFilter<"PokemonTypes"> | number
  type_id?: Prisma.IntWithAggregatesFilter<"PokemonTypes"> | number
  slot?: Prisma.IntWithAggregatesFilter<"PokemonTypes"> | number
}

export type PokemonTypesCreateInput = {
  slot: number
  pokemon: Prisma.PokemonCreateNestedOneWithoutTypesInput
  type: Prisma.TypesCreateNestedOneWithoutPokemonTypesInput
}

export type PokemonTypesUncheckedCreateInput = {
  pokemon_id: number
  type_id: number
  slot: number
}

export type PokemonTypesUpdateInput = {
  slot?: Prisma.IntFieldUpdateOperationsInput | number
  pokemon?: Prisma.PokemonUpdateOneRequiredWithoutTypesNestedInput
  type?: Prisma.TypesUpdateOneRequiredWithoutPokemonTypesNestedInput
}

export type PokemonTypesUncheckedUpdateInput = {
  pokemon_id?: Prisma.IntFieldUpdateOperationsInput | number
  type_id?: Prisma.IntFieldUpdateOperationsInput | number
  slot?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonTypesCreateManyInput = {
  pokemon_id: number
  type_id: number
  slot: number
}

export type PokemonTypesUpdateManyMutationInput = {
  slot?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonTypesUncheckedUpdateManyInput = {
  pokemon_id?: Prisma.IntFieldUpdateOperationsInput | number
  type_id?: Prisma.IntFieldUpdateOperationsInput | number
  slot?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonTypesListRelationFilter = {
  every?: Prisma.PokemonTypesWhereInput
  some?: Prisma.PokemonTypesWhereInput
  none?: Prisma.PokemonTypesWhereInput
}

export type PokemonTypesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PokemonTypesPokemon_idType_idCompoundUniqueInput = {
  pokemon_id: number
  type_id: number
}

export type PokemonTypesCountOrderByAggregateInput = {
  pokemon_id?: Prisma.SortOrder
  type_id?: Prisma.SortOrder
  slot?: Prisma.SortOrder
}

export type PokemonTypesAvgOrderByAggregateInput = {
  pokemon_id?: Prisma.SortOrder
  type_id?: Prisma.SortOrder
  slot?: Prisma.SortOrder
}

export type PokemonTypesMaxOrderByAggregateInput = {
  pokemon_id?: Prisma.SortOrder
  type_id?: Prisma.SortOrder
  slot?: Prisma.SortOrder
}

export type PokemonTypesMinOrderByAggregateInput = {
  pokemon_id?: Prisma.SortOrder
  type_id?: Prisma.SortOrder
  slot?: Prisma.SortOrder
}

export type PokemonTypesSumOrderByAggregateInput = {
  pokemon_id?: Prisma.SortOrder
  type_id?: Prisma.SortOrder
  slot?: Prisma.SortOrder
}

export type PokemonTypesCreateNestedManyWithoutPokemonInput = {
  create?: Prisma.XOR<Prisma.PokemonTypesCreateWithoutPokemonInput, Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput> | Prisma.PokemonTypesCreateWithoutPokemonInput[] | Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput[]
  connectOrCreate?: Prisma.PokemonTypesCreateOrConnectWithoutPokemonInput | Prisma.PokemonTypesCreateOrConnectWithoutPokemonInput[]
  createMany?: Prisma.PokemonTypesCreateManyPokemonInputEnvelope
  connect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
}

export type PokemonTypesUncheckedCreateNestedManyWithoutPokemonInput = {
  create?: Prisma.XOR<Prisma.PokemonTypesCreateWithoutPokemonInput, Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput> | Prisma.PokemonTypesCreateWithoutPokemonInput[] | Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput[]
  connectOrCreate?: Prisma.PokemonTypesCreateOrConnectWithoutPokemonInput | Prisma.PokemonTypesCreateOrConnectWithoutPokemonInput[]
  createMany?: Prisma.PokemonTypesCreateManyPokemonInputEnvelope
  connect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
}

export type PokemonTypesUpdateManyWithoutPokemonNestedInput = {
  create?: Prisma.XOR<Prisma.PokemonTypesCreateWithoutPokemonInput, Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput> | Prisma.PokemonTypesCreateWithoutPokemonInput[] | Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput[]
  connectOrCreate?: Prisma.PokemonTypesCreateOrConnectWithoutPokemonInput | Prisma.PokemonTypesCreateOrConnectWithoutPokemonInput[]
  upsert?: Prisma.PokemonTypesUpsertWithWhereUniqueWithoutPokemonInput | Prisma.PokemonTypesUpsertWithWhereUniqueWithoutPokemonInput[]
  createMany?: Prisma.PokemonTypesCreateManyPokemonInputEnvelope
  set?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  disconnect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  delete?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  connect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  update?: Prisma.PokemonTypesUpdateWithWhereUniqueWithoutPokemonInput | Prisma.PokemonTypesUpdateWithWhereUniqueWithoutPokemonInput[]
  updateMany?: Prisma.PokemonTypesUpdateManyWithWhereWithoutPokemonInput | Prisma.PokemonTypesUpdateManyWithWhereWithoutPokemonInput[]
  deleteMany?: Prisma.PokemonTypesScalarWhereInput | Prisma.PokemonTypesScalarWhereInput[]
}

export type PokemonTypesUncheckedUpdateManyWithoutPokemonNestedInput = {
  create?: Prisma.XOR<Prisma.PokemonTypesCreateWithoutPokemonInput, Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput> | Prisma.PokemonTypesCreateWithoutPokemonInput[] | Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput[]
  connectOrCreate?: Prisma.PokemonTypesCreateOrConnectWithoutPokemonInput | Prisma.PokemonTypesCreateOrConnectWithoutPokemonInput[]
  upsert?: Prisma.PokemonTypesUpsertWithWhereUniqueWithoutPokemonInput | Prisma.PokemonTypesUpsertWithWhereUniqueWithoutPokemonInput[]
  createMany?: Prisma.PokemonTypesCreateManyPokemonInputEnvelope
  set?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  disconnect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  delete?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  connect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  update?: Prisma.PokemonTypesUpdateWithWhereUniqueWithoutPokemonInput | Prisma.PokemonTypesUpdateWithWhereUniqueWithoutPokemonInput[]
  updateMany?: Prisma.PokemonTypesUpdateManyWithWhereWithoutPokemonInput | Prisma.PokemonTypesUpdateManyWithWhereWithoutPokemonInput[]
  deleteMany?: Prisma.PokemonTypesScalarWhereInput | Prisma.PokemonTypesScalarWhereInput[]
}

export type PokemonTypesCreateNestedManyWithoutTypeInput = {
  create?: Prisma.XOR<Prisma.PokemonTypesCreateWithoutTypeInput, Prisma.PokemonTypesUncheckedCreateWithoutTypeInput> | Prisma.PokemonTypesCreateWithoutTypeInput[] | Prisma.PokemonTypesUncheckedCreateWithoutTypeInput[]
  connectOrCreate?: Prisma.PokemonTypesCreateOrConnectWithoutTypeInput | Prisma.PokemonTypesCreateOrConnectWithoutTypeInput[]
  createMany?: Prisma.PokemonTypesCreateManyTypeInputEnvelope
  connect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
}

export type PokemonTypesUncheckedCreateNestedManyWithoutTypeInput = {
  create?: Prisma.XOR<Prisma.PokemonTypesCreateWithoutTypeInput, Prisma.PokemonTypesUncheckedCreateWithoutTypeInput> | Prisma.PokemonTypesCreateWithoutTypeInput[] | Prisma.PokemonTypesUncheckedCreateWithoutTypeInput[]
  connectOrCreate?: Prisma.PokemonTypesCreateOrConnectWithoutTypeInput | Prisma.PokemonTypesCreateOrConnectWithoutTypeInput[]
  createMany?: Prisma.PokemonTypesCreateManyTypeInputEnvelope
  connect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
}

export type PokemonTypesUpdateManyWithoutTypeNestedInput = {
  create?: Prisma.XOR<Prisma.PokemonTypesCreateWithoutTypeInput, Prisma.PokemonTypesUncheckedCreateWithoutTypeInput> | Prisma.PokemonTypesCreateWithoutTypeInput[] | Prisma.PokemonTypesUncheckedCreateWithoutTypeInput[]
  connectOrCreate?: Prisma.PokemonTypesCreateOrConnectWithoutTypeInput | Prisma.PokemonTypesCreateOrConnectWithoutTypeInput[]
  upsert?: Prisma.PokemonTypesUpsertWithWhereUniqueWithoutTypeInput | Prisma.PokemonTypesUpsertWithWhereUniqueWithoutTypeInput[]
  createMany?: Prisma.PokemonTypesCreateManyTypeInputEnvelope
  set?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  disconnect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  delete?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  connect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  update?: Prisma.PokemonTypesUpdateWithWhereUniqueWithoutTypeInput | Prisma.PokemonTypesUpdateWithWhereUniqueWithoutTypeInput[]
  updateMany?: Prisma.PokemonTypesUpdateManyWithWhereWithoutTypeInput | Prisma.PokemonTypesUpdateManyWithWhereWithoutTypeInput[]
  deleteMany?: Prisma.PokemonTypesScalarWhereInput | Prisma.PokemonTypesScalarWhereInput[]
}

export type PokemonTypesUncheckedUpdateManyWithoutTypeNestedInput = {
  create?: Prisma.XOR<Prisma.PokemonTypesCreateWithoutTypeInput, Prisma.PokemonTypesUncheckedCreateWithoutTypeInput> | Prisma.PokemonTypesCreateWithoutTypeInput[] | Prisma.PokemonTypesUncheckedCreateWithoutTypeInput[]
  connectOrCreate?: Prisma.PokemonTypesCreateOrConnectWithoutTypeInput | Prisma.PokemonTypesCreateOrConnectWithoutTypeInput[]
  upsert?: Prisma.PokemonTypesUpsertWithWhereUniqueWithoutTypeInput | Prisma.PokemonTypesUpsertWithWhereUniqueWithoutTypeInput[]
  createMany?: Prisma.PokemonTypesCreateManyTypeInputEnvelope
  set?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  disconnect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  delete?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  connect?: Prisma.PokemonTypesWhereUniqueInput | Prisma.PokemonTypesWhereUniqueInput[]
  update?: Prisma.PokemonTypesUpdateWithWhereUniqueWithoutTypeInput | Prisma.PokemonTypesUpdateWithWhereUniqueWithoutTypeInput[]
  updateMany?: Prisma.PokemonTypesUpdateManyWithWhereWithoutTypeInput | Prisma.PokemonTypesUpdateManyWithWhereWithoutTypeInput[]
  deleteMany?: Prisma.PokemonTypesScalarWhereInput | Prisma.PokemonTypesScalarWhereInput[]
}

export type PokemonTypesCreateWithoutPokemonInput = {
  slot: number
  type: Prisma.TypesCreateNestedOneWithoutPokemonTypesInput
}

export type PokemonTypesUncheckedCreateWithoutPokemonInput = {
  type_id: number
  slot: number
}

export type PokemonTypesCreateOrConnectWithoutPokemonInput = {
  where: Prisma.PokemonTypesWhereUniqueInput
  create: Prisma.XOR<Prisma.PokemonTypesCreateWithoutPokemonInput, Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput>
}

export type PokemonTypesCreateManyPokemonInputEnvelope = {
  data: Prisma.PokemonTypesCreateManyPokemonInput | Prisma.PokemonTypesCreateManyPokemonInput[]
  skipDuplicates?: boolean
}

export type PokemonTypesUpsertWithWhereUniqueWithoutPokemonInput = {
  where: Prisma.PokemonTypesWhereUniqueInput
  update: Prisma.XOR<Prisma.PokemonTypesUpdateWithoutPokemonInput, Prisma.PokemonTypesUncheckedUpdateWithoutPokemonInput>
  create: Prisma.XOR<Prisma.PokemonTypesCreateWithoutPokemonInput, Prisma.PokemonTypesUncheckedCreateWithoutPokemonInput>
}

export type PokemonTypesUpdateWithWhereUniqueWithoutPokemonInput = {
  where: Prisma.PokemonTypesWhereUniqueInput
  data: Prisma.XOR<Prisma.PokemonTypesUpdateWithoutPokemonInput, Prisma.PokemonTypesUncheckedUpdateWithoutPokemonInput>
}

export type PokemonTypesUpdateManyWithWhereWithoutPokemonInput = {
  where: Prisma.PokemonTypesScalarWhereInput
  data: Prisma.XOR<Prisma.PokemonTypesUpdateManyMutationInput, Prisma.PokemonTypesUncheckedUpdateManyWithoutPokemonInput>
}

export type PokemonTypesScalarWhereInput = {
  AND?: Prisma.PokemonTypesScalarWhereInput | Prisma.PokemonTypesScalarWhereInput[]
  OR?: Prisma.PokemonTypesScalarWhereInput[]
  NOT?: Prisma.PokemonTypesScalarWhereInput | Prisma.PokemonTypesScalarWhereInput[]
  pokemon_id?: Prisma.IntFilter<"PokemonTypes"> | number
  type_id?: Prisma.IntFilter<"PokemonTypes"> | number
  slot?: Prisma.IntFilter<"PokemonTypes"> | number
}

export type PokemonTypesCreateWithoutTypeInput = {
  slot: number
  pokemon: Prisma.PokemonCreateNestedOneWithoutTypesInput
}

export type PokemonTypesUncheckedCreateWithoutTypeInput = {
  pokemon_id: number
  slot: number
}

export type PokemonTypesCreateOrConnectWithoutTypeInput = {
  where: Prisma.PokemonTypesWhereUniqueInput
  create: Prisma.XOR<Prisma.PokemonTypesCreateWithoutTypeInput, Prisma.PokemonTypesUncheckedCreateWithoutTypeInput>
}

export type PokemonTypesCreateManyTypeInputEnvelope = {
  data: Prisma.PokemonTypesCreateManyTypeInput | Prisma.PokemonTypesCreateManyTypeInput[]
  skipDuplicates?: boolean
}

export type PokemonTypesUpsertWithWhereUniqueWithoutTypeInput = {
  where: Prisma.PokemonTypesWhereUniqueInput
  update: Prisma.XOR<Prisma.PokemonTypesUpdateWithoutTypeInput, Prisma.PokemonTypesUncheckedUpdateWithoutTypeInput>
  create: Prisma.XOR<Prisma.PokemonTypesCreateWithoutTypeInput, Prisma.PokemonTypesUncheckedCreateWithoutTypeInput>
}

export type PokemonTypesUpdateWithWhereUniqueWithoutTypeInput = {
  where: Prisma.PokemonTypesWhereUniqueInput
  data: Prisma.XOR<Prisma.PokemonTypesUpdateWithoutTypeInput, Prisma.PokemonTypesUncheckedUpdateWithoutTypeInput>
}

export type PokemonTypesUpdateManyWithWhereWithoutTypeInput = {
  where: Prisma.PokemonTypesScalarWhereInput
  data: Prisma.XOR<Prisma.PokemonTypesUpdateManyMutationInput, Prisma.PokemonTypesUncheckedUpdateManyWithoutTypeInput>
}

export type PokemonTypesCreateManyPokemonInput = {
  type_id: number
  slot: number
}

export type PokemonTypesUpdateWithoutPokemonInput = {
  slot?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.TypesUpdateOneRequiredWithoutPokemonTypesNestedInput
}

export type PokemonTypesUncheckedUpdateWithoutPokemonInput = {
  type_id?: Prisma.IntFieldUpdateOperationsInput | number
  slot?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonTypesUncheckedUpdateManyWithoutPokemonInput = {
  type_id?: Prisma.IntFieldUpdateOperationsInput | number
  slot?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonTypesCreateManyTypeInput = {
  pokemon_id: number
  slot: number
}

export type PokemonTypesUpdateWithoutTypeInput = {
  slot?: Prisma.IntFieldUpdateOperationsInput | number
  pokemon?: Prisma.PokemonUpdateOneRequiredWithoutTypesNestedInput
}

export type PokemonTypesUncheckedUpdateWithoutTypeInput = {
  pokemon_id?: Prisma.IntFieldUpdateOperationsInput | number
  slot?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PokemonTypesUncheckedUpdateManyWithoutTypeInput = {
  pokemon_id?: Prisma.IntFieldUpdateOperationsInput | number
  slot?: Prisma.IntFieldUpdateOperationsInput | number
}



export type PokemonTypesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  pokemon_id?: boolean
  type_id?: boolean
  slot?: boolean
  pokemon?: boolean | Prisma.PokemonDefaultArgs<ExtArgs>
  type?: boolean | Prisma.TypesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pokemonTypes"]>

export type PokemonTypesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  pokemon_id?: boolean
  type_id?: boolean
  slot?: boolean
  pokemon?: boolean | Prisma.PokemonDefaultArgs<ExtArgs>
  type?: boolean | Prisma.TypesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pokemonTypes"]>

export type PokemonTypesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  pokemon_id?: boolean
  type_id?: boolean
  slot?: boolean
  pokemon?: boolean | Prisma.PokemonDefaultArgs<ExtArgs>
  type?: boolean | Prisma.TypesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pokemonTypes"]>

export type PokemonTypesSelectScalar = {
  pokemon_id?: boolean
  type_id?: boolean
  slot?: boolean
}

export type PokemonTypesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"pokemon_id" | "type_id" | "slot", ExtArgs["result"]["pokemonTypes"]>
export type PokemonTypesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pokemon?: boolean | Prisma.PokemonDefaultArgs<ExtArgs>
  type?: boolean | Prisma.TypesDefaultArgs<ExtArgs>
}
export type PokemonTypesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pokemon?: boolean | Prisma.PokemonDefaultArgs<ExtArgs>
  type?: boolean | Prisma.TypesDefaultArgs<ExtArgs>
}
export type PokemonTypesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pokemon?: boolean | Prisma.PokemonDefaultArgs<ExtArgs>
  type?: boolean | Prisma.TypesDefaultArgs<ExtArgs>
}

export type $PokemonTypesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PokemonTypes"
  objects: {
    pokemon: Prisma.$PokemonPayload<ExtArgs>
    type: Prisma.$TypesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    pokemon_id: number
    type_id: number
    slot: number
  }, ExtArgs["result"]["pokemonTypes"]>
  composites: {}
}

export type PokemonTypesGetPayload<S extends boolean | null | undefined | PokemonTypesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload, S>

export type PokemonTypesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PokemonTypesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PokemonTypesCountAggregateInputType | true
  }

export interface PokemonTypesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PokemonTypes'], meta: { name: 'PokemonTypes' } }
  /**
   * Find zero or one PokemonTypes that matches the filter.
   * @param {PokemonTypesFindUniqueArgs} args - Arguments to find a PokemonTypes
   * @example
   * // Get one PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PokemonTypesFindUniqueArgs>(args: Prisma.SelectSubset<T, PokemonTypesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PokemonTypesClient<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PokemonTypes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PokemonTypesFindUniqueOrThrowArgs} args - Arguments to find a PokemonTypes
   * @example
   * // Get one PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PokemonTypesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PokemonTypesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PokemonTypesClient<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PokemonTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonTypesFindFirstArgs} args - Arguments to find a PokemonTypes
   * @example
   * // Get one PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PokemonTypesFindFirstArgs>(args?: Prisma.SelectSubset<T, PokemonTypesFindFirstArgs<ExtArgs>>): Prisma.Prisma__PokemonTypesClient<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PokemonTypes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonTypesFindFirstOrThrowArgs} args - Arguments to find a PokemonTypes
   * @example
   * // Get one PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PokemonTypesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PokemonTypesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PokemonTypesClient<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PokemonTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonTypesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.findMany()
   * 
   * // Get first 10 PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.findMany({ take: 10 })
   * 
   * // Only select the `pokemon_id`
   * const pokemonTypesWithPokemon_idOnly = await prisma.pokemonTypes.findMany({ select: { pokemon_id: true } })
   * 
   */
  findMany<T extends PokemonTypesFindManyArgs>(args?: Prisma.SelectSubset<T, PokemonTypesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PokemonTypes.
   * @param {PokemonTypesCreateArgs} args - Arguments to create a PokemonTypes.
   * @example
   * // Create one PokemonTypes
   * const PokemonTypes = await prisma.pokemonTypes.create({
   *   data: {
   *     // ... data to create a PokemonTypes
   *   }
   * })
   * 
   */
  create<T extends PokemonTypesCreateArgs>(args: Prisma.SelectSubset<T, PokemonTypesCreateArgs<ExtArgs>>): Prisma.Prisma__PokemonTypesClient<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PokemonTypes.
   * @param {PokemonTypesCreateManyArgs} args - Arguments to create many PokemonTypes.
   * @example
   * // Create many PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PokemonTypesCreateManyArgs>(args?: Prisma.SelectSubset<T, PokemonTypesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PokemonTypes and returns the data saved in the database.
   * @param {PokemonTypesCreateManyAndReturnArgs} args - Arguments to create many PokemonTypes.
   * @example
   * // Create many PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PokemonTypes and only return the `pokemon_id`
   * const pokemonTypesWithPokemon_idOnly = await prisma.pokemonTypes.createManyAndReturn({
   *   select: { pokemon_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PokemonTypesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PokemonTypesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PokemonTypes.
   * @param {PokemonTypesDeleteArgs} args - Arguments to delete one PokemonTypes.
   * @example
   * // Delete one PokemonTypes
   * const PokemonTypes = await prisma.pokemonTypes.delete({
   *   where: {
   *     // ... filter to delete one PokemonTypes
   *   }
   * })
   * 
   */
  delete<T extends PokemonTypesDeleteArgs>(args: Prisma.SelectSubset<T, PokemonTypesDeleteArgs<ExtArgs>>): Prisma.Prisma__PokemonTypesClient<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PokemonTypes.
   * @param {PokemonTypesUpdateArgs} args - Arguments to update one PokemonTypes.
   * @example
   * // Update one PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PokemonTypesUpdateArgs>(args: Prisma.SelectSubset<T, PokemonTypesUpdateArgs<ExtArgs>>): Prisma.Prisma__PokemonTypesClient<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PokemonTypes.
   * @param {PokemonTypesDeleteManyArgs} args - Arguments to filter PokemonTypes to delete.
   * @example
   * // Delete a few PokemonTypes
   * const { count } = await prisma.pokemonTypes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PokemonTypesDeleteManyArgs>(args?: Prisma.SelectSubset<T, PokemonTypesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PokemonTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonTypesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PokemonTypesUpdateManyArgs>(args: Prisma.SelectSubset<T, PokemonTypesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PokemonTypes and returns the data updated in the database.
   * @param {PokemonTypesUpdateManyAndReturnArgs} args - Arguments to update many PokemonTypes.
   * @example
   * // Update many PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PokemonTypes and only return the `pokemon_id`
   * const pokemonTypesWithPokemon_idOnly = await prisma.pokemonTypes.updateManyAndReturn({
   *   select: { pokemon_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PokemonTypesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PokemonTypesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PokemonTypes.
   * @param {PokemonTypesUpsertArgs} args - Arguments to update or create a PokemonTypes.
   * @example
   * // Update or create a PokemonTypes
   * const pokemonTypes = await prisma.pokemonTypes.upsert({
   *   create: {
   *     // ... data to create a PokemonTypes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PokemonTypes we want to update
   *   }
   * })
   */
  upsert<T extends PokemonTypesUpsertArgs>(args: Prisma.SelectSubset<T, PokemonTypesUpsertArgs<ExtArgs>>): Prisma.Prisma__PokemonTypesClient<runtime.Types.Result.GetResult<Prisma.$PokemonTypesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PokemonTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonTypesCountArgs} args - Arguments to filter PokemonTypes to count.
   * @example
   * // Count the number of PokemonTypes
   * const count = await prisma.pokemonTypes.count({
   *   where: {
   *     // ... the filter for the PokemonTypes we want to count
   *   }
   * })
  **/
  count<T extends PokemonTypesCountArgs>(
    args?: Prisma.Subset<T, PokemonTypesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PokemonTypesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PokemonTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonTypesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PokemonTypesAggregateArgs>(args: Prisma.Subset<T, PokemonTypesAggregateArgs>): Prisma.PrismaPromise<GetPokemonTypesAggregateType<T>>

  /**
   * Group by PokemonTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonTypesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PokemonTypesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PokemonTypesGroupByArgs['orderBy'] }
      : { orderBy?: PokemonTypesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PokemonTypesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPokemonTypesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PokemonTypes model
 */
readonly fields: PokemonTypesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PokemonTypes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PokemonTypesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pokemon<T extends Prisma.PokemonDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PokemonDefaultArgs<ExtArgs>>): Prisma.Prisma__PokemonClient<runtime.Types.Result.GetResult<Prisma.$PokemonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  type<T extends Prisma.TypesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TypesDefaultArgs<ExtArgs>>): Prisma.Prisma__TypesClient<runtime.Types.Result.GetResult<Prisma.$TypesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PokemonTypes model
 */
export interface PokemonTypesFieldRefs {
  readonly pokemon_id: Prisma.FieldRef<"PokemonTypes", 'Int'>
  readonly type_id: Prisma.FieldRef<"PokemonTypes", 'Int'>
  readonly slot: Prisma.FieldRef<"PokemonTypes", 'Int'>
}
    

// Custom InputTypes
/**
 * PokemonTypes findUnique
 */
export type PokemonTypesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
  /**
   * Filter, which PokemonTypes to fetch.
   */
  where: Prisma.PokemonTypesWhereUniqueInput
}

/**
 * PokemonTypes findUniqueOrThrow
 */
export type PokemonTypesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
  /**
   * Filter, which PokemonTypes to fetch.
   */
  where: Prisma.PokemonTypesWhereUniqueInput
}

/**
 * PokemonTypes findFirst
 */
export type PokemonTypesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
  /**
   * Filter, which PokemonTypes to fetch.
   */
  where?: Prisma.PokemonTypesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonTypes to fetch.
   */
  orderBy?: Prisma.PokemonTypesOrderByWithRelationInput | Prisma.PokemonTypesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PokemonTypes.
   */
  cursor?: Prisma.PokemonTypesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PokemonTypes.
   */
  distinct?: Prisma.PokemonTypesScalarFieldEnum | Prisma.PokemonTypesScalarFieldEnum[]
}

/**
 * PokemonTypes findFirstOrThrow
 */
export type PokemonTypesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
  /**
   * Filter, which PokemonTypes to fetch.
   */
  where?: Prisma.PokemonTypesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonTypes to fetch.
   */
  orderBy?: Prisma.PokemonTypesOrderByWithRelationInput | Prisma.PokemonTypesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PokemonTypes.
   */
  cursor?: Prisma.PokemonTypesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PokemonTypes.
   */
  distinct?: Prisma.PokemonTypesScalarFieldEnum | Prisma.PokemonTypesScalarFieldEnum[]
}

/**
 * PokemonTypes findMany
 */
export type PokemonTypesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
  /**
   * Filter, which PokemonTypes to fetch.
   */
  where?: Prisma.PokemonTypesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonTypes to fetch.
   */
  orderBy?: Prisma.PokemonTypesOrderByWithRelationInput | Prisma.PokemonTypesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PokemonTypes.
   */
  cursor?: Prisma.PokemonTypesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PokemonTypes.
   */
  distinct?: Prisma.PokemonTypesScalarFieldEnum | Prisma.PokemonTypesScalarFieldEnum[]
}

/**
 * PokemonTypes create
 */
export type PokemonTypesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
  /**
   * The data needed to create a PokemonTypes.
   */
  data: Prisma.XOR<Prisma.PokemonTypesCreateInput, Prisma.PokemonTypesUncheckedCreateInput>
}

/**
 * PokemonTypes createMany
 */
export type PokemonTypesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PokemonTypes.
   */
  data: Prisma.PokemonTypesCreateManyInput | Prisma.PokemonTypesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PokemonTypes createManyAndReturn
 */
export type PokemonTypesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * The data used to create many PokemonTypes.
   */
  data: Prisma.PokemonTypesCreateManyInput | Prisma.PokemonTypesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PokemonTypes update
 */
export type PokemonTypesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
  /**
   * The data needed to update a PokemonTypes.
   */
  data: Prisma.XOR<Prisma.PokemonTypesUpdateInput, Prisma.PokemonTypesUncheckedUpdateInput>
  /**
   * Choose, which PokemonTypes to update.
   */
  where: Prisma.PokemonTypesWhereUniqueInput
}

/**
 * PokemonTypes updateMany
 */
export type PokemonTypesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PokemonTypes.
   */
  data: Prisma.XOR<Prisma.PokemonTypesUpdateManyMutationInput, Prisma.PokemonTypesUncheckedUpdateManyInput>
  /**
   * Filter which PokemonTypes to update
   */
  where?: Prisma.PokemonTypesWhereInput
  /**
   * Limit how many PokemonTypes to update.
   */
  limit?: number
}

/**
 * PokemonTypes updateManyAndReturn
 */
export type PokemonTypesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * The data used to update PokemonTypes.
   */
  data: Prisma.XOR<Prisma.PokemonTypesUpdateManyMutationInput, Prisma.PokemonTypesUncheckedUpdateManyInput>
  /**
   * Filter which PokemonTypes to update
   */
  where?: Prisma.PokemonTypesWhereInput
  /**
   * Limit how many PokemonTypes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PokemonTypes upsert
 */
export type PokemonTypesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
  /**
   * The filter to search for the PokemonTypes to update in case it exists.
   */
  where: Prisma.PokemonTypesWhereUniqueInput
  /**
   * In case the PokemonTypes found by the `where` argument doesn't exist, create a new PokemonTypes with this data.
   */
  create: Prisma.XOR<Prisma.PokemonTypesCreateInput, Prisma.PokemonTypesUncheckedCreateInput>
  /**
   * In case the PokemonTypes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PokemonTypesUpdateInput, Prisma.PokemonTypesUncheckedUpdateInput>
}

/**
 * PokemonTypes delete
 */
export type PokemonTypesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
  /**
   * Filter which PokemonTypes to delete.
   */
  where: Prisma.PokemonTypesWhereUniqueInput
}

/**
 * PokemonTypes deleteMany
 */
export type PokemonTypesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PokemonTypes to delete
   */
  where?: Prisma.PokemonTypesWhereInput
  /**
   * Limit how many PokemonTypes to delete.
   */
  limit?: number
}

/**
 * PokemonTypes without action
 */
export type PokemonTypesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonTypes
   */
  select?: Prisma.PokemonTypesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonTypes
   */
  omit?: Prisma.PokemonTypesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonTypesInclude<ExtArgs> | null
}
