
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PokemonColors` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PokemonColors
 * @@TypeGraphQL.type(name: "PokemonColor")
 */
export type PokemonColorsModel = runtime.Types.Result.DefaultSelection<Prisma.$PokemonColorsPayload>

export type AggregatePokemonColors = {
  _count: PokemonColorsCountAggregateOutputType | null
  _avg: PokemonColorsAvgAggregateOutputType | null
  _sum: PokemonColorsSumAggregateOutputType | null
  _min: PokemonColorsMinAggregateOutputType | null
  _max: PokemonColorsMaxAggregateOutputType | null
}

export type PokemonColorsAvgAggregateOutputType = {
  id: number | null
}

export type PokemonColorsSumAggregateOutputType = {
  id: number | null
}

export type PokemonColorsMinAggregateOutputType = {
  id: number | null
  identifier: string | null
}

export type PokemonColorsMaxAggregateOutputType = {
  id: number | null
  identifier: string | null
}

export type PokemonColorsCountAggregateOutputType = {
  id: number
  identifier: number
  _all: number
}


export type PokemonColorsAvgAggregateInputType = {
  id?: true
}

export type PokemonColorsSumAggregateInputType = {
  id?: true
}

export type PokemonColorsMinAggregateInputType = {
  id?: true
  identifier?: true
}

export type PokemonColorsMaxAggregateInputType = {
  id?: true
  identifier?: true
}

export type PokemonColorsCountAggregateInputType = {
  id?: true
  identifier?: true
  _all?: true
}

export type PokemonColorsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PokemonColors to aggregate.
   */
  where?: Prisma.PokemonColorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonColors to fetch.
   */
  orderBy?: Prisma.PokemonColorsOrderByWithRelationInput | Prisma.PokemonColorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PokemonColorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonColors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonColors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PokemonColors
  **/
  _count?: true | PokemonColorsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PokemonColorsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PokemonColorsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PokemonColorsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PokemonColorsMaxAggregateInputType
}

export type GetPokemonColorsAggregateType<T extends PokemonColorsAggregateArgs> = {
      [P in keyof T & keyof AggregatePokemonColors]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePokemonColors[P]>
    : Prisma.GetScalarType<T[P], AggregatePokemonColors[P]>
}




export type PokemonColorsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PokemonColorsWhereInput
  orderBy?: Prisma.PokemonColorsOrderByWithAggregationInput | Prisma.PokemonColorsOrderByWithAggregationInput[]
  by: Prisma.PokemonColorsScalarFieldEnum[] | Prisma.PokemonColorsScalarFieldEnum
  having?: Prisma.PokemonColorsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PokemonColorsCountAggregateInputType | true
  _avg?: PokemonColorsAvgAggregateInputType
  _sum?: PokemonColorsSumAggregateInputType
  _min?: PokemonColorsMinAggregateInputType
  _max?: PokemonColorsMaxAggregateInputType
}

export type PokemonColorsGroupByOutputType = {
  id: number
  identifier: string
  _count: PokemonColorsCountAggregateOutputType | null
  _avg: PokemonColorsAvgAggregateOutputType | null
  _sum: PokemonColorsSumAggregateOutputType | null
  _min: PokemonColorsMinAggregateOutputType | null
  _max: PokemonColorsMaxAggregateOutputType | null
}

export type GetPokemonColorsGroupByPayload<T extends PokemonColorsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PokemonColorsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PokemonColorsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PokemonColorsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PokemonColorsGroupByOutputType[P]>
      }
    >
  >



export type PokemonColorsWhereInput = {
  AND?: Prisma.PokemonColorsWhereInput | Prisma.PokemonColorsWhereInput[]
  OR?: Prisma.PokemonColorsWhereInput[]
  NOT?: Prisma.PokemonColorsWhereInput | Prisma.PokemonColorsWhereInput[]
  id?: Prisma.IntFilter<"PokemonColors"> | number
  identifier?: Prisma.StringFilter<"PokemonColors"> | string
  species?: Prisma.PokemonSpeciesListRelationFilter
}

export type PokemonColorsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  species?: Prisma.PokemonSpeciesOrderByRelationAggregateInput
}

export type PokemonColorsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.PokemonColorsWhereInput | Prisma.PokemonColorsWhereInput[]
  OR?: Prisma.PokemonColorsWhereInput[]
  NOT?: Prisma.PokemonColorsWhereInput | Prisma.PokemonColorsWhereInput[]
  identifier?: Prisma.StringFilter<"PokemonColors"> | string
  species?: Prisma.PokemonSpeciesListRelationFilter
}, "id">

export type PokemonColorsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
  _count?: Prisma.PokemonColorsCountOrderByAggregateInput
  _avg?: Prisma.PokemonColorsAvgOrderByAggregateInput
  _max?: Prisma.PokemonColorsMaxOrderByAggregateInput
  _min?: Prisma.PokemonColorsMinOrderByAggregateInput
  _sum?: Prisma.PokemonColorsSumOrderByAggregateInput
}

export type PokemonColorsScalarWhereWithAggregatesInput = {
  AND?: Prisma.PokemonColorsScalarWhereWithAggregatesInput | Prisma.PokemonColorsScalarWhereWithAggregatesInput[]
  OR?: Prisma.PokemonColorsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PokemonColorsScalarWhereWithAggregatesInput | Prisma.PokemonColorsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PokemonColors"> | number
  identifier?: Prisma.StringWithAggregatesFilter<"PokemonColors"> | string
}

export type PokemonColorsCreateInput = {
  id: number
  identifier: string
  species?: Prisma.PokemonSpeciesCreateNestedManyWithoutColorInput
}

export type PokemonColorsUncheckedCreateInput = {
  id: number
  identifier: string
  species?: Prisma.PokemonSpeciesUncheckedCreateNestedManyWithoutColorInput
}

export type PokemonColorsUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  species?: Prisma.PokemonSpeciesUpdateManyWithoutColorNestedInput
}

export type PokemonColorsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  species?: Prisma.PokemonSpeciesUncheckedUpdateManyWithoutColorNestedInput
}

export type PokemonColorsCreateManyInput = {
  id: number
  identifier: string
}

export type PokemonColorsUpdateManyMutationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PokemonColorsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PokemonColorsScalarRelationFilter = {
  is?: Prisma.PokemonColorsWhereInput
  isNot?: Prisma.PokemonColorsWhereInput
}

export type PokemonColorsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
}

export type PokemonColorsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PokemonColorsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
}

export type PokemonColorsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  identifier?: Prisma.SortOrder
}

export type PokemonColorsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PokemonColorsCreateNestedOneWithoutSpeciesInput = {
  create?: Prisma.XOR<Prisma.PokemonColorsCreateWithoutSpeciesInput, Prisma.PokemonColorsUncheckedCreateWithoutSpeciesInput>
  connectOrCreate?: Prisma.PokemonColorsCreateOrConnectWithoutSpeciesInput
  connect?: Prisma.PokemonColorsWhereUniqueInput
}

export type PokemonColorsUpdateOneRequiredWithoutSpeciesNestedInput = {
  create?: Prisma.XOR<Prisma.PokemonColorsCreateWithoutSpeciesInput, Prisma.PokemonColorsUncheckedCreateWithoutSpeciesInput>
  connectOrCreate?: Prisma.PokemonColorsCreateOrConnectWithoutSpeciesInput
  upsert?: Prisma.PokemonColorsUpsertWithoutSpeciesInput
  connect?: Prisma.PokemonColorsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PokemonColorsUpdateToOneWithWhereWithoutSpeciesInput, Prisma.PokemonColorsUpdateWithoutSpeciesInput>, Prisma.PokemonColorsUncheckedUpdateWithoutSpeciesInput>
}

export type PokemonColorsCreateWithoutSpeciesInput = {
  id: number
  identifier: string
}

export type PokemonColorsUncheckedCreateWithoutSpeciesInput = {
  id: number
  identifier: string
}

export type PokemonColorsCreateOrConnectWithoutSpeciesInput = {
  where: Prisma.PokemonColorsWhereUniqueInput
  create: Prisma.XOR<Prisma.PokemonColorsCreateWithoutSpeciesInput, Prisma.PokemonColorsUncheckedCreateWithoutSpeciesInput>
}

export type PokemonColorsUpsertWithoutSpeciesInput = {
  update: Prisma.XOR<Prisma.PokemonColorsUpdateWithoutSpeciesInput, Prisma.PokemonColorsUncheckedUpdateWithoutSpeciesInput>
  create: Prisma.XOR<Prisma.PokemonColorsCreateWithoutSpeciesInput, Prisma.PokemonColorsUncheckedCreateWithoutSpeciesInput>
  where?: Prisma.PokemonColorsWhereInput
}

export type PokemonColorsUpdateToOneWithWhereWithoutSpeciesInput = {
  where?: Prisma.PokemonColorsWhereInput
  data: Prisma.XOR<Prisma.PokemonColorsUpdateWithoutSpeciesInput, Prisma.PokemonColorsUncheckedUpdateWithoutSpeciesInput>
}

export type PokemonColorsUpdateWithoutSpeciesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PokemonColorsUncheckedUpdateWithoutSpeciesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type PokemonColorsCountOutputType
 */

export type PokemonColorsCountOutputType = {
  species: number
}

export type PokemonColorsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  species?: boolean | PokemonColorsCountOutputTypeCountSpeciesArgs
}

/**
 * PokemonColorsCountOutputType without action
 */
export type PokemonColorsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColorsCountOutputType
   */
  select?: Prisma.PokemonColorsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PokemonColorsCountOutputType without action
 */
export type PokemonColorsCountOutputTypeCountSpeciesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PokemonSpeciesWhereInput
}


export type PokemonColorsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
  species?: boolean | Prisma.PokemonColors$speciesArgs<ExtArgs>
  _count?: boolean | Prisma.PokemonColorsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pokemonColors"]>

export type PokemonColorsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
}, ExtArgs["result"]["pokemonColors"]>

export type PokemonColorsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  identifier?: boolean
}, ExtArgs["result"]["pokemonColors"]>

export type PokemonColorsSelectScalar = {
  id?: boolean
  identifier?: boolean
}

export type PokemonColorsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "identifier", ExtArgs["result"]["pokemonColors"]>
export type PokemonColorsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  species?: boolean | Prisma.PokemonColors$speciesArgs<ExtArgs>
  _count?: boolean | Prisma.PokemonColorsCountOutputTypeDefaultArgs<ExtArgs>
}
export type PokemonColorsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PokemonColorsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PokemonColorsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PokemonColors"
  objects: {
    species: Prisma.$PokemonSpeciesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    identifier: string
  }, ExtArgs["result"]["pokemonColors"]>
  composites: {}
}

export type PokemonColorsGetPayload<S extends boolean | null | undefined | PokemonColorsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload, S>

export type PokemonColorsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PokemonColorsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PokemonColorsCountAggregateInputType | true
  }

export interface PokemonColorsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PokemonColors'], meta: { name: 'PokemonColors' } }
  /**
   * Find zero or one PokemonColors that matches the filter.
   * @param {PokemonColorsFindUniqueArgs} args - Arguments to find a PokemonColors
   * @example
   * // Get one PokemonColors
   * const pokemonColors = await prisma.pokemonColors.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PokemonColorsFindUniqueArgs>(args: Prisma.SelectSubset<T, PokemonColorsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PokemonColorsClient<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PokemonColors that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PokemonColorsFindUniqueOrThrowArgs} args - Arguments to find a PokemonColors
   * @example
   * // Get one PokemonColors
   * const pokemonColors = await prisma.pokemonColors.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PokemonColorsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PokemonColorsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PokemonColorsClient<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PokemonColors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonColorsFindFirstArgs} args - Arguments to find a PokemonColors
   * @example
   * // Get one PokemonColors
   * const pokemonColors = await prisma.pokemonColors.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PokemonColorsFindFirstArgs>(args?: Prisma.SelectSubset<T, PokemonColorsFindFirstArgs<ExtArgs>>): Prisma.Prisma__PokemonColorsClient<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PokemonColors that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonColorsFindFirstOrThrowArgs} args - Arguments to find a PokemonColors
   * @example
   * // Get one PokemonColors
   * const pokemonColors = await prisma.pokemonColors.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PokemonColorsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PokemonColorsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PokemonColorsClient<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PokemonColors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonColorsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PokemonColors
   * const pokemonColors = await prisma.pokemonColors.findMany()
   * 
   * // Get first 10 PokemonColors
   * const pokemonColors = await prisma.pokemonColors.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pokemonColorsWithIdOnly = await prisma.pokemonColors.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PokemonColorsFindManyArgs>(args?: Prisma.SelectSubset<T, PokemonColorsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PokemonColors.
   * @param {PokemonColorsCreateArgs} args - Arguments to create a PokemonColors.
   * @example
   * // Create one PokemonColors
   * const PokemonColors = await prisma.pokemonColors.create({
   *   data: {
   *     // ... data to create a PokemonColors
   *   }
   * })
   * 
   */
  create<T extends PokemonColorsCreateArgs>(args: Prisma.SelectSubset<T, PokemonColorsCreateArgs<ExtArgs>>): Prisma.Prisma__PokemonColorsClient<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PokemonColors.
   * @param {PokemonColorsCreateManyArgs} args - Arguments to create many PokemonColors.
   * @example
   * // Create many PokemonColors
   * const pokemonColors = await prisma.pokemonColors.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PokemonColorsCreateManyArgs>(args?: Prisma.SelectSubset<T, PokemonColorsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PokemonColors and returns the data saved in the database.
   * @param {PokemonColorsCreateManyAndReturnArgs} args - Arguments to create many PokemonColors.
   * @example
   * // Create many PokemonColors
   * const pokemonColors = await prisma.pokemonColors.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PokemonColors and only return the `id`
   * const pokemonColorsWithIdOnly = await prisma.pokemonColors.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PokemonColorsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PokemonColorsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PokemonColors.
   * @param {PokemonColorsDeleteArgs} args - Arguments to delete one PokemonColors.
   * @example
   * // Delete one PokemonColors
   * const PokemonColors = await prisma.pokemonColors.delete({
   *   where: {
   *     // ... filter to delete one PokemonColors
   *   }
   * })
   * 
   */
  delete<T extends PokemonColorsDeleteArgs>(args: Prisma.SelectSubset<T, PokemonColorsDeleteArgs<ExtArgs>>): Prisma.Prisma__PokemonColorsClient<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PokemonColors.
   * @param {PokemonColorsUpdateArgs} args - Arguments to update one PokemonColors.
   * @example
   * // Update one PokemonColors
   * const pokemonColors = await prisma.pokemonColors.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PokemonColorsUpdateArgs>(args: Prisma.SelectSubset<T, PokemonColorsUpdateArgs<ExtArgs>>): Prisma.Prisma__PokemonColorsClient<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PokemonColors.
   * @param {PokemonColorsDeleteManyArgs} args - Arguments to filter PokemonColors to delete.
   * @example
   * // Delete a few PokemonColors
   * const { count } = await prisma.pokemonColors.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PokemonColorsDeleteManyArgs>(args?: Prisma.SelectSubset<T, PokemonColorsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PokemonColors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonColorsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PokemonColors
   * const pokemonColors = await prisma.pokemonColors.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PokemonColorsUpdateManyArgs>(args: Prisma.SelectSubset<T, PokemonColorsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PokemonColors and returns the data updated in the database.
   * @param {PokemonColorsUpdateManyAndReturnArgs} args - Arguments to update many PokemonColors.
   * @example
   * // Update many PokemonColors
   * const pokemonColors = await prisma.pokemonColors.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PokemonColors and only return the `id`
   * const pokemonColorsWithIdOnly = await prisma.pokemonColors.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PokemonColorsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PokemonColorsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PokemonColors.
   * @param {PokemonColorsUpsertArgs} args - Arguments to update or create a PokemonColors.
   * @example
   * // Update or create a PokemonColors
   * const pokemonColors = await prisma.pokemonColors.upsert({
   *   create: {
   *     // ... data to create a PokemonColors
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PokemonColors we want to update
   *   }
   * })
   */
  upsert<T extends PokemonColorsUpsertArgs>(args: Prisma.SelectSubset<T, PokemonColorsUpsertArgs<ExtArgs>>): Prisma.Prisma__PokemonColorsClient<runtime.Types.Result.GetResult<Prisma.$PokemonColorsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PokemonColors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonColorsCountArgs} args - Arguments to filter PokemonColors to count.
   * @example
   * // Count the number of PokemonColors
   * const count = await prisma.pokemonColors.count({
   *   where: {
   *     // ... the filter for the PokemonColors we want to count
   *   }
   * })
  **/
  count<T extends PokemonColorsCountArgs>(
    args?: Prisma.Subset<T, PokemonColorsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PokemonColorsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PokemonColors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonColorsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PokemonColorsAggregateArgs>(args: Prisma.Subset<T, PokemonColorsAggregateArgs>): Prisma.PrismaPromise<GetPokemonColorsAggregateType<T>>

  /**
   * Group by PokemonColors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PokemonColorsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PokemonColorsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PokemonColorsGroupByArgs['orderBy'] }
      : { orderBy?: PokemonColorsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PokemonColorsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPokemonColorsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PokemonColors model
 */
readonly fields: PokemonColorsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PokemonColors.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PokemonColorsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  species<T extends Prisma.PokemonColors$speciesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PokemonColors$speciesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PokemonSpeciesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PokemonColors model
 */
export interface PokemonColorsFieldRefs {
  readonly id: Prisma.FieldRef<"PokemonColors", 'Int'>
  readonly identifier: Prisma.FieldRef<"PokemonColors", 'String'>
}
    

// Custom InputTypes
/**
 * PokemonColors findUnique
 */
export type PokemonColorsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
  /**
   * Filter, which PokemonColors to fetch.
   */
  where: Prisma.PokemonColorsWhereUniqueInput
}

/**
 * PokemonColors findUniqueOrThrow
 */
export type PokemonColorsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
  /**
   * Filter, which PokemonColors to fetch.
   */
  where: Prisma.PokemonColorsWhereUniqueInput
}

/**
 * PokemonColors findFirst
 */
export type PokemonColorsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
  /**
   * Filter, which PokemonColors to fetch.
   */
  where?: Prisma.PokemonColorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonColors to fetch.
   */
  orderBy?: Prisma.PokemonColorsOrderByWithRelationInput | Prisma.PokemonColorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PokemonColors.
   */
  cursor?: Prisma.PokemonColorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonColors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonColors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PokemonColors.
   */
  distinct?: Prisma.PokemonColorsScalarFieldEnum | Prisma.PokemonColorsScalarFieldEnum[]
}

/**
 * PokemonColors findFirstOrThrow
 */
export type PokemonColorsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
  /**
   * Filter, which PokemonColors to fetch.
   */
  where?: Prisma.PokemonColorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonColors to fetch.
   */
  orderBy?: Prisma.PokemonColorsOrderByWithRelationInput | Prisma.PokemonColorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PokemonColors.
   */
  cursor?: Prisma.PokemonColorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonColors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonColors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PokemonColors.
   */
  distinct?: Prisma.PokemonColorsScalarFieldEnum | Prisma.PokemonColorsScalarFieldEnum[]
}

/**
 * PokemonColors findMany
 */
export type PokemonColorsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
  /**
   * Filter, which PokemonColors to fetch.
   */
  where?: Prisma.PokemonColorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PokemonColors to fetch.
   */
  orderBy?: Prisma.PokemonColorsOrderByWithRelationInput | Prisma.PokemonColorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PokemonColors.
   */
  cursor?: Prisma.PokemonColorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PokemonColors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PokemonColors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PokemonColors.
   */
  distinct?: Prisma.PokemonColorsScalarFieldEnum | Prisma.PokemonColorsScalarFieldEnum[]
}

/**
 * PokemonColors create
 */
export type PokemonColorsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
  /**
   * The data needed to create a PokemonColors.
   */
  data: Prisma.XOR<Prisma.PokemonColorsCreateInput, Prisma.PokemonColorsUncheckedCreateInput>
}

/**
 * PokemonColors createMany
 */
export type PokemonColorsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PokemonColors.
   */
  data: Prisma.PokemonColorsCreateManyInput | Prisma.PokemonColorsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PokemonColors createManyAndReturn
 */
export type PokemonColorsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * The data used to create many PokemonColors.
   */
  data: Prisma.PokemonColorsCreateManyInput | Prisma.PokemonColorsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PokemonColors update
 */
export type PokemonColorsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
  /**
   * The data needed to update a PokemonColors.
   */
  data: Prisma.XOR<Prisma.PokemonColorsUpdateInput, Prisma.PokemonColorsUncheckedUpdateInput>
  /**
   * Choose, which PokemonColors to update.
   */
  where: Prisma.PokemonColorsWhereUniqueInput
}

/**
 * PokemonColors updateMany
 */
export type PokemonColorsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PokemonColors.
   */
  data: Prisma.XOR<Prisma.PokemonColorsUpdateManyMutationInput, Prisma.PokemonColorsUncheckedUpdateManyInput>
  /**
   * Filter which PokemonColors to update
   */
  where?: Prisma.PokemonColorsWhereInput
  /**
   * Limit how many PokemonColors to update.
   */
  limit?: number
}

/**
 * PokemonColors updateManyAndReturn
 */
export type PokemonColorsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * The data used to update PokemonColors.
   */
  data: Prisma.XOR<Prisma.PokemonColorsUpdateManyMutationInput, Prisma.PokemonColorsUncheckedUpdateManyInput>
  /**
   * Filter which PokemonColors to update
   */
  where?: Prisma.PokemonColorsWhereInput
  /**
   * Limit how many PokemonColors to update.
   */
  limit?: number
}

/**
 * PokemonColors upsert
 */
export type PokemonColorsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
  /**
   * The filter to search for the PokemonColors to update in case it exists.
   */
  where: Prisma.PokemonColorsWhereUniqueInput
  /**
   * In case the PokemonColors found by the `where` argument doesn't exist, create a new PokemonColors with this data.
   */
  create: Prisma.XOR<Prisma.PokemonColorsCreateInput, Prisma.PokemonColorsUncheckedCreateInput>
  /**
   * In case the PokemonColors was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PokemonColorsUpdateInput, Prisma.PokemonColorsUncheckedUpdateInput>
}

/**
 * PokemonColors delete
 */
export type PokemonColorsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
  /**
   * Filter which PokemonColors to delete.
   */
  where: Prisma.PokemonColorsWhereUniqueInput
}

/**
 * PokemonColors deleteMany
 */
export type PokemonColorsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PokemonColors to delete
   */
  where?: Prisma.PokemonColorsWhereInput
  /**
   * Limit how many PokemonColors to delete.
   */
  limit?: number
}

/**
 * PokemonColors.species
 */
export type PokemonColors$speciesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonSpecies
   */
  select?: Prisma.PokemonSpeciesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonSpecies
   */
  omit?: Prisma.PokemonSpeciesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonSpeciesInclude<ExtArgs> | null
  where?: Prisma.PokemonSpeciesWhereInput
  orderBy?: Prisma.PokemonSpeciesOrderByWithRelationInput | Prisma.PokemonSpeciesOrderByWithRelationInput[]
  cursor?: Prisma.PokemonSpeciesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PokemonSpeciesScalarFieldEnum | Prisma.PokemonSpeciesScalarFieldEnum[]
}

/**
 * PokemonColors without action
 */
export type PokemonColorsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PokemonColors
   */
  select?: Prisma.PokemonColorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PokemonColors
   */
  omit?: Prisma.PokemonColorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PokemonColorsInclude<ExtArgs> | null
}
