
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Pokemon: 'Pokemon',
  PokemonSpecies: 'PokemonSpecies',
  PokemonForms: 'PokemonForms',
  Moves: 'Moves',
  MoveTargets: 'MoveTargets',
  MoveDamageClasses: 'MoveDamageClasses',
  Types: 'Types',
  Abilities: 'Abilities',
  Items: 'Items',
  ItemCategories: 'ItemCategories',
  ItemPockets: 'ItemPockets',
  Stats: 'Stats',
  Generations: 'Generations',
  VersionGroups: 'VersionGroups',
  Versions: 'Versions',
  Regions: 'Regions',
  Locations: 'Locations',
  LocationAreas: 'LocationAreas',
  Pokedexes: 'Pokedexes',
  EvolutionChains: 'EvolutionChains',
  EvolutionTriggers: 'EvolutionTriggers',
  PokemonEvolution: 'PokemonEvolution',
  GrowthRates: 'GrowthRates',
  Experience: 'Experience',
  Genders: 'Genders',
  Languages: 'Languages',
  EggGroups: 'EggGroups',
  Natures: 'Natures',
  ContestTypes: 'ContestTypes',
  ContestEffects: 'ContestEffects',
  SuperContestEffects: 'SuperContestEffects',
  Machines: 'Machines',
  EncounterMethods: 'EncounterMethods',
  EncounterSlots: 'EncounterSlots',
  Encounters: 'Encounters',
  EncounterConditions: 'EncounterConditions',
  EncounterConditionValues: 'EncounterConditionValues',
  EncounterConditionValueMap: 'EncounterConditionValueMap',
  MoveMetaCategories: 'MoveMetaCategories',
  MoveMetaAilments: 'MoveMetaAilments',
  MoveMeta: 'MoveMeta',
  MoveMetaStatChanges: 'MoveMetaStatChanges',
  MoveFlags: 'MoveFlags',
  MoveFlagMap: 'MoveFlagMap',
  MoveBattleStyles: 'MoveBattleStyles',
  ItemFlags: 'ItemFlags',
  ItemFlagMap: 'ItemFlagMap',
  ItemFlingEffects: 'ItemFlingEffects',
  Berries: 'Berries',
  BerryFirmness: 'BerryFirmness',
  BerryFlavors: 'BerryFlavors',
  Characteristics: 'Characteristics',
  ContestCombos: 'ContestCombos',
  SuperContestCombos: 'SuperContestCombos',
  PokemonMoveMethods: 'PokemonMoveMethods',
  VersionGroupPokemonMoveMethods: 'VersionGroupPokemonMoveMethods',
  PokemonShapes: 'PokemonShapes',
  PokemonColors: 'PokemonColors',
  PokemonHabitats: 'PokemonHabitats',
  TypeEfficacy: 'TypeEfficacy',
  VersionGroupRegions: 'VersionGroupRegions',
  PokedexVersionGroups: 'PokedexVersionGroups',
  PokemonAbilities: 'PokemonAbilities',
  PokemonMoves: 'PokemonMoves',
  PokemonStats: 'PokemonStats',
  PokemonTypes: 'PokemonTypes',
  PokemonEggGroups: 'PokemonEggGroups',
  PokemonItems: 'PokemonItems',
  PokemonGameIndices: 'PokemonGameIndices',
  PokemonDexNumbers: 'PokemonDexNumbers',
  PokemonFormGenerations: 'PokemonFormGenerations',
  PokemonFormTypes: 'PokemonFormTypes',
  TypeGameIndices: 'TypeGameIndices',
  ItemGameIndices: 'ItemGameIndices',
  LocationGameIndices: 'LocationGameIndices',
  LocationAreaEncounterRates: 'LocationAreaEncounterRates',
  NatureBattleStylePreferences: 'NatureBattleStylePreferences'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const PokemonScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  species_id: 'species_id',
  height: 'height',
  weight: 'weight',
  base_experience: 'base_experience',
  order: 'order',
  is_default: 'is_default'
} as const

export type PokemonScalarFieldEnum = (typeof PokemonScalarFieldEnum)[keyof typeof PokemonScalarFieldEnum]


export const PokemonSpeciesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  generation_id: 'generation_id',
  evolves_from_species_id: 'evolves_from_species_id',
  evolution_chain_id: 'evolution_chain_id',
  color_id: 'color_id',
  shape_id: 'shape_id',
  habitat_id: 'habitat_id',
  gender_rate: 'gender_rate',
  capture_rate: 'capture_rate',
  base_happiness: 'base_happiness',
  is_baby: 'is_baby',
  hatch_counter: 'hatch_counter',
  has_gender_differences: 'has_gender_differences',
  growth_rate_id: 'growth_rate_id',
  forms_switchable: 'forms_switchable',
  is_legendary: 'is_legendary',
  is_mythical: 'is_mythical',
  order: 'order',
  conquest_order: 'conquest_order'
} as const

export type PokemonSpeciesScalarFieldEnum = (typeof PokemonSpeciesScalarFieldEnum)[keyof typeof PokemonSpeciesScalarFieldEnum]


export const PokemonFormsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  form_identifier: 'form_identifier',
  pokemon_id: 'pokemon_id',
  introduced_in_version_group_id: 'introduced_in_version_group_id',
  is_default: 'is_default',
  is_battle_only: 'is_battle_only',
  is_mega: 'is_mega',
  form_order: 'form_order',
  order: 'order'
} as const

export type PokemonFormsScalarFieldEnum = (typeof PokemonFormsScalarFieldEnum)[keyof typeof PokemonFormsScalarFieldEnum]


export const MovesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  generation_id: 'generation_id',
  type_id: 'type_id',
  power: 'power',
  pp: 'pp',
  accuracy: 'accuracy',
  priority: 'priority',
  target_id: 'target_id',
  damage_class_id: 'damage_class_id',
  effect_id: 'effect_id',
  effect_chance: 'effect_chance',
  contest_type_id: 'contest_type_id',
  contest_effect_id: 'contest_effect_id',
  super_contest_effect_id: 'super_contest_effect_id'
} as const

export type MovesScalarFieldEnum = (typeof MovesScalarFieldEnum)[keyof typeof MovesScalarFieldEnum]


export const MoveTargetsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type MoveTargetsScalarFieldEnum = (typeof MoveTargetsScalarFieldEnum)[keyof typeof MoveTargetsScalarFieldEnum]


export const MoveDamageClassesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type MoveDamageClassesScalarFieldEnum = (typeof MoveDamageClassesScalarFieldEnum)[keyof typeof MoveDamageClassesScalarFieldEnum]


export const TypesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  generation_id: 'generation_id',
  damage_class_id: 'damage_class_id'
} as const

export type TypesScalarFieldEnum = (typeof TypesScalarFieldEnum)[keyof typeof TypesScalarFieldEnum]


export const AbilitiesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  generation_id: 'generation_id',
  is_main_series: 'is_main_series'
} as const

export type AbilitiesScalarFieldEnum = (typeof AbilitiesScalarFieldEnum)[keyof typeof AbilitiesScalarFieldEnum]


export const ItemsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  category_id: 'category_id',
  cost: 'cost',
  fling_power: 'fling_power',
  fling_effect_id: 'fling_effect_id'
} as const

export type ItemsScalarFieldEnum = (typeof ItemsScalarFieldEnum)[keyof typeof ItemsScalarFieldEnum]


export const ItemCategoriesScalarFieldEnum = {
  id: 'id',
  pocket_id: 'pocket_id',
  identifier: 'identifier'
} as const

export type ItemCategoriesScalarFieldEnum = (typeof ItemCategoriesScalarFieldEnum)[keyof typeof ItemCategoriesScalarFieldEnum]


export const ItemPocketsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type ItemPocketsScalarFieldEnum = (typeof ItemPocketsScalarFieldEnum)[keyof typeof ItemPocketsScalarFieldEnum]


export const StatsScalarFieldEnum = {
  id: 'id',
  damage_class_id: 'damage_class_id',
  identifier: 'identifier',
  is_battle_only: 'is_battle_only',
  game_index: 'game_index'
} as const

export type StatsScalarFieldEnum = (typeof StatsScalarFieldEnum)[keyof typeof StatsScalarFieldEnum]


export const GenerationsScalarFieldEnum = {
  id: 'id',
  main_region_id: 'main_region_id',
  identifier: 'identifier'
} as const

export type GenerationsScalarFieldEnum = (typeof GenerationsScalarFieldEnum)[keyof typeof GenerationsScalarFieldEnum]


export const VersionGroupsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  generation_id: 'generation_id',
  order: 'order'
} as const

export type VersionGroupsScalarFieldEnum = (typeof VersionGroupsScalarFieldEnum)[keyof typeof VersionGroupsScalarFieldEnum]


export const VersionsScalarFieldEnum = {
  id: 'id',
  version_group_id: 'version_group_id',
  identifier: 'identifier'
} as const

export type VersionsScalarFieldEnum = (typeof VersionsScalarFieldEnum)[keyof typeof VersionsScalarFieldEnum]


export const RegionsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type RegionsScalarFieldEnum = (typeof RegionsScalarFieldEnum)[keyof typeof RegionsScalarFieldEnum]


export const LocationsScalarFieldEnum = {
  id: 'id',
  region_id: 'region_id',
  identifier: 'identifier'
} as const

export type LocationsScalarFieldEnum = (typeof LocationsScalarFieldEnum)[keyof typeof LocationsScalarFieldEnum]


export const LocationAreasScalarFieldEnum = {
  id: 'id',
  location_id: 'location_id',
  game_index: 'game_index',
  identifier: 'identifier'
} as const

export type LocationAreasScalarFieldEnum = (typeof LocationAreasScalarFieldEnum)[keyof typeof LocationAreasScalarFieldEnum]


export const PokedexesScalarFieldEnum = {
  id: 'id',
  region_id: 'region_id',
  identifier: 'identifier',
  is_main_series: 'is_main_series'
} as const

export type PokedexesScalarFieldEnum = (typeof PokedexesScalarFieldEnum)[keyof typeof PokedexesScalarFieldEnum]


export const EvolutionChainsScalarFieldEnum = {
  id: 'id',
  baby_trigger_item_id: 'baby_trigger_item_id'
} as const

export type EvolutionChainsScalarFieldEnum = (typeof EvolutionChainsScalarFieldEnum)[keyof typeof EvolutionChainsScalarFieldEnum]


export const EvolutionTriggersScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type EvolutionTriggersScalarFieldEnum = (typeof EvolutionTriggersScalarFieldEnum)[keyof typeof EvolutionTriggersScalarFieldEnum]


export const PokemonEvolutionScalarFieldEnum = {
  id: 'id',
  evolved_species_id: 'evolved_species_id',
  evolution_trigger_id: 'evolution_trigger_id',
  trigger_item_id: 'trigger_item_id',
  minimum_level: 'minimum_level',
  gender_id: 'gender_id',
  location_id: 'location_id',
  held_item_id: 'held_item_id',
  time_of_day: 'time_of_day',
  known_move_id: 'known_move_id',
  known_move_type_id: 'known_move_type_id',
  minimum_happiness: 'minimum_happiness',
  minimum_beauty: 'minimum_beauty',
  minimum_affection: 'minimum_affection',
  relative_physical_stats: 'relative_physical_stats',
  party_species_id: 'party_species_id',
  party_type_id: 'party_type_id',
  trade_species_id: 'trade_species_id',
  needs_overworld_rain: 'needs_overworld_rain',
  turn_upside_down: 'turn_upside_down'
} as const

export type PokemonEvolutionScalarFieldEnum = (typeof PokemonEvolutionScalarFieldEnum)[keyof typeof PokemonEvolutionScalarFieldEnum]


export const GrowthRatesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  formula: 'formula'
} as const

export type GrowthRatesScalarFieldEnum = (typeof GrowthRatesScalarFieldEnum)[keyof typeof GrowthRatesScalarFieldEnum]


export const ExperienceScalarFieldEnum = {
  growth_rate_id: 'growth_rate_id',
  level: 'level',
  experience: 'experience'
} as const

export type ExperienceScalarFieldEnum = (typeof ExperienceScalarFieldEnum)[keyof typeof ExperienceScalarFieldEnum]


export const GendersScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type GendersScalarFieldEnum = (typeof GendersScalarFieldEnum)[keyof typeof GendersScalarFieldEnum]


export const LanguagesScalarFieldEnum = {
  id: 'id',
  iso639: 'iso639',
  iso3166: 'iso3166',
  identifier: 'identifier',
  official: 'official',
  order: 'order'
} as const

export type LanguagesScalarFieldEnum = (typeof LanguagesScalarFieldEnum)[keyof typeof LanguagesScalarFieldEnum]


export const EggGroupsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type EggGroupsScalarFieldEnum = (typeof EggGroupsScalarFieldEnum)[keyof typeof EggGroupsScalarFieldEnum]


export const NaturesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  decreased_stat_id: 'decreased_stat_id',
  increased_stat_id: 'increased_stat_id',
  hates_flavor_id: 'hates_flavor_id',
  likes_flavor_id: 'likes_flavor_id',
  game_index: 'game_index'
} as const

export type NaturesScalarFieldEnum = (typeof NaturesScalarFieldEnum)[keyof typeof NaturesScalarFieldEnum]


export const ContestTypesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type ContestTypesScalarFieldEnum = (typeof ContestTypesScalarFieldEnum)[keyof typeof ContestTypesScalarFieldEnum]


export const ContestEffectsScalarFieldEnum = {
  id: 'id',
  appeal: 'appeal',
  jam: 'jam'
} as const

export type ContestEffectsScalarFieldEnum = (typeof ContestEffectsScalarFieldEnum)[keyof typeof ContestEffectsScalarFieldEnum]


export const SuperContestEffectsScalarFieldEnum = {
  id: 'id',
  appeal: 'appeal'
} as const

export type SuperContestEffectsScalarFieldEnum = (typeof SuperContestEffectsScalarFieldEnum)[keyof typeof SuperContestEffectsScalarFieldEnum]


export const MachinesScalarFieldEnum = {
  machine_number: 'machine_number',
  version_group_id: 'version_group_id',
  item_id: 'item_id',
  move_id: 'move_id'
} as const

export type MachinesScalarFieldEnum = (typeof MachinesScalarFieldEnum)[keyof typeof MachinesScalarFieldEnum]


export const EncounterMethodsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  order: 'order'
} as const

export type EncounterMethodsScalarFieldEnum = (typeof EncounterMethodsScalarFieldEnum)[keyof typeof EncounterMethodsScalarFieldEnum]


export const EncounterSlotsScalarFieldEnum = {
  id: 'id',
  version_group_id: 'version_group_id',
  encounter_method_id: 'encounter_method_id',
  slot: 'slot',
  rarity: 'rarity'
} as const

export type EncounterSlotsScalarFieldEnum = (typeof EncounterSlotsScalarFieldEnum)[keyof typeof EncounterSlotsScalarFieldEnum]


export const EncountersScalarFieldEnum = {
  id: 'id',
  version_id: 'version_id',
  location_area_id: 'location_area_id',
  encounter_slot_id: 'encounter_slot_id',
  pokemon_id: 'pokemon_id',
  min_level: 'min_level',
  max_level: 'max_level'
} as const

export type EncountersScalarFieldEnum = (typeof EncountersScalarFieldEnum)[keyof typeof EncountersScalarFieldEnum]


export const EncounterConditionsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type EncounterConditionsScalarFieldEnum = (typeof EncounterConditionsScalarFieldEnum)[keyof typeof EncounterConditionsScalarFieldEnum]


export const EncounterConditionValuesScalarFieldEnum = {
  id: 'id',
  encounter_condition_id: 'encounter_condition_id',
  identifier: 'identifier',
  is_default: 'is_default'
} as const

export type EncounterConditionValuesScalarFieldEnum = (typeof EncounterConditionValuesScalarFieldEnum)[keyof typeof EncounterConditionValuesScalarFieldEnum]


export const EncounterConditionValueMapScalarFieldEnum = {
  encounter_id: 'encounter_id',
  encounter_condition_value_id: 'encounter_condition_value_id'
} as const

export type EncounterConditionValueMapScalarFieldEnum = (typeof EncounterConditionValueMapScalarFieldEnum)[keyof typeof EncounterConditionValueMapScalarFieldEnum]


export const MoveMetaCategoriesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type MoveMetaCategoriesScalarFieldEnum = (typeof MoveMetaCategoriesScalarFieldEnum)[keyof typeof MoveMetaCategoriesScalarFieldEnum]


export const MoveMetaAilmentsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type MoveMetaAilmentsScalarFieldEnum = (typeof MoveMetaAilmentsScalarFieldEnum)[keyof typeof MoveMetaAilmentsScalarFieldEnum]


export const MoveMetaScalarFieldEnum = {
  move_id: 'move_id',
  meta_category_id: 'meta_category_id',
  meta_ailment_id: 'meta_ailment_id',
  min_hits: 'min_hits',
  max_hits: 'max_hits',
  min_turns: 'min_turns',
  max_turns: 'max_turns',
  drain: 'drain',
  healing: 'healing',
  crit_rate: 'crit_rate',
  ailment_chance: 'ailment_chance',
  flinch_chance: 'flinch_chance',
  stat_chance: 'stat_chance'
} as const

export type MoveMetaScalarFieldEnum = (typeof MoveMetaScalarFieldEnum)[keyof typeof MoveMetaScalarFieldEnum]


export const MoveMetaStatChangesScalarFieldEnum = {
  move_id: 'move_id',
  stat_id: 'stat_id',
  change: 'change'
} as const

export type MoveMetaStatChangesScalarFieldEnum = (typeof MoveMetaStatChangesScalarFieldEnum)[keyof typeof MoveMetaStatChangesScalarFieldEnum]


export const MoveFlagsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type MoveFlagsScalarFieldEnum = (typeof MoveFlagsScalarFieldEnum)[keyof typeof MoveFlagsScalarFieldEnum]


export const MoveFlagMapScalarFieldEnum = {
  move_id: 'move_id',
  move_flag_id: 'move_flag_id'
} as const

export type MoveFlagMapScalarFieldEnum = (typeof MoveFlagMapScalarFieldEnum)[keyof typeof MoveFlagMapScalarFieldEnum]


export const MoveBattleStylesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type MoveBattleStylesScalarFieldEnum = (typeof MoveBattleStylesScalarFieldEnum)[keyof typeof MoveBattleStylesScalarFieldEnum]


export const ItemFlagsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type ItemFlagsScalarFieldEnum = (typeof ItemFlagsScalarFieldEnum)[keyof typeof ItemFlagsScalarFieldEnum]


export const ItemFlagMapScalarFieldEnum = {
  item_id: 'item_id',
  item_flag_id: 'item_flag_id'
} as const

export type ItemFlagMapScalarFieldEnum = (typeof ItemFlagMapScalarFieldEnum)[keyof typeof ItemFlagMapScalarFieldEnum]


export const ItemFlingEffectsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type ItemFlingEffectsScalarFieldEnum = (typeof ItemFlingEffectsScalarFieldEnum)[keyof typeof ItemFlingEffectsScalarFieldEnum]


export const BerriesScalarFieldEnum = {
  id: 'id',
  item_id: 'item_id',
  firmness_id: 'firmness_id',
  natural_gift_power: 'natural_gift_power',
  natural_gift_type_id: 'natural_gift_type_id',
  size: 'size',
  max_harvest: 'max_harvest',
  growth_time: 'growth_time',
  soil_dryness: 'soil_dryness',
  smoothness: 'smoothness'
} as const

export type BerriesScalarFieldEnum = (typeof BerriesScalarFieldEnum)[keyof typeof BerriesScalarFieldEnum]


export const BerryFirmnessScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type BerryFirmnessScalarFieldEnum = (typeof BerryFirmnessScalarFieldEnum)[keyof typeof BerryFirmnessScalarFieldEnum]


export const BerryFlavorsScalarFieldEnum = {
  berry_id: 'berry_id',
  contest_type_id: 'contest_type_id',
  flavor: 'flavor'
} as const

export type BerryFlavorsScalarFieldEnum = (typeof BerryFlavorsScalarFieldEnum)[keyof typeof BerryFlavorsScalarFieldEnum]


export const CharacteristicsScalarFieldEnum = {
  id: 'id',
  stat_id: 'stat_id',
  gene_mod_5: 'gene_mod_5'
} as const

export type CharacteristicsScalarFieldEnum = (typeof CharacteristicsScalarFieldEnum)[keyof typeof CharacteristicsScalarFieldEnum]


export const ContestCombosScalarFieldEnum = {
  first_move_id: 'first_move_id',
  second_move_id: 'second_move_id'
} as const

export type ContestCombosScalarFieldEnum = (typeof ContestCombosScalarFieldEnum)[keyof typeof ContestCombosScalarFieldEnum]


export const SuperContestCombosScalarFieldEnum = {
  first_move_id: 'first_move_id',
  second_move_id: 'second_move_id'
} as const

export type SuperContestCombosScalarFieldEnum = (typeof SuperContestCombosScalarFieldEnum)[keyof typeof SuperContestCombosScalarFieldEnum]


export const PokemonMoveMethodsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type PokemonMoveMethodsScalarFieldEnum = (typeof PokemonMoveMethodsScalarFieldEnum)[keyof typeof PokemonMoveMethodsScalarFieldEnum]


export const VersionGroupPokemonMoveMethodsScalarFieldEnum = {
  version_group_id: 'version_group_id',
  pokemon_move_method_id: 'pokemon_move_method_id'
} as const

export type VersionGroupPokemonMoveMethodsScalarFieldEnum = (typeof VersionGroupPokemonMoveMethodsScalarFieldEnum)[keyof typeof VersionGroupPokemonMoveMethodsScalarFieldEnum]


export const PokemonShapesScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type PokemonShapesScalarFieldEnum = (typeof PokemonShapesScalarFieldEnum)[keyof typeof PokemonShapesScalarFieldEnum]


export const PokemonColorsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type PokemonColorsScalarFieldEnum = (typeof PokemonColorsScalarFieldEnum)[keyof typeof PokemonColorsScalarFieldEnum]


export const PokemonHabitatsScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier'
} as const

export type PokemonHabitatsScalarFieldEnum = (typeof PokemonHabitatsScalarFieldEnum)[keyof typeof PokemonHabitatsScalarFieldEnum]


export const TypeEfficacyScalarFieldEnum = {
  damage_type_id: 'damage_type_id',
  target_type_id: 'target_type_id',
  damage_factor: 'damage_factor'
} as const

export type TypeEfficacyScalarFieldEnum = (typeof TypeEfficacyScalarFieldEnum)[keyof typeof TypeEfficacyScalarFieldEnum]


export const VersionGroupRegionsScalarFieldEnum = {
  version_group_id: 'version_group_id',
  region_id: 'region_id'
} as const

export type VersionGroupRegionsScalarFieldEnum = (typeof VersionGroupRegionsScalarFieldEnum)[keyof typeof VersionGroupRegionsScalarFieldEnum]


export const PokedexVersionGroupsScalarFieldEnum = {
  pokedex_id: 'pokedex_id',
  version_group_id: 'version_group_id'
} as const

export type PokedexVersionGroupsScalarFieldEnum = (typeof PokedexVersionGroupsScalarFieldEnum)[keyof typeof PokedexVersionGroupsScalarFieldEnum]


export const PokemonAbilitiesScalarFieldEnum = {
  pokemon_id: 'pokemon_id',
  ability_id: 'ability_id',
  is_hidden: 'is_hidden',
  slot: 'slot'
} as const

export type PokemonAbilitiesScalarFieldEnum = (typeof PokemonAbilitiesScalarFieldEnum)[keyof typeof PokemonAbilitiesScalarFieldEnum]


export const PokemonMovesScalarFieldEnum = {
  pokemon_id: 'pokemon_id',
  version_group_id: 'version_group_id',
  move_id: 'move_id',
  pokemon_move_method_id: 'pokemon_move_method_id',
  level: 'level',
  order: 'order',
  mastery: 'mastery'
} as const

export type PokemonMovesScalarFieldEnum = (typeof PokemonMovesScalarFieldEnum)[keyof typeof PokemonMovesScalarFieldEnum]


export const PokemonStatsScalarFieldEnum = {
  pokemon_id: 'pokemon_id',
  stat_id: 'stat_id',
  base_stat: 'base_stat',
  effort: 'effort'
} as const

export type PokemonStatsScalarFieldEnum = (typeof PokemonStatsScalarFieldEnum)[keyof typeof PokemonStatsScalarFieldEnum]


export const PokemonTypesScalarFieldEnum = {
  pokemon_id: 'pokemon_id',
  type_id: 'type_id',
  slot: 'slot'
} as const

export type PokemonTypesScalarFieldEnum = (typeof PokemonTypesScalarFieldEnum)[keyof typeof PokemonTypesScalarFieldEnum]


export const PokemonEggGroupsScalarFieldEnum = {
  species_id: 'species_id',
  egg_group_id: 'egg_group_id'
} as const

export type PokemonEggGroupsScalarFieldEnum = (typeof PokemonEggGroupsScalarFieldEnum)[keyof typeof PokemonEggGroupsScalarFieldEnum]


export const PokemonItemsScalarFieldEnum = {
  pokemon_id: 'pokemon_id',
  version_id: 'version_id',
  item_id: 'item_id',
  rarity: 'rarity'
} as const

export type PokemonItemsScalarFieldEnum = (typeof PokemonItemsScalarFieldEnum)[keyof typeof PokemonItemsScalarFieldEnum]


export const PokemonGameIndicesScalarFieldEnum = {
  pokemon_id: 'pokemon_id',
  version_id: 'version_id',
  game_index: 'game_index'
} as const

export type PokemonGameIndicesScalarFieldEnum = (typeof PokemonGameIndicesScalarFieldEnum)[keyof typeof PokemonGameIndicesScalarFieldEnum]


export const PokemonDexNumbersScalarFieldEnum = {
  species_id: 'species_id',
  pokedex_id: 'pokedex_id',
  pokedex_number: 'pokedex_number'
} as const

export type PokemonDexNumbersScalarFieldEnum = (typeof PokemonDexNumbersScalarFieldEnum)[keyof typeof PokemonDexNumbersScalarFieldEnum]


export const PokemonFormGenerationsScalarFieldEnum = {
  pokemon_form_id: 'pokemon_form_id',
  generation_id: 'generation_id',
  game_index: 'game_index'
} as const

export type PokemonFormGenerationsScalarFieldEnum = (typeof PokemonFormGenerationsScalarFieldEnum)[keyof typeof PokemonFormGenerationsScalarFieldEnum]


export const PokemonFormTypesScalarFieldEnum = {
  pokemon_form_id: 'pokemon_form_id',
  type_id: 'type_id',
  slot: 'slot'
} as const

export type PokemonFormTypesScalarFieldEnum = (typeof PokemonFormTypesScalarFieldEnum)[keyof typeof PokemonFormTypesScalarFieldEnum]


export const TypeGameIndicesScalarFieldEnum = {
  type_id: 'type_id',
  generation_id: 'generation_id',
  game_index: 'game_index'
} as const

export type TypeGameIndicesScalarFieldEnum = (typeof TypeGameIndicesScalarFieldEnum)[keyof typeof TypeGameIndicesScalarFieldEnum]


export const ItemGameIndicesScalarFieldEnum = {
  item_id: 'item_id',
  generation_id: 'generation_id',
  game_index: 'game_index'
} as const

export type ItemGameIndicesScalarFieldEnum = (typeof ItemGameIndicesScalarFieldEnum)[keyof typeof ItemGameIndicesScalarFieldEnum]


export const LocationGameIndicesScalarFieldEnum = {
  location_id: 'location_id',
  generation_id: 'generation_id',
  game_index: 'game_index'
} as const

export type LocationGameIndicesScalarFieldEnum = (typeof LocationGameIndicesScalarFieldEnum)[keyof typeof LocationGameIndicesScalarFieldEnum]


export const LocationAreaEncounterRatesScalarFieldEnum = {
  location_area_id: 'location_area_id',
  encounter_method_id: 'encounter_method_id',
  version_id: 'version_id',
  rate: 'rate'
} as const

export type LocationAreaEncounterRatesScalarFieldEnum = (typeof LocationAreaEncounterRatesScalarFieldEnum)[keyof typeof LocationAreaEncounterRatesScalarFieldEnum]


export const NatureBattleStylePreferencesScalarFieldEnum = {
  nature_id: 'nature_id',
  move_battle_style_id: 'move_battle_style_id',
  low_hp_preference: 'low_hp_preference',
  high_hp_preference: 'high_hp_preference'
} as const

export type NatureBattleStylePreferencesScalarFieldEnum = (typeof NatureBattleStylePreferencesScalarFieldEnum)[keyof typeof NatureBattleStylePreferencesScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

